class aa{constructor(){this.g=new Map}register(a,b){this.g.set(a,b)}resolve(a){if(!this.g.has(a))throw Error(`Class ${a.name||a} is not registered in Locator.`);const b=this.g.get(a);if(!b)throw Error(`Class ${a.name||a} instance is null or undefined.`);return b}locate(a){if(!this.g.has(a))try{this.g.set(a,new a)}catch(c){throw Error(`Failed to auto-instantiate Class ${a.name||a} in Locator: ${c instanceof Error?c.message:String(c)}`);}const b=this.g.get(a);if(!b)throw Error(`Class ${a.name||a} instance is null or undefined.`);
return b}};class ba{constructor(a,b=null){this.type=a;this.detail=b;this.target=null}}
class ca{constructor(){this.g={}}addEventListener(a,b){this.g[a]||(this.g[a]=[]);this.g[a].push(b)}removeEventListener(a,b){this.g[a]&&(this.g[a]=this.g[a].filter(c=>c!==b))}dispatchEvent(a){var b=a.type;if(window.__DEBUG_EVENT__){let c="";try{c=JSON.stringify(a.detail)}catch(d){c=String(a.detail)}console.log(`[Event Audit] Dispatched event "${b}" (Payload: ${c}) to ${this.g[b]?this.g[b].length:0} listener(s)`)}if(this.g[b]){a.target=this;b=[...this.g[b]];for(const c of b)c(a)}}scoped(a){return new da(this,
a)}}class da{constructor(a,b){this.h=a;this.g=b}addEventListener(a,b){this.h.addEventListener(a.startsWith(this.g+":")?a:`${this.g}:${a}`,b)}removeEventListener(a,b){this.h.removeEventListener(a.startsWith(this.g+":")?a:`${this.g}:${a}`,b)}dispatchEvent(a){a.type.startsWith(this.g+":")||(a.type=`${this.g}:${a.type}`);this.h.dispatchEvent(a)}scoped(a){return new da(this.h,`${this.g}:${a}`)}};class k{constructor(a){this.h=a;this.g=new Map}subscribe(a,b){let c=this.g.get(a);c||(c=new Map,this.g.set(a,c));if(!c.has(b)){var d=f=>{b(f.detail)};c.set(b,d);this.h.addEventListener(a,d)}}unsubscribe(a,b){const c=this.g.get(a);if(c){var d=c.get(b);d&&(this.h.removeEventListener(a,d),c.delete(b));0===c.size&&this.g.delete(a)}}publish(a,b){this.h.dispatchEvent(new ba(a,b))}};class ea{enter(){throw Error("enter() must be implemented");}exit(){throw Error("exit() must be implemented");}}class fa{constructor(){this.g={};this.currentSceneName=null;this.isTransitioning=!1}register(a,b){this.g[a]=b}transitionTo(a,b){if(!this.isTransitioning){var c=this.g[a];if(!c)throw Error(`Scene not found: ${a}`);this.isTransitioning=!0;try{this.currentSceneName&&this.g[this.currentSceneName].exit(),c.enter(b),this.currentSceneName=a}finally{this.isTransitioning=!1}}}};class ha{constructor(a="welcome"){this.h=a;this.g=[];this.currentHash=null}register(a,b){this.g.push({pattern:new RegExp("^\\/?"+a.replace(/^\//,"").replace(/\//g,"\\/")+"(?:\\?(.*))?$"),D:b})}resolve(a){if(null!==this.currentHash&&a===this.currentHash)return!1;var b=a;b.startsWith("#")&&(b=b.slice(1));b.startsWith("/")&&(b=b.slice(1));b||(b=this.h);for(var c=0;c<this.g.length;c++){const f=this.g[c];var d=b.match(f.pattern);if(d){c=d[1]||"";b={};if(c)for(c=c.split("&"),d=0;d<c.length;d++){const e=
c[d].split("=");e[0]&&(b[decodeURIComponent(e[0])]=decodeURIComponent(e[1]||""))}this.currentHash=a;f.D(b);return!0}}return!1}listen(){window.addEventListener("hashchange",()=>{this.resolve(window.location.hash)});const a=window.location.hash;a&&"#"!==a&&"#/"!==a?this.resolve(a):this.navigate("#/"+this.h)}navigate(a){window.location.hash=a}};const m=new aa;window.locator=m;class ia extends ea{enter(){const a=q.locator.resolve(r);a.welcomeScreen&&a.welcomeScreen.classList.add("hidden");a.readerScreen&&a.readerScreen.classList.add("hidden")}exit(){}}class ja extends ea{enter(){const a=q.locator.resolve(r);a.welcomeScreen&&a.welcomeScreen.classList.remove("hidden");ka()}exit(){const a=q.locator.resolve(r);a.welcomeScreen&&a.welcomeScreen.classList.add("hidden");la()}}
class ma extends ea{enter(){const a=q.locator.resolve(r);a.readerScreen&&a.readerScreen.classList.remove("hidden");na()}exit(){const a=q.locator.resolve(r);a.readerScreen&&a.readerScreen.classList.add("hidden");oa()}};class pa{get(){return Promise.reject(Error("get() must be implemented"))}save(){return Promise.reject(Error("save() must be implemented"))}delete(){return Promise.reject(Error("delete() must be implemented"))}keys(){return Promise.reject(Error("keys() must be implemented"))}clear(){return Promise.reject(Error("clear() must be implemented"))}}
class ra extends pa{get(a){try{return Promise.resolve(localStorage.getItem(a))}catch(b){return console.warn("LocalStorageRepository.get() failed:",b),Promise.resolve(null)}}save(a,b){try{localStorage.setItem(a,b)}catch(c){console.warn("LocalStorageRepository.save() failed:",c)}return Promise.resolve()}delete(a){try{localStorage.removeItem(a)}catch(b){console.warn("LocalStorageRepository.delete() failed:",b)}return Promise.resolve()}keys(){const a=[];try{for(let b=0;b<localStorage.length;b++){const c=
localStorage.key(b);null!==c&&a.push(c)}}catch(b){console.warn("LocalStorageRepository.keys() failed:",b)}return Promise.resolve(a)}clear(){try{localStorage.clear()}catch(a){console.warn("LocalStorageRepository.clear() failed:",a)}return Promise.resolve()}}
class x{constructor(a){this.storage=a;this._KEY="yuzora_config"}async load(){try{const a=await this.storage.get(this._KEY);if(a){const b=JSON.parse(a);if(b&&"object"===typeof b)return b}}catch(a){console.warn("SettingsRepository.load() failed to parse JSON:",a)}return{}}async save(a){try{await this.storage.save(this._KEY,JSON.stringify(a))}catch(b){console.warn("SettingsRepository.save() failed to serialize JSON:",b)}}async clear(){await this.storage.delete(this._KEY)}}
class y{constructor(a){this.storage=a;this._PREFIX="bookmark_"}async load(a){if(!a)return 0;try{const b=await this.storage.get(this._PREFIX+a);if(b){const c=parseFloat(b);return isNaN(c)?0:c}}catch(b){console.warn("BookmarkRepository.load() failed:",b)}return 0}async save(a,b){a&&await this.storage.save(this._PREFIX+a,b.toString())}async clearAll(){const a=(await this.storage.keys()).filter(b=>b.startsWith(this._PREFIX));await Promise.all(a.map(b=>this.storage.delete(b)))}}
class z{constructor(a){this.storage=a;this._KEY_NAME="last_read_file_name";this._KEY_CONTENT="last_read_file_content";this._KEY_TYPE="last_read_file_type"}async load(){const [a,b,c]=await Promise.all([this.storage.get(this._KEY_NAME),this.storage.get(this._KEY_CONTENT),this.storage.get(this._KEY_TYPE)]);return{name:a,content:b,type:c}}async save(a,b,c){await Promise.all([this.storage.save(this._KEY_NAME,a),this.storage.save(this._KEY_CONTENT,b),this.storage.save(this._KEY_TYPE,c)])}async clear(){await Promise.all([this.storage.delete(this._KEY_NAME),
this.storage.delete(this._KEY_CONTENT),this.storage.delete(this._KEY_TYPE)])}}const sa=new ra,ta=new x(sa),ua=new y(sa),va=new z(sa);m.register(ra,sa);m.register(x,ta);m.register(y,ua);m.register(z,va);m.register(ca,new ca);window.YuzoraEvent=ba;window.YuzoraEventTarget=ca;
window.YuzoraEventType={K:"document:load-start",I:"document:loaded",L:"document:rendered",J:"document:load-failed",U:"ui:navigate-page",V:"ui:page-changed",M:"ui:config-changed",X:"ui:toc-generated",W:"ui:toc-active-changed",Z:"ui:toggle-debug-modal",Y:"ui:toggle-controls",$:"ui:toggle-drawer",P:"system:history-updated",O:"system:diagnose-run",N:"system:diagnose-completed",S:"system:layout-repaired",R:"system:layout-check-requested",T:"system:layout-repair-requested"};m.register(k,new k(m.resolve(ca)));window.Publisher=k;class r{constructor(){this.headerTimeout=this.tabContentDiagnose=this.tabContentMonitor=this.tabBtnDiagnose=this.tabBtnMonitor=this.btnImportHistory=this.btnExportHistory=this.debugHistoryJSON=this.diagnoseReportOutput=this.btnCopyDebugReport=this.btnDiagnoseLayout=this.btnClearAll=this.btnClearConfig=this.btnClearBookmarks=this.debugMonitor=this.debugModalOverlay=this.btnCloseDebug=this.debugModal=this.btnOpenDebug=this.readerBooksGrid=this.developerBooksGrid=this.readingIndex=this.readingPercentage=
this.progressBar=this.progressBarContainer=this.readerFooter=this.readerHeader=this.pageNavRight=this.pageNavLeft=this.drawerOverlay=this.tocList=this.tocDrawer=this.settingsDrawer=this.btnCloseTOC=this.btnCloseSettings=this.btnFirstPage=this.btnTOC=this.btnSettings=this.btnBack=this.bookTitle=this.readerContent=this.readerViewport=this.fileInput=this.dropZone=this.readerScreen=this.welcomeScreen=this.app=null;this.isReflowing=!1;this.progressAnimationFrameId=this.cachedClientWidth=this.cachedScrollWidth=
this.config=this.tocObserver=this.activeHeadingId=null;this.isSnapping=!1;this.scrollStartTimestamp=null;this.scrollEventCount=0;this.tocDrawerOpen=this.settingsDrawerOpen=!1}initializeDOMElements(){this.app=document.getElementById("app");this.welcomeScreen=document.getElementById("welcome-screen");this.readerScreen=document.getElementById("reader-screen");this.dropZone=document.getElementById("drop-zone");this.fileInput=document.getElementById("file-input");this.readerViewport=document.getElementById("reader-viewport");
this.readerContent=document.getElementById("reader-content");this.bookTitle=document.getElementById("book-title");this.btnBack=document.getElementById("btn-back");this.btnSettings=document.getElementById("btn-settings");this.btnTOC=document.getElementById("btn-toc");this.btnFirstPage=document.getElementById("btn-first-page");this.btnCloseSettings=document.getElementById("btn-close-settings");this.btnCloseTOC=document.getElementById("btn-close-toc");this.settingsDrawer=document.getElementById("settings-drawer");
this.tocDrawer=document.getElementById("toc-drawer");this.tocList=document.getElementById("toc-list");this.drawerOverlay=document.getElementById("drawer-overlay");this.pageNavLeft=document.getElementById("page-nav-left");this.pageNavRight=document.getElementById("page-nav-right");this.readerHeader=document.querySelector(".reader-header");this.readerFooter=document.querySelector(".reader-footer");this.progressBarContainer=document.querySelector(".progress-bar-container");this.progressBar=document.getElementById("progress-bar");
this.readingPercentage=document.getElementById("reading-percentage");this.readingIndex=document.getElementById("reading-index");this.developerBooksGrid=document.getElementById("developer-books-grid");this.readerBooksGrid=document.getElementById("reader-books-grid");this.btnOpenDebug=document.getElementById("btn-open-debug");this.debugModal=document.getElementById("debug-modal");this.btnCloseDebug=document.getElementById("btn-close-debug");this.debugModalOverlay=document.getElementById("debug-modal-overlay");
this.debugMonitor=document.getElementById("debug-monitor");this.btnClearBookmarks=document.getElementById("btn-clear-bookmarks");this.btnClearConfig=document.getElementById("btn-clear-config");this.btnClearAll=document.getElementById("btn-clear-all");this.btnDiagnoseLayout=document.getElementById("btn-diagnose-layout");this.btnCopyDebugReport=document.getElementById("btn-copy-debug-report");this.diagnoseReportOutput=document.getElementById("diagnose-report-output");this.debugHistoryJSON=document.getElementById("debug-history-json");
this.btnExportHistory=document.getElementById("btn-export-history");this.btnImportHistory=document.getElementById("btn-import-history");this.tabBtnMonitor=document.getElementById("tab-btn-monitor");this.tabBtnDiagnose=document.getElementById("tab-btn-diagnose");this.tabContentMonitor=document.getElementById("debug-tab-content-monitor");this.tabContentDiagnose=document.getElementById("debug-tab-content-diagnose")}}
class A{constructor(){this.type=this.content=this.author=this.title="";this.currentPage=this.totalPages=0;this.toc=[]}isEmpty(){return!this.title||!this.content}clear(){this.type=this.content=this.author=this.title="";this.currentPage=this.totalPages=0;this.toc=[]}}
class C{constructor(){this.theme="sepia";this.font="font-gothic";this.direction="rtl";this.size="size-md";this.lh="line-height-normal";this.spacing="spacing-normal";this.headingPageBreakMode="large-medium"}async load(){const a=await q.locator.resolve(x).load();a&&"object"===typeof a&&0<Object.keys(a).length&&(a.theme&&(this.theme=a.theme),a.font&&(this.font=a.font),a.direction&&(this.direction=a.direction),a.size&&(this.size=a.size),a.lh&&(this.lh=a.lh),a.spacing&&(this.spacing=a.spacing),a.headingPageBreakMode&&
(this.headingPageBreakMode=a.headingPageBreakMode))}async save(){await q.locator.resolve(x).save({theme:this.theme,font:this.font,direction:this.direction,size:this.size,lh:this.lh,spacing:this.spacing,headingPageBreakMode:this.headingPageBreakMode})}apply(){document.body.setAttribute("data-theme",this.theme);var a=q.locator.resolve(r);a.readerContent&&a.readerViewport&&(a.readerViewport.style.direction=this.direction,a.readerContent.className="reader-content",a.readerContent.classList.add(this.font,
`direction-${this.direction}`,this.size,this.lh,this.spacing),"rtl"===this.direction?(a.pageNavLeft.title="\u6b21\u306e\u30da\u30fc\u30b8\u3078",a.pageNavRight.title="\u524d\u306e\u30da\u30fc\u30b8\u3078"):(a.pageNavLeft.title="\u524d\u306e\u30da\u30fc\u30b8\u3078",a.pageNavRight.title="\u6b21\u306e\u30da\u30fc\u30b8\u3078"),(a=a.btnFirstPage?a.btnFirstPage.querySelector("path"):null)&&("rtl"===this.direction?a.setAttribute("d","M11.25 4.5l7.5 7.5-7.5 7.5m-6-15l7.5 7.5-7.5 7.5"):a.setAttribute("d",
"M18.75 19.5l-7.5-7.5 7.5-7.5m-6 15L5.25 12l7.5-7.5")),"function"===typeof F&&(F(".theme-selector button","theme",this.theme),F(".font-selector button","font",this.font),F(".direction-selector button","direction",this.direction),F(".size-selector button","size",this.size),F(".lh-selector button","lh",this.lh),F(".spacing-selector button","spacing",this.spacing)),a=document.getElementById("select-heading-break"))&&(a.value=this.headingPageBreakMode)}}
class G{constructor(){this.bookmarkProgress=0}async save(a,b){a&&(this.bookmarkProgress=b,await q.locator.resolve(y).save(a,b))}async load(a){return a?this.bookmarkProgress=await q.locator.resolve(y).load(a):this.bookmarkProgress=0}clear(){this.bookmarkProgress=0}}
var wa=[{id:"kokoro",title:"\u3053\u3053\u308d",j:"\u3053\u3053\u308d",l:773,path:"src/books/773_yoko.txt",i:"developer",author:"\u590f\u76ee\u6f31\u77f3",m:"\u590f\u76ee\u6f31\u77f3"},{id:"gokyo",title:"\u6545\u90f7",j:"\u6545\u90f7",l:42939,path:"src/books/42939_yoko.txt",i:"developer",author:"\u9b6f\u8fc5",m:"\u9b6f\u8fc5"},{id:"musashi_01",title:"\u5bae\u672c\u6b66\u8535 01 \u5e8f\u3001\u306f\u3057\u304c\u304d",j:"\u5e8f\u3001\u306f\u3057\u304c\u304d",l:52395,path:"src/books/52395_yoko.txt",i:"reader",
author:"\u5409\u5ddd\u82f1\u6cbb",m:"01"},{id:"musashi_02",title:"\u5bae\u672c\u6b66\u8535 02 \u5730\u306e\u5dfb",j:"\u5730\u306e\u5dfb",l:52396,path:"src/books/52396_yoko.txt",i:"reader",author:"\u5409\u5ddd\u82f1\u6cbb",m:"02"},{id:"musashi_03",title:"\u5bae\u672c\u6b66\u8535 03 \u6c34\u306e\u5dfb",j:"\u6c34\u306e\u5dfb",l:52397,path:"src/books/52397_yoko.txt",i:"reader",author:"\u5409\u5ddd\u82f1\u6cbb",m:"03"},{id:"musashi_04",title:"\u5bae\u672c\u6b66\u8535 04 \u706b\u306e\u5dfb",j:"\u706b\u306e\u5dfb",
l:52398,path:"src/books/52398_yoko.txt",i:"reader",author:"\u5409\u5ddd\u82f1\u6cbb",m:"04"},{id:"musashi_05",title:"\u5bae\u672c\u6b66\u8535 05 \u98a8 of the roll",j:"\u98a8\u306e\u5dfb",l:52399,path:"src/books/52399_yoko.txt",i:"reader",author:"\u5409\u5ddd\u82f1\u6cbb",m:"05"},{id:"musashi_06",title:"\u5bae\u672c\u6b66\u8535 06 \u7a7a\u306e\u5dfb",j:"\u7a7a\u306e\u5dfb",l:52400,path:"src/books/52400_yoko.txt",i:"reader",author:"\u5409\u5ddd\u82f1\u6cbb",m:"06"},{id:"musashi_07",title:"\u5bae\u672c\u6b66\u8535 07 \u4e8c\u5929\u306e\u5dfb",
j:"\u4e8c\u5929\u306e\u5dfb",l:52401,path:"src/books/52401_yoko.txt",i:"reader",author:"\u5409\u5ddd\u82f1\u6cbb",m:"07"},{id:"musashi_08",title:"\u5bae\u672c\u6b66\u8535 08 \u5186\u660e\u306e\u5dfb",j:"\u5186\u660e\u306e\u5dfb",l:52402,path:"src/books/52402_yoko.txt",i:"reader",author:"\u5409\u5ddd\u82f1\u6cbb",m:"08"}];m.register(r,new r);m.register(A,new A);m.register(C,new C);m.register(G,new G);class xa{constructor(a){this.id=a;this.type="book";this.status="loading";this.error=null}dispose(){this.type=this.id="";this.status="failed";this.error=null}}class ya extends xa{constructor(a){super(a);this.content=this.title="";this.toc=[]}dispose(){super.dispose();this.content=this.title="";this.toc=[]}};class H{constructor(){this.assets=new Map}loadBook(a,b,c){if(b.startsWith("http://")||b.startsWith("https://")||b.startsWith("//"))try{var d=(new URL(b,window.location.href)).origin===window.location.origin}catch(e){d=!1}else d=!0;if(!d)return c=Error("Security Error: Fetching from external origin is blocked."),b=new ya(a),b.status="failed",b.error=c,this.assets.set(a,b),Promise.reject(c);if(this.assets.has(a)&&(b=this.assets.get(a),b instanceof ya)){if("ready"===b.status)return Promise.resolve(b);
if("loading"===b.status)return Promise.reject(Error("Asset is currently loading."))}var f=new ya(a);this.assets.set(a,f);return c().then(e=>{if(e&&2097152<e.length)throw e=Error("File size exceeds the 2MB safety limit."),f.status="failed",f.error=e,e;f.content=e;f.status="ready";return f}).catch(e=>{f.status="failed";f.error=e;throw e;})}unload(a){this.assets.has(a)&&(this.assets.get(a).dispose(),this.assets.delete(a))}clear(){this.assets.forEach(a=>{a.dispose()});this.assets.clear()}}
window.ResourceDirector=H;class I{constructor(a){this.type=a}execute(){throw Error("execute() must be implemented");}serialize(){return{type:this.type,params:{}}}}
class za extends I{constructor(a,b){super("LoadBook");this.fileName=a;this.fileContent=b}execute(){const a=q.locator.resolve(A),b=this;q.locator.resolve(H).loadBook(this.fileName,this.fileName,function(){return Promise.resolve(b.fileContent)}).then(function(c){a.title=c.id;a.type=c.id.endsWith(".html")||c.id.endsWith(".xhtml")?"html":"txt";a.content=c.content;yuzora.publisher.publish("document:loaded",{fileName:b.fileName,fileContent:b.fileContent})}).catch(function(c){console.error("LoadBookCommand execution failed:",
c)})}serialize(){return{type:this.type,params:{fileName:this.fileName,fileContent:this.fileContent}}}}class J extends I{constructor(a){super("NavigatePage");this.targetPage=a}execute(){q.locator.resolve(r).readerViewport&&yuzora.publisher.publish("ui:navigate-page",{targetPage:this.targetPage})}serialize(){return{type:this.type,params:{targetPage:this.targetPage}}}}
class K extends I{constructor(a,b){super("UpdateConfig");this.configKey=a;this.configValue=b}async execute(){const a=q.locator.resolve(r),b=q.locator.resolve(C),c=q.locator.resolve(G);b[this.configKey]=this.configValue;Ca(this.configKey,this.configValue);a.isReflowing=!0;Da();setTimeout(()=>{const d=Math.abs(a.readerViewport.scrollWidth-a.readerViewport.clientWidth);a.readerViewport.scrollLeft="rtl"===b.direction?-(c.bookmarkProgress*d):c.bookmarkProgress*d;a.isReflowing=!1},150);await Ea()}serialize(){return{type:this.type,
params:{configKey:this.configKey,configValue:this.configValue}}}}class Fa extends I{constructor(a){super("SyncBookmark");this.progress=a}execute(){q.locator.resolve(G).bookmarkProgress=this.progress}serialize(){return{type:this.type,params:{progress:this.progress}}}}
class Ga extends I{constructor(a){super("ToggleControls");this.visible=a}execute(){if(this.visible)Ha();else{const a=q.locator.resolve(r);a.headerTimeout&&clearTimeout(a.headerTimeout);Ia()}}serialize(){return{type:this.type,params:{visible:this.visible}}}}
class L extends I{constructor(a,b){super("ToggleDrawer");this.drawerId=a;this.open=b}execute(){const a=q.locator.resolve(r);var b="settings"===this.drawerId?a.settingsDrawer:a.tocDrawer;b&&(this.open?(b.classList.add("open"),a.drawerOverlay&&a.drawerOverlay.classList.add("active"),"toc"===this.drawerId&&Ja()):(b.classList.remove("open"),(b="settings"===this.drawerId?a.tocDrawer:a.settingsDrawer)&&!b.classList.contains("open")&&a.drawerOverlay&&a.drawerOverlay.classList.remove("active")))}serialize(){return{type:this.type,
params:{drawerId:this.drawerId,open:this.open}}}}class Ka extends I{constructor(){super("ExitReader")}execute(){const a=q.locator.resolve(A),b=q.locator.resolve(z),c=q.locator.resolve(ha),d=q.locator.resolve(r);c.navigate("/welcome");b.clear();a.clear();d.isReflowing=!1;window.__isReflowing__=!1}serialize(){return{type:this.type,params:{}}}}
class La extends I{constructor(a){super("ClearStorage");this.clearType=a}async execute(){const a=q.locator.resolve(G),b=q.locator.resolve(y),c=q.locator.resolve(x),d=q.locator.resolve(z);"bookmarks"===this.clearType?(await b.clearAll(),a.bookmarkProgress=0,Ma()):"config"===this.clearType?(await c.clear(),M.isReplaying||window.location.reload()):"all"===this.clearType&&(await Promise.all([b.clearAll(),c.clear(),d.clear()]),M.isReplaying||window.location.reload())}serialize(){return{type:this.type,
params:{clearType:this.clearType}}}}class N extends I{constructor(a){super("ToggleDebugModal");this.open=a}execute(){yuzora.publisher.publish("ui:toggle-debug-modal",{open:this.open})}serialize(){return{type:this.type,params:{open:this.open}}}}function Na(a){yuzora.publisher.publish("system:history-updated",{history:a.commandHistory.map(b=>b.serialize()),ba:!1,aa:!1})}
function Oa(a){switch(a.type){case "LoadBook":return new za(a.params.fileName,a.params.fileContent);case "NavigatePage":return new J(a.params.targetPage);case "UpdateConfig":return new K(a.params.configKey,a.params.configValue);case "SyncBookmark":return new Fa(a.params.progress);case "ToggleControls":return new Ga(a.params.visible);case "ToggleDrawer":return new L(a.params.drawerId,a.params.open);case "ExitReader":return new Ka;case "ClearStorage":return new La(a.params.clearType);case "ToggleDebugModal":return new N(a.params.open);
default:throw Error(`Unknown command type: ${a.type}`);}}function Pa(a,b,c){return(b={LoadBook:a.o,NavigatePage:a.s,UpdateConfig:a.h,SyncBookmark:a.v,ToggleControls:a.F,ToggleDrawer:a.H,ExitReader:()=>!0,ClearStorage:a.g,ToggleDebugModal:a.G}[b])?b.call(a,c):!1}
class O{constructor(){this.commandHistory=[];this.isReplaying=!1}undo(){console.warn("Undo operation is not implemented.")}redo(){console.warn("Redo operation is not implemented.")}async execute(a,b=!1){if(!this.isReplaying||b){await a.execute();if(b=!b)0===this.commandHistory.length?b=!1:(b=this.commandHistory[this.commandHistory.length-1],b="NavigatePage"===a.type&&"NavigatePage"===b.type?b.targetPage===a.targetPage:"SyncBookmark"===a.type&&"SyncBookmark"===b.type?.001>Math.abs(b.progress-a.progress):
!1),b=!b;b&&(this.commandHistory.push(a),100>=this.commandHistory.length||("LoadBook"===this.commandHistory[0].type?this.commandHistory.splice(1,1):this.commandHistory.shift()),Na(this))}}exportJSON(){return JSON.stringify(this.commandHistory.map(a=>a.serialize()),null,2)}h(a){if(!a||"string"!==typeof a.configKey||"string"!==typeof a.configValue)return!1;var b={theme:["sepia","light","dark","black"],font:["font-mincho","font-gothic"],direction:["rtl","ltr"],size:["size-sm","size-md","size-lg"],lh:["line-height-sm",
"line-height-normal","line-height-lg"],spacing:["spacing-sm","spacing-normal","spacing-lg"]};if(!Object.prototype.hasOwnProperty.call(b,a.configKey))return!1;b=b[a.configKey];return!!b&&b.includes(a.configValue)}o(a){return!!a&&"string"===typeof a.fileName&&"string"===typeof a.fileContent}s(a){return!!a&&"number"===typeof a.targetPage&&!isNaN(a.targetPage)&&1<=a.targetPage}v(a){return!!a&&"number"===typeof a.progress&&!isNaN(a.progress)&&0<=a.progress&&1>=a.progress}F(a){return!!a&&"boolean"===typeof a.visible}H(a){return!!a&&
("settings"===a.drawerId||"toc"===a.drawerId)&&"boolean"===typeof a.open}g(a){return!!a&&["bookmarks","config","all"].includes(a.clearType)}G(a){return!!a&&"boolean"===typeof a.open}importJSON(a){try{const c=JSON.parse(a);if(!Array.isArray(c))throw Error("Input operations history must be a JSON array");a=[];for(const d of c){a:{if(!d||"object"!==typeof d||"string"!==typeof d.type||!d.params||"object"!==typeof d.params){var b=!1;break a}const f=d.params;for(const e of Object.keys(f))if("__proto__"===
e||"constructor"===e||"prototype"===e){b=!1;break a}b=Pa(this,d.type,f)}if(b){const f=Oa(d);f&&a.push(f)}else console.warn("Skipping invalid/unsafe command item:",d)}return a}catch(c){return console.error("Failed to parse operations history JSON:",c),alert(`\u5c65\u6b74\u30c7\u30fc\u30bf\u306e\u30a4\u30f3\u30dd\u30fc\u30c8\u306b\u5931\u6557\u3057\u307e\u3057\u305f:\n${c instanceof Error?c.message:String(c)}`),null}}updateDebugMonitor(){const a=q.locator.resolve(r);if(a.debugMonitor){var b=document.querySelector('meta[name="build-id"]'),
c=document.querySelector('meta[name="build-date"]');b=b&&b.content?b.content:"";c=c&&c.content?c.content:"";a.debugMonitor.textContent=`Build: ${b&&"BUILD_ID_PLACEHOLDER"!==b?b:"dev"}  ${c&&"BUILD_DATE_PLACEHOLDER"!==c?c:"---"}\nHistory: ${this.commandHistory.length} operations.`}}}const Qa=new O;m.register(O,Qa);m.register(O,Qa);var M=m.resolve(O);class P{constructor(a,b,c,d){this.type=a;this.value=b;this.rt=c;this.children=d}}class Ra extends P{constructor(){super("Root",void 0,void 0,[])}}class Sa extends P{constructor(a){super("Text",a,void 0,void 0)}}class Ta extends P{constructor(a,b){super("Ruby",a,b,void 0)}}class Ua extends P{constructor(){super("Bold",void 0,void 0,[])}}class Va extends P{constructor(){super("Italic",void 0,void 0,[])}}class Wa extends P{constructor(){super("Bouten",void 0,void 0,[])}}
class Xa extends P{constructor(a){super("Document",void 0,void 0,a)}}class Ya extends P{constructor(a,b){super("CoverPage");this.title=a;this.author=b}}class Za extends P{constructor(){super("PageBreak")}}class $a extends P{constructor(){super("EmptyLine")}}class ab extends P{constructor(a,b,c,d,f){super("Heading",void 0,void 0,c);this.level=a;this.headingId=b;this.jisageClass=d;this.alignmentClass=f}}
class bb extends P{constructor(a,b,c){super("Paragraph",void 0,void 0,c);this.jisageClass=a;this.alignmentClass=b}};class cb{tokenize(a){const b=[];a=a.split(/\r?\n/);for(let g=0;g<a.length;g++){let h=a[g];if(0===h.trim().length){b.push({type:"BLOCK_EMPTY_LINE",value:h,rt:void 0,children:void 0,headingLevel:void 0,headingText:void 0,jisageClass:void 0,alignmentClass:void 0,inlineTokens:void 0});continue}if("\uff3b\uff03\u6539\u30da\u30fc\u30b8\uff3d"===h.trim()){b.push({type:"BLOCK_PAGE_BREAK",value:h,rt:void 0,children:void 0,headingLevel:void 0,headingText:void 0,jisageClass:void 0,alignmentClass:void 0,inlineTokens:void 0});
continue}var c="",d=h.match(/\uff3b\uff03([\uff10-\uff190-9]+)\u5b57\u4e0b\u3052\uff3d/);d&&(c=d[1].replace(/[\uff10-\uff19]/g,n=>String.fromCharCode(n.charCodeAt(0)-65248)),c=`jisage${parseInt(c,10)}`,h=h.replace(/\uff3b\uff03[\uff10-\uff190-9]+\u5b57\u4e0b\u3052\uff3d/,""));d="";if(h.includes("\uff3b\uff03\u5730\u4ed8\u304d\uff3d"))d="chitsuki",h=h.replace(/\uff3b\uff03\u5730\u4ed8\u304d\uff3d/g,"");else if(h.includes("\uff3b\uff03\u5730\u5bc4\u305b\uff3d"))d="chiyose",h=h.replace(/\uff3b\uff03\u5730\u5bc4\u305b\uff3d/g,
"");else{var f=h.match(/\uff3b\uff03\u5730\u304b\u3089([\uff10-\uff190-9]+)\u5b57\u4e0a\u3052\uff3d/);f&&(d=f[1].replace(/[\uff10-\uff19]/g,n=>String.fromCharCode(n.charCodeAt(0)-65248)),d=`chitage-${parseInt(d,10)}`,h=h.replace(/\uff3b\uff03\u5730\u304b\u3089[\uff10-\uff190-9]+\u5b57\u4e0a\u3052\uff3d/g,""))}f=!1;let l=2,p="";var e=h.match(/\uff3b\uff03\u300c([^\u300d]+)\u300d\u306f(\u5927|\u4e2d|\u5c0f)\u898b\u51fa\u3057\uff3d/);e&&(f=!0,p=e[1],e=e[2],"\u5927"===e?l=2:"\u4e2d"===e?l=3:"\u5c0f"===
e&&(l=4),h=h.replace(/\uff3b\uff03\u300c[^\u300d]+\u300d\u306f(?:\u5927|\u4e2d|\u5c0f)\u898b\u51fa\u3057\uff3d/,""));e=this.tokenizeInline(h);f?b.push({type:"BLOCK_HEADING",value:h,rt:void 0,children:void 0,headingLevel:l,headingText:p,jisageClass:c,alignmentClass:d,inlineTokens:e}):b.push({type:"BLOCK_PARAGRAPH",value:h,rt:void 0,children:void 0,headingLevel:void 0,headingText:void 0,jisageClass:c,alignmentClass:d,inlineTokens:e})}return b}tokenizeInline(a){const b=[];let c=0;for(;c<a.length;){if("\uff5c"===
a[c]||"|"===a[c]){var d=a.indexOf("\u300a",c);if(-1!==d){var f=a.indexOf("\u300b",d);if(-1!==f){b.push({type:"RUBY",value:a.substring(c+1,d),rt:a.substring(d+1,f),children:void 0,headingLevel:void 0,headingText:void 0,jisageClass:void 0,alignmentClass:void 0,inlineTokens:void 0});c=f+1;continue}}}if(d=a.substring(c).match(/^((?:[\u4e00-\u9fa0\u3005\u4edd\u3006\u3007\u30f6]|\u203b\uff3b\uff03\u4e8c\u306e\u5b57\u70b9\u3001\u9762\u533a\u70b9\u756a\u53f71-2-22\uff3d)+|[A-Za-z]+)\u300a([^\u300b]+)\u300b/))b.push({type:"RUBY",
value:d[1],rt:d[2],children:void 0,headingLevel:void 0,headingText:void 0,jisageClass:void 0,alignmentClass:void 0,inlineTokens:void 0}),c+=d[0].length;else if(a.startsWith("\uff3b\uff03\u3053\u3053\u304b\u3089\u592a\u5b57\uff3d",c))b.push({type:"BOLD_START",value:void 0,rt:void 0,children:void 0,headingLevel:void 0,headingText:void 0,jisageClass:void 0,alignmentClass:void 0,inlineTokens:void 0}),c+=9;else if(a.startsWith("\uff3b\uff03\u3053\u3053\u3067\u592a\u5b57\u7d42\u308f\u308a\uff3d",c))b.push({type:"BOLD_END",
value:void 0,rt:void 0,children:void 0,headingLevel:void 0,headingText:void 0,jisageClass:void 0,alignmentClass:void 0,inlineTokens:void 0}),c+=11;else if(a.startsWith("\uff3b\uff03\u3053\u3053\u304b\u3089\u659c\u4f53\uff3d",c))b.push({type:"ITALIC_START",value:void 0,rt:void 0,children:void 0,headingLevel:void 0,headingText:void 0,jisageClass:void 0,alignmentClass:void 0,inlineTokens:void 0}),c+=9;else if(a.startsWith("\uff3b\uff03\u3053\u3053\u3067\u659c\u4f53\u7d42\u308f\u308a\uff3d",c))b.push({type:"ITALIC_END",
value:void 0,rt:void 0,children:void 0,headingLevel:void 0,headingText:void 0,jisageClass:void 0,alignmentClass:void 0,inlineTokens:void 0}),c+=11;else if(a.startsWith("\uff3b\uff03\u508d\u70b9\uff3d",c))b.push({type:"BOUTEN_START",value:void 0,rt:void 0,children:void 0,headingLevel:void 0,headingText:void 0,jisageClass:void 0,alignmentClass:void 0,inlineTokens:void 0}),c+=5;else if(a.startsWith("\uff3b\uff03\u508d\u70b9\u7d42\u308f\u308a\uff3d",c))b.push({type:"BOUTEN_END",value:void 0,rt:void 0,
children:void 0,headingLevel:void 0,headingText:void 0,jisageClass:void 0,alignmentClass:void 0,inlineTokens:void 0}),c+=8;else{if(a.startsWith("\uff3b\uff03",c)&&(d=a.indexOf("\uff3d",c),-1!==d)){c=d+1;continue}d=a.length;f=["\uff5c","|","\uff3b\uff03","\u300a"];for(let e=0;e<f.length;e++){const g=a.indexOf(f[e],c);-1!==g&&g<d&&(d=g)}f=a.substring(c,d);"\u300a"===a[d]&&(f=f.match(/([\u4e00-\u9fa0\u3005\u4edd\u3006\u3007\u30f6]+|[A-Za-z]+)$/))&&(d=c+f.index);d===c?(b.push({type:"TEXT",value:a[c],
rt:void 0,children:void 0,headingLevel:void 0,headingText:void 0,jisageClass:void 0,alignmentClass:void 0,inlineTokens:void 0}),c++):(b.push({type:"TEXT",value:a.substring(c,d),rt:void 0,children:void 0,headingLevel:void 0,headingText:void 0,jisageClass:void 0,alignmentClass:void 0,inlineTokens:void 0}),c=d)}}return b}}window.AozoraTokenizer=cb;function db(a,b,c){if(b.children)for(let d=0;d<b.children.length;d++){const f=b.children[d];"Ruby"===f.type?c?(console.warn(`Semantic Warning: Nested ruby tag detected for "${f.value}". Flatting it to plain text.`),b.children[d]=new Sa(f.value||"")):db(a,f,!0):db(a,f,c)}}class eb{analyze(a){db(this,a,!1);return a}}window.AozoraSemanticAnalyzer=eb;function Q(a,b){if("Document"===b.type)return(b.children||[]).map(f=>Q(a,f)).join("\n");if("CoverPage"===b.type){var c=a.escapeHTML(b.title||"");b=a.escapeHTML(b.author||"");return`<div class="book-cover-page">\n    <h1 class="book-cover-title">${c}</h1>\n    <p class="book-cover-author">${b}</p>\n</div>`}if("PageBreak"===b.type)return'<div class="page-break"></div>';if("EmptyLine"===b.type)return'<p class="empty-line">&nbsp;</p>';if("Heading"===b.type){c=b.level||2;const f=b.headingId||"";var d=
[];b.jisageClass&&d.push(b.jisageClass);b.alignmentClass&&d.push(b.alignmentClass);d=0<d.length?` class="${d.join(" ")}"`:"";b=(b.children||[]).map(e=>Q(a,e)).join("");return`<h${c} id="${f}"${d}>${b}</h${c}>`}return"Paragraph"===b.type?(c=[],b.jisageClass&&c.push(b.jisageClass),b.alignmentClass&&c.push(b.alignmentClass),c=0<c.length?` class="${c.join(" ")}"`:"",b=(b.children||[]).map(f=>Q(a,f)).join(""),`<p${c}>${b}</p>`):"Root"===b.type?(b.children||[]).map(f=>Q(a,f)).join(""):"Text"===b.type?a.escapeHTML(b.value||
""):"Ruby"===b.type?`<ruby>${a.escapeHTML(b.value||"")}<rt>${a.escapeHTML(b.rt||"")}</rt></ruby>`:"Bold"===b.type?`<strong class="aozora-bold">${(b.children||[]).map(f=>Q(a,f)).join("")}</strong>`:"Italic"===b.type?`<em class="aozora-italic">${(b.children||[]).map(f=>Q(a,f)).join("")}</em>`:"Bouten"===b.type?`<span class="em-sesame">${(b.children||[]).map(f=>Q(a,f)).join("")}</span>`:""}
class R{evaluate(a){return Q(this,a)}escapeHTML(a){return a?a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#x27;"):""}sanitizeDOM(a){function b(e){var g=Array.from(e.attributes);for(const h of g)if(g=h.name.toLowerCase(),g.startsWith("on")||!f.has(g))e.removeAttribute(h.name);else if("href"===g||"src"===g)g=h.value.trim().toLowerCase(),(g.startsWith("javascript:")||g.startsWith("data:")||g.startsWith("vbscript:"))&&e.removeAttribute(h.name)}
function c(e){e=Array.from(e.childNodes);for(const g of e)if(1===g.nodeType){e=g;const h=e.tagName.toLowerCase();if(d.has(h))b(e),c(e);else{if(!["script","style","iframe"].includes(h))for(;e.firstChild;)e.parentNode.insertBefore(e.firstChild,e);e.remove()}}}const d=new Set("div span p h1 h2 h3 h4 h5 h6 a ruby rt rp br img b i strong em".split(" ")),f=new Set(["class","id","src","alt","href"]);b(a);c(a)}}window.AozoraEvaluator=R;function fb(a){return a?a.replace(/[\uff5c|]/g,"").replace(/\u300a[^\u300b]+\u300b/g,"").trim():""}
class S{constructor(){this.h=q.locator.resolve(cb);this.v=q.locator.resolve(eb);this.g=q.locator.resolve(R);this.o=q.locator.resolve(C);this.s=new DOMParser}parseTokensToAST(a){const b=new Ra,c=[b];for(let f=0;f<a.length;f++){var d=a[f];const e=c[c.length-1];"TEXT"===d.type?e.children.push(new Sa(d.value||"")):"RUBY"===d.type?e.children.push(new Ta(d.value||"",d.rt||"")):"BOLD_START"===d.type?(d=new Ua,e.children.push(d),c.push(d)):"BOLD_END"===d.type?1<c.length&&"Bold"===c[c.length-1].type&&c.pop():
"ITALIC_START"===d.type?(d=new Va,e.children.push(d),c.push(d)):"ITALIC_END"===d.type?1<c.length&&"Italic"===c[c.length-1].type&&c.pop():"BOUTEN_START"===d.type?(d=new Wa,e.children.push(d),c.push(d)):"BOUTEN_END"===d.type&&1<c.length&&"Bouten"===c[c.length-1].type&&c.pop()}return b}parseAozoraText(a){var b=q.locator.resolve(A);b.toc=[];let c=0;const d=this.h.tokenize(a);let f=a="";var e=0;for(var g=0;g<d.length;g++){var h=d[g];if("BLOCK_EMPTY_LINE"!==h.type&&"BLOCK_PAGE_BREAK"!==h.type)if(0===e)a=
fb(h.value||""),e++;else if(1===e){f=fb(h.value||"");break}}b.title=a;b.author=f;e=[];e.push(new Ya(a,f));e.push(new Za);g=!0;h=!1;for(let B=0;B<d.length;B++){var l=d[B],p=l.value||"";if(g){if(p.includes("-------------------------------------------------------")){g=!1;var n=d[B+1],v=d[B+2];v=v?(v.value||"").trim():"";if((n?(n.value||"").trim():"").includes("\u3010\u30c6\u30ad\u30b9\u30c8\u4e2d\u306b\u73fe\u308c\u308b\u8a18\u53f7\u306b\u3064\u3044\u3066\u3011")||v.includes("\u3010\u30c6\u30ad\u30b9\u30c8\u4e2d\u306b\u73fe\u308c\u308b\u8a18\u53f7\u306b\u3064\u3044\u3066\u3011"))h=
!0;continue}n=p;v=B;if(n.includes("-------------------------------------------------------")||n.includes("\uff3b\uff03")&&(n.includes("\u59cb\u307e\u308a")||n.includes("\u76ee\u6b21"))||0<n.trim().length&&!n.startsWith("\uff3b\uff03")&&2<v)g=!1;else continue}if(h)p.includes("-------------------------------------------------------")&&(h=!1);else if("BLOCK_EMPTY_LINE"===l.type)e.push(new $a);else if("BLOCK_PAGE_BREAK"===l.type)e.push(new Za);else if(n=l.jisageClass||"",v=l.alignmentClass||"",p=this.parseTokensToAST(l.inlineTokens||
[]).children||[],"BLOCK_HEADING"===l.type){const w=l.headingLevel||2;l=l.headingText||"";var t=this.o.headingPageBreakMode||"large-medium",u=!1;"large"===t&&2===w?u=!0:"large-medium"!==t||2!==w&&3!==w?"all"!==t||2!==w&&3!==w&&4!==w||(u=!0):u=!0;if(u){t=null;for(u=e.length-1;0<=u;u--)if("EmptyLine"!==e[u].type){t=e[u];break}t&&"Heading"!==t.type&&"PageBreak"!==t.type&&"CoverPage"!==t.type&&e.push(new Za)}t=`toc-heading-${c}`;l=l.replace(/[\uff5c|]/g,"").replace(/\u300a[^\u300b]+\u300b/g,"").trim();
b.toc.push({id:t,text:l,level:w});c++;e.push(new ab(w,t,p,n,v))}else e.push(new bb(n,v,p))}b=this.g.evaluate(new Xa(e));return{title:a+(f?` (${f})`:""),body:b}}parseAozoraHTML(a){var b=this.s.parseFromString(a,"text/html");a=(a=b.querySelector("title"))?a.textContent:"";let c=b.querySelector(".main_body");c||=b.querySelector("body");(b=c.querySelector(".bibliographical_information"))&&b.remove();(b=c.querySelector(".card_link"))&&b.remove();this.g.sanitizeDOM(c);return{title:a||"",body:c.innerHTML}}formatAozoraMarkup(a){a=
this.h.tokenizeInline(a);a=this.parseTokensToAST(a);a=this.v.analyze(a);return this.g.evaluate(a)}}window.AozoraParser=S;function gb(a){if(!a)return{currentPage:0,C:0};const b=Math.abs(a.scrollLeft),c=Math.round(a.scrollWidth/a.clientWidth)||0;return{currentPage:0<a.scrollWidth-a.clientWidth?Math.round(b/a.clientWidth)+1:0<c?1:0,C:c}}
function hb(a,b){const c=q.locator.resolve(A),d=q.locator.resolve(C),f=q.locator.resolve(G),e=q.locator.resolve(r);let g;g="### \ud83d\udcd6 \u3086\u3046\u305e\u3089 \u30ec\u30a4\u30a2\u30a6\u30c8\u8a3a\u65ad\u30ec\u30dd\u30fc\u30c8\n"+`- **\u65e5\u6642**: ${(new Date).toLocaleString()}\n`;g+=`- **\u30d5\u30a1\u30a4\u30eb\u540d**: ${c.title||"(\u672a\u30ed\u30fc\u30c9)"}\n`;g+=`- **\u30d5\u30a1\u30a4\u30eb\u7a2e\u5225**: ${c.type||"(\u306a\u3057)"}\n`;g=g+"- **\u8868\u793a\u8a2d\u5b9a**:\n"+`  - \u30c6\u30fc\u30de: ${d.theme}\n`;
g+=`  - \u66f8\u4f53: ${"font-mincho"===d.font?"\u660e\u671d\u4f53":"\u30b4\u30b7\u30c3\u30af\u4f53"}\n`;g+=`  - \u9001\u308a\u65b9\u5411: ${"rtl"===d.direction?"\u53f3\u304b\u3089\u5de6 (RTL)":"\u5de6\u304b\u3089\u53f3 (LTR)"}\n`;g+=`  - \u6587\u5b57\u30b5\u30a4\u30ba: ${d.size}\n`;g+=`  - \u884c\u9593: ${d.lh}\n`;g+=`  - \u6587\u5b57\u9593: ${d.spacing}\n`;g=g+"- **\u753b\u9762\u30b5\u30a4\u30ba**:\n"+`  - \u30d3\u30e5\u30fc\u30dd\u30fc\u30c8\u5e45(clientWidth): ${e.readerViewport.clientWidth}px\n`;
g+=`  - \u30d3\u30e5\u30fc\u30dd\u30fc\u30c8\u9ad8(clientHeight): ${e.readerViewport.clientHeight}px\n`;g+=`  - \u30b3\u30f3\u30c6\u30f3\u30c4\u5168\u4f53\u5e45(scrollWidth): ${e.readerViewport.scrollWidth}px\n`;g=g+"- **\u30b9\u30af\u30ed\u30fc\u30eb\u72b6\u614b**:\n"+`  - scrollLeft: ${e.readerViewport.scrollLeft}px\n`;g+=`  - \u9032\u6357\u5272\u5408(bookmarkProgress): ${(100*f.bookmarkProgress).toFixed(1)}%\n`;return g+`  - \u30da\u30fc\u30b8\u6570: \u73fe\u5728 ${a} / ${b} \u30da\u30fc\u30b8\n\n`}
function ib(a){const b=a.marginLeft||"0px",c=a.marginRight||"0px";a="### \ud83d\udcd0 \u30ab\u30e9\u30e0\uff06\u30d3\u30e5\u30fc\u30dd\u30fc\u30c8\u8a08\u7b97\u691c\u8a3c\n- **\u30b3\u30f3\u30c6\u30f3\u30c4\u914d\u7f6e\u30b9\u30bf\u30a4\u30eb**:\n"+`  - column-width: ${a.columnWidth||"auto"}\n`+`  - column-gap: ${a.columnGap||"normal"}\n`;a=a+`  - margin-left: ${b}\n`+`  - margin-right: ${c}\n`;return a+="\n"}
function jb(a){var b=q.locator.resolve(r).readerViewport.clientWidth;const c=parseFloat(a.columnWidth||"auto")||0;var d=parseFloat(a.marginLeft||"0px")||0;const f=parseFloat(a.marginRight||"0px")||0;d=(a=768>window.innerWidth)?b-d-f:b/2-d-f;b=Math.abs(c-d);a="- **\u30ab\u30e9\u30e0\u4ed5\u69d8\u30c1\u30a7\u30c3\u30af**:\n"+`  - \u30c7\u30d0\u30a4\u30b9\u74b0\u5883: ${a?"\u30e2\u30d0\u30a4\u30eb (1\u6bb5\u7d44\u307f)":"PC (\u898b\u958b\u304d2\u6bb5\u7d44\u307f)"}\n`+`  - \u7406\u8ad6\u4e0a\u306e\u7406\u60f3\u30ab\u30e9\u30e0\u5e45: ${d.toFixed(1)}px (\u8a08\u7b97\u5f0f: ${a?
"W - margins":"W/2 - margins"})\n`;a+=`  - \u5b9f\u969b\u306e\u30ab\u30e9\u30e0\u5e45: ${c.toFixed(1)}px\n`;a=2<b?a+`  - \u26a0\ufe0f **\u8b66\u544a**: \u5b9f\u969b\u306e\u30ab\u30e9\u30e0\u5e45\u304c\u7406\u60f3\u306e\u5e45\u3068 ${b.toFixed(1)}px \u30ba\u30ec\u3066\u3044\u307e\u3059\u3002\u6539\u6bb5\u305a\u308c\u306e\u539f\u56e0\u3068\u306a\u308a\u307e\u3059\u3002\n`:a+"  - \u2705 **\u6b63\u5e38**: \u30ab\u30e9\u30e0\u5e45\u306f\u30ec\u30a4\u30a2\u30a6\u30c8\u8a2d\u8a08\u901a\u308a\u3067\u3059\u3002\n";
return a+"\n"}
function kb(a,b){var c=q.locator.resolve(r);let d="### \ud83d\udcd0 \u7e26\u65b9\u5411\u30ec\u30a4\u30a2\u30a6\u30c8\u914d\u7f6e\n";var f=document.querySelector(".reader-header"),e=document.querySelector(".reader-footer");f&&e&&(f=f.getBoundingClientRect(),e=e.getBoundingClientRect(),c=c.readerContent.getBoundingClientRect(),d+=`- **\u30d8\u30c3\u30c0\u30fc Y\u5ea7\u6a19\u7bc4\u56f2**: ${f.top.toFixed(1)}px \u301c ${f.bottom.toFixed(1)}px (\u9ad8\u3055: ${f.height.toFixed(1)}px)\n`,d+=`- **\u30d5\u30c3\u30bf\u30fc Y\u5ea7\u6a19\u7bc4\u56f2**: ${e.top.toFixed(1)}px \u301c ${e.bottom.toFixed(1)}px (\u9ad8\u3055: ${e.height.toFixed(1)}px)\n`,
d+=`- **\u30d3\u30e5\u30fc\u30dd\u30fc\u30c8\u9ad8**: ${a.height.toFixed(1)}px\n`,d+=`- **\u30b3\u30f3\u30c6\u30f3\u30c4 Y\u5ea7\u6a19\u7bc4\u56f2**: ${c.top.toFixed(1)}px \u301c ${c.bottom.toFixed(1)}px (\u9ad8\u3055: ${c.height.toFixed(1)}px)\n`,d+=`  - margin-top: ${b.marginTop}\n`,d+=`  - margin-bottom: ${b.marginBottom}\n`,d+=`  - margin-left: ${b.marginLeft}\n`,d+=`  - margin-right: ${b.marginRight}\n`,a=c.bottom>e.top,d+=`  - \u30d8\u30c3\u30c0\u30fc\u3068\u306e\u91cd\u8907: ${c.top<f.bottom?
`\u26a0\ufe0f \u3042\u308a (\u91cd\u8907\u9ad8: ${(f.bottom-c.top).toFixed(1)}px)`:"\u2705 \u306a\u3057"}\n`,d+=`  - \u30d5\u30c3\u30bf\u30fc\u3068\u306e\u91cd\u8907: ${a?`\u26a0\ufe0f \u3042\u308a (\u91cd\u8907\u9ad8: ${(c.bottom-e.top).toFixed(1)}px)`:"\u2705 \u306a\u3057"}\n`,d+=`  - \u30d5\u30c3\u30bf\u30fc\u3068\u306e\u9593\u306e\u4f59\u767d: ${(e.top-c.bottom).toFixed(1)}px\n\n`);return d}
async function lb(a,b,c){for(let d=0;d<a.length;d+=20){const f=a.slice(d,d+20);f.forEach((e,g)=>{c(e,d+g)});b(Math.round((d+f.length)/a.length*100));await new Promise(e=>{"function"===typeof requestAnimationFrame?requestAnimationFrame(()=>{setTimeout(e,0)}):setTimeout(e,0)})}}
async function mb(a,b,c){let d=`### \ud83d\udccf \u53ef\u8996\u8981\u7d20\u306e\u5883\u754c\u5ea7\u6a19\u5206\u5e03 (Y: ${a.top.toFixed(1)}px)\n`,f=0;await lb(b,e=>{c(`\u30ec\u30a4\u30a2\u30a6\u30c8\u5ea7\u6a19\u8a3a\u65ad\u4e2d... ${e}%`)},(e,g)=>{if(!e.classList.contains("empty-line")&&!e.classList.contains("page-break")){var h=e.getBoundingClientRect(),l=h.left-a.left,p=h.right-a.left;if(h.right>=a.left-5&&h.left<=a.right+5){f++;const n=p>a.width+1;d+=`- **\u6bb5\u843d ${g+1} (${e.tagName.toLowerCase()})**: X\u7bc4\u56f2: ${l.toFixed(1)}px \u301c ${p.toFixed(1)}px (\u5e45: ${h.width.toFixed(1)}px) \u300c${e.textContent.trim().substring(0,
15)}...\u300d\n`;-1>l&&(d+=`  - \u26a0\ufe0f **\u306f\u307f\u51fa\u3057**: \u5de6\u5883\u754c\u3092 ${(-l).toFixed(1)}px \u8d85\u904e\u3057\u3066\u3044\u307e\u3059 (\u6b21\u306e\u30da\u30fc\u30b8\u306b\u56de\u308a\u8fbc\u3093\u3067\u3044\u308b\u304b\u3001\u898b\u5207\u308c\u3066\u3044\u307e\u3059)\n`);n&&(d+=`  - \u26a0\ufe0f **\u306f\u307f\u51fa\u3057**: \u53f3\u5883\u754c\u3092 ${(p-a.width).toFixed(1)}px \u8d85\u904e\u3057\u3066\u3044\u307e\u3059 (\u524d\u306e\u30da\u30fc\u30b8\u304b\u3089\u56de\u308a\u8fbc\u3093\u3067\u3044\u308b\u304b\u3001\u898b\u5207\u308c\u3066\u3044\u307e\u3059)\n`)}}});
0===f&&(d+="- (\u53ef\u8996\u6bb5\u843d\u306f\u691c\u51fa\u3055\u308c\u307e\u305b\u3093\u3067\u3057\u305f)\n");return d+="\n"}
async function nb(a,b,c,d){var f=q.locator.resolve(C);const e=q.locator.resolve(r);var g=c-1;g="rtl"===f.direction?-(g*e.readerViewport.clientWidth):g*e.readerViewport.clientWidth;f=Math.abs(e.readerViewport.scrollLeft-g);g="### \ud83d\udcd0 \u30a2\u30e9\u30a4\u30e1\u30f3\u30c8\u691c\u8a3c\n"+`- **\u73fe\u5728\u306e\u30da\u30fc\u30b8\u306e\u7406\u60f3\u30b9\u30af\u30ed\u30fc\u30eb\u4f4d\u7f6e**: ${g}px\n`+`- **\u5b9f\u969b\u306e\u30b9\u30af\u30ed\u30fc\u30eb\u4f4d\u7f6e\u3068\u306e\u30ba\u30ec**: ${f}px\n`;
g=(5<f?g+`  - \u26a0\ufe0f **\u8b66\u544a**: \u30b9\u30af\u30ed\u30fc\u30eb\u4f4d\u7f6e\u304c\u30da\u30fc\u30b8\u306e\u533a\u5207\u308a\u304b\u3089 ${f}px \u30ba\u30ec\u3066\u3044\u307e\u3059\u3002\u6587\u5b57\u304c\u898b\u5207\u308c\u308b\u539f\u56e0\u306b\u306a\u3063\u3066\u3044\u308b\u53ef\u80fd\u6027\u304c\u3042\u308a\u307e\u3059\u3002\n`:g+"  - \u2705 **\u6b63\u5e38**: \u30b9\u30af\u30ed\u30fc\u30eb\u4f4d\u7f6e\u306f\u6b63\u3057\u304f\u914d\u7f6e\u3055\u308c\u3066\u3044\u307e\u3059\u3002\n")+
"\n";g+="### \u26a0\ufe0f \u5883\u754c\u7dda\u4e0a\u3067\u306e\u30c6\u30ad\u30b9\u30c8\u898b\u5207\u308c\u691c\u51fa\n";const h=a.left,l=a.right;let p=0,n=0,v=0,t="";await lb(b,u=>{d(`\u5883\u754c\u898b\u5207\u308c\u8a3a\u65ad\u4e2d... ${u}%`)},(u,B)=>{if(!u.classList.contains("empty-line")&&!u.classList.contains("page-break")){var w=u.getBoundingClientRect();if(w.right>=a.left-50&&w.left<=a.right+50){var E=w.bottom>a.bottom+2;if(w.top<a.top-2||E)t+=`- **\u7e26\u65b9\u5411\u306f\u307f\u51fa\u3057**: \u6bb5\u843d ${B+
1} (${u.tagName.toLowerCase()}) \u304c\u30d3\u30e5\u30fc\u30dd\u30fc\u30c8\u306e\u4e0a\u4e0b\u5883\u754c\u304b\u3089\u306f\u307f\u51fa\u3057\u3066\u3044\u307e\u3059\u3002\n`,t+=`  - \u8981\u7d20 of Y\u5ea7\u6a19\u7bc4\u56f2: ${w.top.toFixed(1)}px \u301c ${w.bottom.toFixed(1)}px (\u30d3\u30e5\u30fc\u30dd\u30fc\u30c8: ${a.top.toFixed(1)}px \u301c ${a.bottom.toFixed(1)}px)\n`,t+=`  - \u30c6\u30ad\u30b9\u30c8\u629c\u7c8b: \u300c${u.textContent.substring(0,30)}...\u300d\n`,v++;E=window.getComputedStyle(u);
E=`[font-size: ${E.fontSize}, line-height: ${E.lineHeight}, font-family: ${E.fontFamily}]`;var D=1===c&&1>Math.abs(e.readerViewport.scrollLeft);if(w.left<h&&w.right>h&&!D&&(D=ob(u,h))){p++;var qa=D.context,Aa=D.rect.left-a.left,Ba=D.rect.right-a.left;const Kb=a.left-D.rect.left;t+=`- **\u5de6\u5883\u754c\u7dda\u3068\u306e\u4ea4\u5dee**: \u6bb5\u843d ${B+1} (${u.tagName.toLowerCase()}) \u304c\u5de6\u30da\u30fc\u30b8\u5883\u754c (X: ${h.toFixed(1)}px) \u3092\u307e\u305f\u3044\u3067\u3044\u307e\u3059\u3002 ${E}\n`;
t+=`  - \u5883\u754c\u4e0a\u306e\u6587\u5b57: \u300c${qa.before}**[${D.char}]**${qa.after}\u300d\n`;t+=`  - \u6587\u5b57\u5ea7\u6a19 (viewport\u57fa\u6e96): left: ${Aa.toFixed(1)}px, right: ${Ba.toFixed(1)}px (\u5e45: ${D.rect.width.toFixed(1)}px)\n`;t+=`  - \u5de6\u5883\u754c\u306f\u307f\u51fa\u3057\u91cf (overrun): **${Kb.toFixed(1)}px**\n`}w.left<l&&w.right>l&&(w=ob(u,l))&&(n++,D=w.context,qa=w.rect.left-a.left,Aa=w.rect.right-a.left,Ba=w.rect.right-a.right,t+=`- **\u53f3\u5883\u754c\u7dda\u3068\u306e\u4ea4\u5dee**: \u6bb5\u843d ${B+
1} (${u.tagName.toLowerCase()}) \u304c\u53f3\u30da\u30fc\u30b8\u5883\u754c (X: ${l.toFixed(1)}px) \u3092\u307e\u305f\u3044\u3067\u3044\u307e\u3059\u3002 ${E}\n`,t+=`  - \u5883\u754c\u4e0a\u306e\u6587\u5b57: \u300c${D.before}**[${w.char}]**${D.after}\u300d\n`,t+=`  - \u6587\u5b57\u5ea7\u6a19 (viewport\u57fa\u6e96): left: ${qa.toFixed(1)}px, right: ${Aa.toFixed(1)}px (\u5e45: ${w.rect.width.toFixed(1)}px)\n`,t+=`  - \u53f3\u5883\u754c\u306f\u307f\u51fa\u3057\u91cf (overrun): **${Ba.toFixed(1)}px**\n`)}}});
0===p&&0===n&&0===v?g+="- \u2705 \u5883\u754c\u7dda\u4e0a\u306e\u898b\u5207\u308c\u3084\u306f\u307f\u51fa\u3057\u306f\u691c\u51fa\u3055\u308c\u307e\u305b\u3093\u3067\u3057\u305f\u3002\n":(g+=`- \u691c\u51fa\u30b5\u30de\u30ea\u30fc: \u5de6\u5883\u754c\u307e\u305f\u304e ${p}\u4ef6, \u53f3\u5883\u754c\u307e\u305f\u304e ${n}\u4ef6, \u4e0a\u4e0b\u306f\u307f\u51fa\u3057 ${v}\u4ef6\n\n`,g+=t);return g}
async function pb(){const a=q.locator.resolve(r);if(!a.readerViewport||!a.readerContent)return Promise.resolve("\u30a8\u30e9\u30fc: \u30d3\u30e5\u30fc\u30a2\u30fc\u304c\u521d\u671f\u5316\u3055\u308c\u3066\u3044\u307e\u305b\u3093\u3002");const b=l=>{a.diagnoseReportOutput&&(a.diagnoseReportOutput.textContent=l)};b("\u8a3a\u65ad\u4e2d... \u74b0\u5883\u60c5\u5831\u3092\u53d6\u5f97\u3057\u3066\u3044\u307e\u3059\u3002");const {currentPage:c,C:d}=gb(a.readerViewport);var f=window.getComputedStyle(a.readerContent);
const e=a.readerViewport.getBoundingClientRect(),g=Array.from(a.readerContent.children);let h;h=""+hb(c,d);h+=ib(f);h+=jb(f);h+=kb(e,f);h+=await mb(e,g,b);h+=await nb(e,g,c,b);(f=q.locator.resolve(T))&&f.lastRepairMetrics&&(f=f.lastRepairMetrics,h=h+"### \ud83d\udee0\ufe0f \u30ec\u30a4\u30a2\u30a6\u30c8\u81ea\u5df1\u4fee\u5fa9\u30b9\u30c6\u30fc\u30bf\u30b9\n"+`- **\u4fee\u5fa9\u72b6\u614b**: ${30<=f.passesCount?"\u26a0\ufe0f \u30eb\u30fc\u30d7\u4e0a\u9650\u5230\u9054 (\u672a\u53ce\u675f)":"\u2705 \u53ce\u675f\u5b8c\u4e86 (\u6b63\u5e38)"}\n`,
h+=`- **\u5b9f\u884c\u30d1\u30b9\u6570**: ${f.passesCount}\u56de\n`,h+=`- **\u633f\u5165\u3055\u308c\u305f\u6539\u30da\u30fc\u30b8\u6570**: ${f.insertedCount}\u500b\n`,h+=`- **\u51e6\u7406\u6240\u8981\u6642\u9593**: ${f.durationMs.toFixed(1)}ms\n\n`);b(h);return h}
function ob(a,b){var c=[];a=document.createTreeWalker(a,NodeFilter.SHOW_TEXT,null);for(var d;d=a.nextNode();)c.push(d);for(const f of c)for(c=f.textContent,a=0;a<c.length;a++){d=document.createRange();try{d.setStart(f,a),d.setEnd(f,a+1)}catch(e){continue}d=d.getBoundingClientRect();if(d.left<b-.5&&d.right>b+.5)return{char:c[a],rect:d,context:{before:c.substring(Math.max(0,a-10),a),after:c.substring(a+1,Math.min(c.length,a+11))}}}return null};function qb(a){const b=rb(a.g.readerContent,a.g.readerViewport);if(b){var c=Array.from(b.parent.children);for(var d=0;d<c.length;d++){var f=c[d];f.classList.contains("page-break")&&(f.style.width="",f.style.height="",f.style.removeProperty("margin-block-end"))}for(d=0;d<c.length;d++)if(f=c[d],f.classList.contains("page-break")){a:{var e=c;var g=d;for(--g;0<=g;g--){var h=e[g];if(!h.classList.contains("page-break")&&!h.classList.contains("empty-line")&&"none"!==window.getComputedStyle(h).display){e=
h;break a}}e=null}g=e;e=b.columnWidth;g&&(e="rtl"===a.h.direction,g=g.getBoundingClientRect(),h=b.parent.getBoundingClientRect(),e=e?h.right-g.left-5:g.right-h.left-5,g=Math.max(1,Math.round(a.g.readerViewport.clientWidth/b.step)),e=(Math.floor(Math.floor(e/b.step)/g)+1)*g*b.step-e-b.columnGap);0>=e&&(e=b.columnWidth);f.style.width=`${e}px`;f.style.height="100%";f.style.setProperty("margin-block-end",`${b.columnGap}px`)}}}
function sb(a,b,c){const d=[];1<a&&d.push((a-1)*c);a<b&&d.push(a*c);return d}
function tb(a,b,c,d){var f=a.g.readerContent;if(!f)return!1;f=Array.from(f.children);for(const B of b){if(b=!(0>=B))a:{b=a;var e=B,g=f,h=c,l=d;b.paragraphBoundsCache&&0!==b.paragraphBoundsCache.length||b.cacheParagraphBounds();let w=!0;var p=0;for(const E of g)if(E.classList.contains("page-break"))w=!0;else if(!E.classList.contains("empty-line"))if(g=w,w=!1,g)p++;else{b:{g=E;var n=e,v=h,t=l,u=b.paragraphBoundsCache[p];p+=1;if(u&&u.element===g){if(v=u.docRight,u.docLeft<n&&v>n&&ub(g,n,t)){g={B:!0,
A:p};break b}}else{u=g.getBoundingClientRect();const D=u.right+v;if(u.left+v<n&&D>n&&ub(g,n,t)){g={B:!0,A:p};break b}}g={B:!1,A:p}}p=g.A;if(g.B){b=!0;break a}}b=!1}if(b)return!0}return!1}
class T{constructor(){this.g=q.locator.resolve(r);this.h=q.locator.resolve(C);this.s=new DOMParser;this.lastRepairMetrics={passesCount:0,insertedCount:0,durationMs:0};this.isRepairing=!1;this.o=0;this.paragraphBoundsCache=[];const a=q.locator.resolve(k);a&&a.subscribe("system:layout-repair-requested",()=>{this.adjustPageBreaksForOverrun()})}render(a){if(this.g.readerContent&&(this.paragraphBoundsCache=[],a=this.s.parseFromString(a,"text/html").body)){var b=q.locator.resolve(R);b&&b.sanitizeDOM(a);
for(this.g.readerContent.innerHTML="";a.firstChild;)this.g.readerContent.appendChild(a.firstChild)}}restoreScrollPosition(a,b=!1){if(this.g.readerViewport){var c=this.g.readerViewport.scrollWidth-this.g.readerViewport.clientWidth;a="rtl"===this.h.direction?-(a*c):a*c;b?this.g.readerViewport.scrollTo({left:a,behavior:"smooth"}):this.g.readerViewport.scrollLeft=a}}scrollToPage(a){if(!this.g.readerViewport)return Promise.resolve();a=(a-1)*this.g.readerViewport.clientWidth;this.g.readerViewport.scrollTo({left:"rtl"===
this.h.direction?-a:a,behavior:"smooth"});return new Promise(b=>{setTimeout(b,400)})}handleResize(a){if(!this.g.readerContent||!this.g.readerViewport)return Promise.resolve();this.paragraphBoundsCache=[];this.g.readerContent.style.width="auto";return new Promise(b=>{setTimeout(()=>{this.g.readerContent.style.width="max-content";var c=q.locator.resolve(k);c&&c.publish("system:layout-check-requested",{scope:"all"});c=Math.abs(this.g.readerViewport.scrollWidth-this.g.readerViewport.clientWidth);this.g.readerViewport.scrollLeft=
"rtl"===this.h.direction?-(a*c):a*c;b()},100)})}async adjustPageBreaksForOverrun(){if(this.g.readerContent&&this.g.readerViewport){var a=++this.o;this.isRepairing=!0;try{const f=this.g.readerContent,e=this.g.readerViewport;f.querySelectorAll(".dynamic-page-break").forEach(n=>n.remove());const g=performance.now(),h=Array.from(f.children).filter(n=>"none"!==window.getComputedStyle(n).display);let l=0,p=0;for(;l<h.length;){if(this.o!==a)return;vb(h[l],e)&&qb(this);l++;p++;600<=p&&(p=0,await new Promise(n=>
setTimeout(n,0)))}if(this.o===a){var b=f.querySelectorAll(".dynamic-page-break").length,c=performance.now()-g;this.lastRepairMetrics={passesCount:1,insertedCount:b,durationMs:parseFloat(c.toFixed(1))};this.g.cachedScrollWidth=null;this.g.cachedClientWidth=null;window.__DEBUG_PERFORMANCE__&&console.log(`[Layout Repair] adjustPageBreaksForOverrun completed in ${c.toFixed(1)}ms. passesCount: 1, insertedCount: ${b}`);this.cacheParagraphBounds();try{const n=q.locator.resolve(G);n&&this.restoreScrollPosition(n.bookmarkProgress,
!1)}catch(n){}var d=q.locator.resolve(k);d&&d.publish("system:layout-repaired",this.lastRepairMetrics)}}finally{this.isRepairing=!1}}}cacheParagraphBounds(){qb(this);this.paragraphBoundsCache=[];var a=this.g.readerContent,b=this.g.readerViewport;if(a&&b){a=Array.from(a.children);b=Math.abs(b.scrollLeft);for(const c of a)c.classList.contains("empty-line")||c.classList.contains("page-break")||(a=c.getBoundingClientRect(),this.paragraphBoundsCache.push({element:c,docLeft:a.left+b,docRight:a.right+b}))}}hasOverrunNearCurrentPage(){if(!this.g.readerContent||
!this.g.readerViewport)return!1;var a=performance.now(),b=this.g.readerViewport,c=b.clientWidth;if(!c||0>=c)return!1;const d=Math.round(b.scrollWidth/c)||0;if(1>=d)return!1;const f=Math.abs(b.scrollLeft);c=sb(Math.round(f/c)+1,d,c);if(0===c.length)return!1;Array.from(this.g.readerContent.children).filter(e=>e.classList.contains("empty-line")?!1:"none"!==window.getComputedStyle(e).display);b=tb(this,c,f,b.scrollLeft);a=performance.now()-a;window.__DEBUG_PERFORMANCE__&&console.log(`[Layout Check] hasOverrunNearCurrentPage completed in ${a.toFixed(1)}ms. Result: ${b}`);
return b}}
function vb(a,b){if(a.classList.contains("empty-line")||a.classList.contains("page-break"))return!1;var c=b.clientWidth;if(!c||0>=c)return!1;b=b.scrollLeft;var d=Math.abs(b),f=a.getBoundingClientRect();const e=f.left+d;d=f.right+d;f=[];if(isFinite(e)&&isFinite(d)&&e<d){let h=Math.ceil(e/c)*c,l=0;for(;h<d&&50>l;)0<h&&f.push(h),h+=c,l++}for(var g of f)if(!(g<=e||g>=d)){a:{c=a.previousElementSibling;for(f=0;c&&10>f;){if(c.classList.contains("page-break")){c=!0;break a}if(!c.classList.contains("empty-line"))break;c=
c.previousElementSibling;f++}c=!1}if(c)break;if(ub(a,g,b))return g=document.createElement("div"),g.className="page-break dynamic-page-break",a.parentNode.insertBefore(g,a),!0}return!1}function wb(a,b){if(3===a.nodeType)a.textContent&&0<a.textContent.trim().length&&b.push(a);else{a=a.firstChild;for(var c=0;a&&1E3>c;)wb(a,b),a=a.nextSibling,c++}}
function ub(a,b,c){var d=[];wb(a,d);a=Math.abs(c);c="rtl"===q.locator.resolve(C).direction;for(const p of d){a:{d=p;var f=b;const n=d.textContent;var e;if(!(e=!n)){b:{var g=d;e=f;var h=document.createRange();try{h.selectNodeContents(g)}catch(v){e=!1;break b}g=h.getBoundingClientRect();h=g.right+a;e=g.left+a<e&&h>e}e=!e}if(e)d=null;else{e=0;h=n.length-1;for(g=0;e<=h&&100>g;){g++;const v=Math.floor((e+h)/2);var l=document.createRange();try{l.setStart(d,v),l.setEnd(d,v+1)}catch(B){break}l=l.getBoundingClientRect();
const t=l.left+a,u=l.right+a;if(t<f-.5&&u>f+.5){d={char:n[v],rect:l,context:{before:n.substring(Math.max(0,v-10),v),after:n.substring(v+1,Math.min(n.length,v+11))}};break a}h=c?t>=f-.5?{low:v+1,high:h}:{low:e,high:v-1}:t>=f-.5?{low:e,high:v-1}:{low:v+1,high:h};e=h.low;h=h.high}d=null}}if(d)return d}return null}
function rb(a,b){if(!a||!b)return null;b=b.clientWidth;if(!b||0>=b)return null;var c=window.getComputedStyle(a);b=parseFloat(c.columnWidth);if(!b||isNaN(b))return null;c=parseFloat(c.columnGap);c=isNaN(c)?0:c;return{parent:a,columnWidth:b,columnGap:c,step:b+c}};function xb(a){a&&q.locator.resolve(H).loadBook(a.name,a.name,function(){return new Promise((b,c)=>{const d=new FileReader;d.onload=function(f){f=f.target.result;var e=new TextDecoder("utf-8",{fatal:!0});try{b(e.decode(f))}catch(g){e=new TextDecoder("shift-jis",{fatal:!1}),b(e.decode(f))}};d.onerror=function(){c(Error("File reading failed."))};d.readAsArrayBuffer(a)})}).then(b=>{M.execute(new za(b.id,b.content))}).catch(b=>{console.error("Failed to load dropped file:",b);alert("\u30d5\u30a1\u30a4\u30eb\u306e\u8aad\u307f\u8fbc\u307f\u306b\u5931\u6557\u3057\u307e\u3057\u305f: "+
b.message)})}
function yb(a){const b=wa.find(c=>c.id===a);b&&q.locator.resolve(H).loadBook(b.title,b.path,function(){return fetch(b.path).then(c=>c.arrayBuffer()).then(c=>{const d=new TextDecoder("utf-8",{fatal:!0});try{return d.decode(c)}catch(f){return console.warn("Shift_JIS decode failed (fatal=true), falling back to UTF-8 for predefined book",f),(new TextDecoder("shift-jis",{fatal:!1})).decode(c)}})}).then(c=>{M.execute(new za(c.id,c.content))}).catch(c=>{console.error("Failed to load predefined book:",c);
alert("\u63a8\u5968\u66f8\u7c4d\u306e\u8aad\u307f\u8fbc\u307f\u306b\u5931\u6557\u3057\u307e\u3057\u305f: "+c.message)})}let zb=0;
async function Ab(){const a=++zb,b=q.locator.resolve(A),c=q.locator.resolve(G),d=q.locator.resolve(r),f=q.locator.resolve(T);d.cachedScrollWidth=null;d.cachedClientWidth=null;var e="";e=q.locator.resolve(S);if("txt"===b.type)e=e.parseAozoraText(b.content).body;else{var g=e.parseAozoraHTML(b.content);e=g.body;b.title=g.title||b.title.replace(/\.(x?html)/,"")}if(g=wa.find(h=>h.title===b.title||b.title.includes(h.l.toString())))b.title=g.title,b.author=g.author||"";d.bookTitle.textContent=b.title;document.title=
`${b.title} - \u3086\u3046\u305e\u3089`;f.render(e);d.activeHeadingId=b.toc&&0<b.toc.length?b.toc[0].id:null;q.locator.resolve(fa).transitionTo("reader");e=q.locator.resolve(ha);g?(g="#/reader?book="+g.id,e.currentHash=g,window.location.hash=g):(g="#/reader?local="+encodeURIComponent(b.title),e.currentHash=g,window.location.hash=g);e=q.locator.resolve(y);c.bookmarkProgress=await e.load(b.title);zb===a&&(d.isReflowing=!0,window.__isReflowing__=!0,setTimeout(async()=>{if(zb===a)try{if(await f.adjustPageBreaksForOverrun(),
zb===a)try{Bb(),U(),yuzora.publisher.publish("document:rendered"),setTimeout(()=>{zb===a&&(d.isReflowing=!1,window.__isReflowing__=!1)},50)}catch(h){document.title="FATAL_ERROR: "+(h instanceof Error?h.message:String(h)),console.error("FATAL_ERROR: ",h),d.isReflowing=!1,window.__isReflowing__=!1}}catch(h){document.title="FATAL_ERROR: "+(h instanceof Error?h.message:String(h)),console.error("FATAL_ERROR: ",h),d.isReflowing=!1,window.__isReflowing__=!1}},100))}
function U(){const a=q.locator.resolve(r);var b=q.locator.resolve(G);if(a.readerViewport){var c=performance.now(),d=a.cachedScrollWidth,f=a.cachedClientWidth;if(null===d||null===f)d=a.readerViewport.scrollWidth,f=a.readerViewport.clientWidth,a.cachedScrollWidth=d,a.cachedClientWidth=f;var e=d,g=f,h=Math.abs(a.readerViewport.scrollLeft);d=e-g;b.bookmarkProgress=0>=d?0:h/d;var l=Math.min(100,Math.max(0,Math.round(100*b.bookmarkProgress)));null!==a.progressAnimationFrameId&&cancelAnimationFrame(a.progressAnimationFrameId);
a.progressAnimationFrameId=requestAnimationFrame(()=>{a.progressAnimationFrameId=null;a.progressBar&&(a.progressBar.style.width=`${l}%`);a.readingPercentage&&(a.readingPercentage.textContent=`${l}%`);const p=Math.round(e/g),n=Math.min(p,Math.max(1,Math.round(h/g)+1));a.readingIndex&&(a.readingIndex.textContent=`${n} / ${p} \u30da\u30fc\u30b8`)});b=performance.now()-c;window.__DEBUG_PERFORMANCE__&&1<b&&console.log(`[Progress Update] updateProgress logic took ${b.toFixed(2)}ms (DOM writes deferred via rAF)`)}}
function Bb(){const a=q.locator.resolve(G);q.locator.resolve(T).restoreScrollPosition(a.bookmarkProgress,!1)}async function Cb(){const a=q.locator.resolve(A),b=q.locator.resolve(G);a.title&&await b.save(a.title,b.bookmarkProgress)}
function V(){var a=q.locator.resolve(r);if(a.readerViewport){var b=a.cachedClientWidth,c=a.cachedScrollWidth;if(null===b||null===c)b=a.readerViewport.clientWidth,c=a.readerViewport.scrollWidth,a.cachedClientWidth=b,a.cachedScrollWidth=c;a=Math.round(Math.abs(a.readerViewport.scrollLeft)/b)+1;a<Math.round(c/b)&&M.execute(new J(a+1))}}
function W(){var a=q.locator.resolve(r);if(a.readerViewport){var b=a.cachedClientWidth;null===b&&(b=a.readerViewport.clientWidth,a.cachedClientWidth=b);a=Math.round(Math.abs(a.readerViewport.scrollLeft)/b)+1;1<a&&M.execute(new J(a-1))}}
function Db(a){const b=q.locator.resolve(r),c=q.locator.resolve(G),d=q.locator.resolve(T);let f=b.cachedClientWidth,e=b.cachedScrollWidth;if(null===f||null===e)f=b.readerViewport.clientWidth,e=b.readerViewport.scrollWidth,b.cachedClientWidth=f,b.cachedScrollWidth=e;const g=e,h=f,l=(a-1)*h,p=performance.now();b.isReflowing=!0;d.scrollToPage(a).then(()=>{b.isReflowing=!1;var n=performance.now()-p;window.__DEBUG_PERFORMANCE__&&console.log(`[Page Navigation] Scroll to page ${a} completed in ${n.toFixed(1)}ms`);
yuzora.publisher.publish("ui:page-changed",{page:a});n=g-h;c.bookmarkProgress=0<n?l/n:0;U();Cb()})}
function Eb(){const a=q.locator.resolve(r),b=q.locator.resolve(G),c=q.locator.resolve(T);if(!a.isReflowing){a.cachedScrollWidth=null;a.cachedClientWidth=null;a.isReflowing=!0;window.__isReflowing__=!0;var d=b.bookmarkProgress,f=()=>{yuzora.publisher.unsubscribe("system:layout-repaired",f);b.bookmarkProgress=d;U();setTimeout(()=>{a.isReflowing=!1;window.__isReflowing__=!1},50)};yuzora.publisher.subscribe("system:layout-repaired",f);c.handleResize(d)}}
async function Ma(){const a=q.locator.resolve(A),b=q.locator.resolve(G),c=q.locator.resolve(y);b.bookmarkProgress=await c.load(a.title);Bb();U()}document.addEventListener("DOMContentLoaded",()=>{yuzora.publisher.subscribe("document:loaded",()=>{Ab()});yuzora.publisher.subscribe("ui:navigate-page",a=>{Db(a.targetPage)})});function Ca(a,b){const c=q.locator.resolve(r),d=q.locator.resolve(C);if("theme"===a)document.body.className=`theme-${b}`;else if("font"===a)c.readerContent.className="reader-content",c.readerContent.classList.add(b,`direction-${d.direction}`,d.size,d.lh,d.spacing),Eb();else if("direction"===a)Da(),Eb();else if("size"===a||"lh"===a||"spacing"===a)c.readerContent.className="reader-content",c.readerContent.classList.add(d.font,`direction-${d.direction}`,d.size,d.lh,d.spacing),Eb();else if("headingPageBreakMode"===
a){if(a=document.getElementById("select-heading-break"))a.value=b;yuzora.publisher.publish("document:loaded")}}function Fb(){const a=q.locator.resolve(r);a.debugModal.classList.add("hidden");a.debugModalOverlay.classList.add("hidden");document.body.classList.remove("debug-active");Ha()}
function Gb(a){var b=q.locator.resolve(r);const c=q.locator.resolve(G);b=b.progressBarContainer.getBoundingClientRect();const d=b.width;c.bookmarkProgress=Math.max(0,Math.min(d,a-b.left))/d;a=q.locator.resolve(G);q.locator.resolve(T).restoreScrollPosition(a.bookmarkProgress,!0);U()}let Hb=[],Ib=[],Jb=null,Lb=null;function X(a,b,c){a&&(a.addEventListener(b,c,void 0),Hb.push({element:a,type:b,u:c,options:void 0}))}
function Y(a,b,c,d){a&&(d=void 0===d?void 0:d||void 0,a.addEventListener(b,c,d),Ib.push({element:a,type:b,u:c,options:d}))}
function Mb(){const a=q.locator.resolve(r),b=q.locator.resolve(fa),c=d=>{if(d){d.innerHTML="";for(let f=0;3>f;f++){const e=document.createElement("div");e.className="book-card-skeleton";e.innerHTML='\n                <div class="skeleton-title-vertical"></div>\n                <div class="skeleton-meta-horizontal"></div>\n            ';d.appendChild(e)}}};("undefined"!==typeof window&&window.requestAnimationFrame?window.requestAnimationFrame:d=>setTimeout(d,16))(()=>{setTimeout(()=>{"welcome"===b.currentSceneName&&
(c(a.developerBooksGrid),c(a.readerBooksGrid),setTimeout(()=>{"welcome"===b.currentSceneName&&(a.developerBooksGrid&&(a.developerBooksGrid.innerHTML="",wa.filter(d=>"developer"===d.i).forEach(d=>{const f=document.createElement("div");f.className="book-card fade-in";f.setAttribute("data-book-id",d.id);f.innerHTML=`
                            <div class="book-card-title">${d.j}</div>
                            <div class="book-card-author">${d.author}</div>
                        `;X(f,"click",()=>{window.location.hash="#/reader?book="+d.id});a.developerBooksGrid.appendChild(f)})),a.readerBooksGrid&&(a.readerBooksGrid.innerHTML="",wa.filter(d=>"reader"===d.i).forEach(d=>{const f=document.createElement("div");f.className="book-card fade-in";f.setAttribute("data-book-id",d.id);f.innerHTML=`
                            <div class="book-card-title">${d.j}</div>
                            <div class="book-card-author">${d.author}</div>
                        `;X(f,"click",()=>{window.location.hash="#/reader?book="+d.id});a.readerBooksGrid.appendChild(f)})))},600))},0)})}
function ka(){const a=q.locator.resolve(r);X(a.dropZone,"dragover",b=>{b.preventDefault();a.dropZone.classList.add("dragover")});X(a.dropZone,"dragleave",()=>{a.dropZone.classList.remove("dragover")});X(a.dropZone,"drop",b=>{b.preventDefault();a.dropZone.classList.remove("dragover");xb(b.dataTransfer.files[0])});X(a.fileInput,"change",b=>{xb(b.target.files[0])});Mb()}function la(){Hb.forEach(({element:a,type:b,u:c,options:d})=>{a.removeEventListener(b,c,void 0===d?void 0:d||void 0)});Hb=[]}
function na(){const a=q.locator.resolve(r),b=q.locator.resolve(C);Y(a.btnBack,"click",()=>{M.execute(new Ka)});let c;Y(a.readerViewport,"scroll",()=>{a.isReflowing||(window.__DEBUG_PERFORMANCE__&&(null===a.scrollStartTimestamp&&(a.scrollStartTimestamp=performance.now(),a.scrollEventCount=0),a.scrollEventCount++),q.locator.resolve(r).isReflowing||U(),clearTimeout(c),c=setTimeout(Nb,150))});Y(a.readerViewport,"click",Ob);Jb=Eb;window.addEventListener("resize",Jb);Lb=g=>{if(!a.readerScreen.classList.contains("hidden")){var h=
a.debugModal&&!a.debugModal.classList.contains("hidden");if(h){if("Tab"===g.key){var l=q.locator.resolve(r).debugModal.querySelectorAll('button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])');h=l[0];l=l[l.length-1];g.shiftKey?document.activeElement===h&&(l.focus(),g.preventDefault()):document.activeElement===l&&(h.focus(),g.preventDefault());return}if("Escape"===g.key){M.execute(new N(!1));return}}if("INPUT"!==g.target.tagName&&"TEXTAREA"!==g.target.tagName&&!g.target.isContentEditable){l=
q.locator.resolve(r);var p=!(!l.debugModal||l.debugModal.classList.contains("hidden"));if("d"===g.key||"D"===g.key)p?Fb():l.btnOpenDebug&&l.btnOpenDebug.click(),g.preventDefault();g.ctrlKey&&("z"===g.key?(g.preventDefault(),M.undo()):"y"===g.key&&(g.preventDefault(),M.redo()));p&&("1"===g.key?l.tabBtnMonitor&&l.tabBtnMonitor.click():"2"===g.key&&l.tabBtnDiagnose&&l.tabBtnDiagnose.click())}h||("rtl"===b.direction?("ArrowLeft"===g.key&&V(),"ArrowRight"===g.key&&W()):("ArrowLeft"===g.key&&W(),"ArrowRight"===
g.key&&V()),"ArrowUp"!==g.key&&"ArrowDown"!==g.key)||(Ob(g),g.preventDefault())}};document.addEventListener("keydown",Lb);let d=0,f=0;Y(a.readerViewport,"touchstart",g=>{1===g.touches.length&&(d=g.touches[0].clientX,f=g.touches[0].clientY)},{passive:!0});Y(a.readerViewport,"touchend",g=>{if(1===g.changedTouches.length){const h=g.changedTouches[0].clientX-d;g=g.changedTouches[0].clientY-f;50<Math.abs(h)&&Math.abs(h)>Math.abs(g)&&("rtl"===b.direction?0<h?V():W():0<h?W():V())}});let e=!1;Y(a.progressBarContainer,
"mousedown",g=>{e=!0;Gb(g.clientX)});Y(document,"mousemove",g=>{e&&Gb(g.clientX)});Y(document,"mouseup",()=>{e&&(e=!1,Cb())});Y(a.progressBarContainer,"touchstart",g=>{e=!0;Gb(g.touches[0].clientX)},{passive:!0});Y(a.progressBarContainer,"touchmove",g=>{e&&Gb(g.touches[0].clientX)},{passive:!0});Y(a.progressBarContainer,"touchend",()=>{e&&(e=!1,Cb())},{passive:!0});Pb();Qb();Rb();Sb();Tb();Ub();Vb()}
function oa(){Ib.forEach(({element:b,type:c,u:d,options:f})=>{b.removeEventListener(c,d,void 0===f?void 0:f||void 0)});Ib=[];Jb&&(window.removeEventListener("resize",Jb),Jb=null);Lb&&(document.removeEventListener("keydown",Lb),Lb=null);const a=q.locator.resolve(r);a.tocObserver&&(a.tocObserver.disconnect(),a.tocObserver=null)}
function Nb(){if(!q.locator.resolve(r).isReflowing){var a=q.locator.resolve(r);if(!a.isReflowing){var b=Math.abs(a.readerViewport.scrollLeft),c=a.cachedClientWidth;null===c&&(c=a.readerViewport.clientWidth,a.cachedClientWidth=c);var d=c;var f=Math.round(b/d);c=f*d;if(5<Math.abs(b-c))d=q.locator.resolve(C),a.isSnapping=!0,window.__DEBUG_PERFORMANCE__&&console.log(`[Scroll Snap] Starting snap to page ${f+1} (target scrollLeft: ${c})`),a.readerViewport.scrollTo({left:"rtl"===d.direction?-c:c,behavior:"smooth"});
else{f+=1;b=a.isSnapping||null!==a.scrollStartTimestamp;a.isSnapping&&(a.isSnapping=!1,window.__DEBUG_PERFORMANCE__&&console.log(`[Scroll Snap] Snap settled at page ${f}`));if(b){b=q.locator.resolve(G);let e=a.cachedScrollWidth;null===e&&(e=a.readerViewport.scrollWidth,a.cachedScrollWidth=e);d=e-d;b.bookmarkProgress=0<d?c/d:0;U();Cb();yuzora.publisher.publish("ui:page-changed",{page:f})}window.__DEBUG_PERFORMANCE__&&null!==a.scrollStartTimestamp&&(c=performance.now()-a.scrollStartTimestamp,d=a.scrollEventCount,
console.log(`[Scroll Performance] Scroll ended. Events: ${d}, Duration: ${c.toFixed(1)}ms, Freq: ${0<c?(d/(c/1E3)).toFixed(1):0} events/sec`),a.scrollStartTimestamp=null,a.scrollEventCount=0)}}}}
function Pb(){const a=q.locator.resolve(r);Y(a.drawerOverlay,"click",()=>{a.settingsDrawer.classList.contains("open")&&M.execute(new L("settings",!1));a.tocDrawer.classList.contains("open")&&M.execute(new L("toc",!1))});Y(a.btnTOC,"click",()=>{M.execute(new L("toc",!0))});Y(a.btnCloseTOC,"click",()=>{M.execute(new L("toc",!1))});Y(a.btnSettings,"click",()=>{M.execute(new L("settings",!0))});Y(a.btnCloseSettings,"click",()=>{M.execute(new L("settings",!1))})}
function Qb(){const a=q.locator.resolve(r),b=q.locator.resolve(C);Y(a.pageNavLeft,"click",c=>{c.stopPropagation();"rtl"===b.direction?V():W()});Y(a.pageNavRight,"click",c=>{c.stopPropagation();"rtl"===b.direction?W():V()});a.btnFirstPage&&Y(a.btnFirstPage,"click",()=>{M.execute(new J(1));M.execute(new L("settings",!1));M.execute(new L("toc",!1))})}
function Rb(){Z(".theme-selector button","theme",b=>{M.execute(new K("theme",b))});Z(".font-selector button","font",b=>{M.execute(new K("font",b))});Z(".direction-selector button","direction",b=>{M.execute(new K("direction",b))});Z(".size-selector button","size",b=>{M.execute(new K("size",b))});Z(".lh-selector button","lh",b=>{M.execute(new K("lh",b))});Z(".spacing-selector button","spacing",b=>{M.execute(new K("spacing",b))});const a=document.getElementById("select-heading-break");a&&Y(a,"change",
b=>{M.execute(new K("headingPageBreakMode",b.target.value))})}
function Sb(){const a=q.locator.resolve(r);a.btnClearBookmarks&&Y(a.btnClearBookmarks,"click",()=>{M.execute(new La("bookmarks"));alert("\u3059\u3079\u3066\u306e\u3057\u304a\u308a\u3092\u6d88\u53bb\u3057\u307e\u3057\u305f\u3002")});a.btnClearConfig&&Y(a.btnClearConfig,"click",()=>{M.execute(new La("config"));alert("\u8868\u793a\u8a2d\u5b9a\u3092\u521d\u671f\u5316\u3057\u307e\u3057\u305f\u3002")});a.btnClearAll&&Y(a.btnClearAll,"click",()=>{M.execute(new La("all"));alert("\u3059\u3079\u3066\u306e\u30ad\u30e3\u30c3\u30b7\u30e5\u30c7\u30fc\u30bf\u3092\u30ea\u30bb\u30c3\u30c8\u3057\u307e\u3057\u305f\u3002")})}
function Tb(){const a=q.locator.resolve(r);a.btnCloseDebug&&Y(a.btnCloseDebug,"click",()=>{M.execute(new N(!1))});a.debugModalOverlay&&Y(a.debugModalOverlay,"click",()=>{M.execute(new N(!1))});a.btnOpenDebug&&Y(a.btnOpenDebug,"click",()=>{M.execute(new N(!0))})}
function Ub(){const a=q.locator.resolve(r);a.btnDiagnoseLayout&&Y(a.btnDiagnoseLayout,"click",async()=>{await pb()});a.btnCopyDebugReport&&Y(a.btnCopyDebugReport,"click",()=>{a.diagnoseReportOutput&&(a.diagnoseReportOutput.select(),navigator.clipboard.writeText(a.diagnoseReportOutput.value).then(()=>alert("\u8a3a\u65ad\u30ec\u30dd\u30fc\u30c8\u3092\u30af\u30ea\u30c3\u30d7\u30dc\u30fc\u30c9\u306b\u30b3\u30d4\u30fc\u3057\u307e\u3057\u305f\u3002")).catch(()=>alert("\u30b3\u30d4\u30fc\u306b\u5931\u6557\u3057\u307e\u3057\u305f\u3002")))});
a.btnExportHistory&&Y(a.btnExportHistory,"click",()=>{if(a.debugHistoryJSON){const b=M.exportJSON();a.debugHistoryJSON.value=b;navigator.clipboard.writeText(b).then(()=>alert("\u64cd\u4f5c\u5c65\u6b74JSON\u3092\u30b3\u30d4\u30fc\u3057\u3001\u51fa\u529b\u30a8\u30ea\u30a2\u306b\u8868\u793a\u3057\u307e\u3057\u305f\u3002")).catch(()=>alert("\u30b3\u30d4\u30fc\u306b\u5931\u6557\u3057\u307e\u3057\u305f\u3002"))}});a.btnImportHistory&&Y(a.btnImportHistory,"click",()=>{if(a.debugHistoryJSON){const b=a.debugHistoryJSON.value.trim();
b?M.importJSON(b):alert("\u30a4\u30f3\u30dd\u30fc\u30c8\u7528\u306eJSON\u30c7\u30fc\u30bf\u3092\u30c6\u30ad\u30b9\u30c8\u30a8\u30ea\u30a2\u306b\u5165\u529b\u3057\u3066\u304f\u3060\u3055\u3044\u3002")}})}
function Vb(){const a=q.locator.resolve(r);a.tabBtnMonitor&&a.tabBtnDiagnose&&(Y(a.tabBtnMonitor,"click",()=>{a.tabBtnMonitor.classList.add("active");a.tabBtnDiagnose.classList.remove("active");a.tabContentMonitor.classList.remove("hidden");a.tabContentDiagnose.classList.add("hidden")}),Y(a.tabBtnDiagnose,"click",async()=>{a.tabBtnDiagnose.classList.add("active");a.tabBtnMonitor.classList.remove("active");a.tabContentDiagnose.classList.remove("hidden");a.tabContentMonitor.classList.add("hidden");
await pb()}))}function Z(a,b,c){const d=document.querySelectorAll(a);d.forEach(f=>{Y(f,"click",()=>{const e=f.getAttribute(`data-${b}`);d.forEach(g=>g.classList.remove("active"));f.classList.add("active");c(e)})})}async function Ea(){await q.locator.resolve(C).save()}async function Wb(){await q.locator.resolve(C).load()}function Da(){q.locator.resolve(C).apply()}
function F(a,b,c){document.querySelectorAll(a).forEach(d=>{d.getAttribute(`data-${b}`)===c?d.classList.add("active"):d.classList.remove("active")})}var Xb=null;
function Ja(){function a(){const f=document.createDocumentFragment(),e=Math.min(d+100,c.toc.length);for(;d<e;d++){const g=c.toc[d],h=document.createElement("div");h.className=`toc-item toc-item-level-${g.level}${g.id===b.activeHeadingId?" active":""}`;h.textContent=g.text;h.setAttribute("data-heading-id",g.id);Y(h,"click",()=>{Yb(g.id);const l=q.locator.resolve(r);l.tocDrawer.classList.remove("open");l.drawerOverlay.classList.remove("open");Ha()});f.appendChild(h)}b.tocList.appendChild(f);d<c.toc.length?
Xb=requestAnimationFrame(a):(Xb=null,Zb())}const b=q.locator.resolve(r),c=q.locator.resolve(A);Xb&&(cancelAnimationFrame(Xb),Xb=null);b.tocList.innerHTML="";if(c.toc&&0!==c.toc.length){var d=0;a()}else{const f=document.createElement("div");f.className="toc-item";f.style.cursor="default";f.style.color="var(--text-muted)";f.textContent="\u76ee\u6b21\u60c5\u5831\u306f\u3042\u308a\u307e\u305b\u3093\u3002";b.tocList.appendChild(f)}}var $b=new Set,ac=0;
function bc(){const a=q.locator.resolve(r),b=q.locator.resolve(A);$b.clear();a.tocObserver&&a.tocObserver.disconnect();a.tocObserver=new IntersectionObserver(c=>{c.forEach(d=>{d.isIntersecting?$b.add(d.target.id):$b.delete(d.target.id)});0<$b.size&&Date.now()>=ac&&(c=b.toc.find(d=>$b.has(d.id)))&&(a.activeHeadingId=c.id);a.activeHeadingId&&a.tocDrawer.classList.contains("open")&&Zb()},{root:a.readerViewport,threshold:.1});b.toc&&b.toc.forEach(c=>{(c=document.getElementById(c.id))&&a.tocObserver.observe(c)})}
function Zb(){const a=q.locator.resolve(r);a.tocList.querySelectorAll(".toc-item").forEach(b=>{b.getAttribute("data-heading-id")===a.activeHeadingId?b.classList.add("active"):b.classList.remove("active")})}
function Yb(a){const b=q.locator.resolve(r),c=q.locator.resolve(C),d=document.getElementById(a);if(d){b.activeHeadingId=a;ac=Date.now()+800;a=d.getBoundingClientRect();var f=b.readerViewport.getBoundingClientRect(),e=b.readerViewport.clientWidth,g=0;g="rtl"===c.direction?Math.floor((f.right-a.right+Math.abs(b.readerViewport.scrollLeft)+(f.right-a.left+Math.abs(b.readerViewport.scrollLeft)))/2/e):Math.floor((a.left-f.left+b.readerViewport.scrollLeft+(a.right-f.left+b.readerViewport.scrollLeft))/2/
e);M.execute(new J(g+1));setTimeout(()=>{d.setAttribute("tabindex","-1");d.focus({preventScroll:!0})},400)}}function Ia(){const a=q.locator.resolve(r);a.settingsDrawer.classList.contains("open")||a.tocDrawer.classList.contains("open")||(a.readerHeader.classList.add("hidden"),a.readerFooter&&a.readerFooter.classList.add("hidden"))}
function Ha(){const a=q.locator.resolve(r);a.readerHeader.classList.remove("hidden");a.readerFooter&&a.readerFooter.classList.remove("hidden");clearTimeout(a.headerTimeout);a.headerTimeout=setTimeout(()=>{Ia()},3E3)}function Ob(a){const b=q.locator.resolve(r);a&&"click"===a.type&&(a.target.closest("a")||a.target.closest("ruby")||a.target.closest("button"))||M.execute(new Ga(b.readerHeader.classList.contains("hidden")))};class q{constructor(){this.locator=q.locator;this.publisher=this.locator.resolve(k);this.config=null}async boot(){const a=new fa;a.register("initialize",new ia);a.register("welcome",new ja);a.register("reader",new ma);this.locator.register(fa,a);const b=new ha("welcome");this.locator.register(ha,b);this.locator.register(H,new H);var c=new T;this.locator.register(T,c);this.config=this.locator.resolve(C);q.locator.resolve(r).initializeDOMElements();const d=this.locator.resolve(r);b.register("/welcome",
()=>{a.transitionTo("welcome")});b.register("/reader",async e=>{if(e.book)yb(e.book);else if(e.local){const g=await this.locator.resolve(z).load();g&&g.name===e.local?this.locator.resolve(H).loadBook(g.name||"",g.name||"",function(){return Promise.resolve(g.content||"")}).then(h=>{const l=this.locator.resolve(A);l.title=h.id;l.content=h.content;l.type=h.id.endsWith(".html")||h.id.endsWith(".xhtml")?"html":"txt";this.publisher.publish("document:loaded",{fileName:h.id,fileContent:h.content})}).catch(h=>
{console.error("Failed to restore session via ResourceDirector:",h);b.navigate("/welcome")}):(alert("\u30ed\u30fc\u30ab\u30eb\u30d5\u30a1\u30a4\u30eb\u306f\u518d\u30ed\u30fc\u30c9\u304c\u5fc5\u8981\u3067\u3059\u3002"),b.navigate("/welcome"))}else b.navigate("/welcome")});a.transitionTo("initialize");await Wb();Da();c=await this.locator.resolve(z).load();const f=window.location.hash;c&&c.name&&c.content&&(!f||"#"===f||"#/welcome"===f)&&(window.location.hash="#/reader?local="+encodeURIComponent(c.name));
b.listen();this.publisher.subscribe("document:rendered",()=>{Ha();bc()});this.publisher.subscribe("ui:toggle-debug-modal",e=>{e&&e.open?(e=q.locator.resolve(r),e.debugModal&&e.debugModalOverlay&&(e.debugModal.classList.remove("hidden"),e.debugModalOverlay.classList.remove("hidden"),document.body.classList.add("debug-active"),M.updateDebugMonitor())):Fb()});this.publisher.subscribe("system:history-updated",e=>{d.debugHistoryJSON&&e&&e.history&&(d.debugHistoryJSON.value=JSON.stringify(e.history,null,
2))});this.publisher.subscribe("ui:page-changed",()=>{this.locator.resolve(T).isRepairing||setTimeout(()=>{this.publisher.publish("system:layout-check-requested",{scope:"current"})},0)});this.publisher.subscribe("system:layout-check-requested",e=>{const g=this.locator.resolve(T);e&&"current"===e.scope?g.hasOverrunNearCurrentPage()&&setTimeout(()=>{this.publisher.publish("system:layout-repair-requested")},0):setTimeout(()=>{this.publisher.publish("system:layout-repair-requested")},0)})}parseAozoraText(a){return this.locator.resolve(S).parseAozoraText(a)}parseAozoraHTML(a){return this.locator.resolve(S).parseAozoraHTML(a)}formatAozoraMarkup(a){return this.locator.resolve(S).formatAozoraMarkup(a)}async runLayoutDiagnosis(){return await pb()}getCurrentTOC(){return this.locator.resolve(A).toc}get CommandManager(){return this.locator.resolve(O)}get BookModel(){return A}get ConfigModel(){return C}get BookmarkModel(){return G}get LoadBookCommand(){return za}get NavigatePageCommand(){return J}get UpdateConfigCommand(){return K}get SyncBookmarkCommand(){return Fa}get VerticalRenderer(){return T}get ViewContext(){return r}get AozoraTokenizer(){return cb}get AozoraParser(){return S}get AozoraSemanticAnalyzer(){return eb}get AozoraEvaluator(){return R}get ASTNode(){return P}}
q.locator=m;const cc=new q;q.locator.register(q,cc);q.locator.register(cb,new cb);q.locator.register(eb,new eb);q.locator.register(R,new R);q.locator.register(S,new S);window.yuzora=cc;window.Yuzora=cc;document.addEventListener("DOMContentLoaded",()=>{cc.boot()});
