class aa{constructor(){this.g=new Map}register(a,b){this.g.set(a,b)}resolve(a){if(!this.g.has(a))throw Error(`Class ${a.name||a} is not registered in Locator.`);const b=this.g.get(a);if(!b)throw Error(`Class ${a.name||a} instance is null or undefined.`);return b}locate(a){if(!this.g.has(a))try{this.g.set(a,new a)}catch(c){throw Error(`Failed to auto-instantiate Class ${a.name||a} in Locator: ${c instanceof Error?c.message:String(c)}`);}const b=this.g.get(a);if(!b)throw Error(`Class ${a.name||a} instance is null or undefined.`);
return b}};class ba{constructor(a,b=null){this.type=a;this.detail=b;this.target=null}}
class ca{constructor(){this.g={}}addEventListener(a,b){this.g[a]||(this.g[a]=[]);this.g[a].push(b)}removeEventListener(a,b){this.g[a]&&(this.g[a]=this.g[a].filter(c=>c!==b))}dispatchEvent(a){var b=a.type;if(window.__DEBUG_EVENT__){let c="";try{c=JSON.stringify(a.detail)}catch(d){c=String(a.detail)}console.log(`[Event Audit] Dispatched event "${b}" (Payload: ${c}) to ${this.g[b]?this.g[b].length:0} listener(s)`)}if(this.g[b]){a.target=this;b=[...this.g[b]];for(const c of b)c(a)}}scoped(a){return new da(this,
a)}}class da{constructor(a,b){this.h=a;this.g=b}addEventListener(a,b){this.h.addEventListener(a.startsWith(this.g+":")?a:`${this.g}:${a}`,b)}removeEventListener(a,b){this.h.removeEventListener(a.startsWith(this.g+":")?a:`${this.g}:${a}`,b)}dispatchEvent(a){a.type.startsWith(this.g+":")||(a.type=`${this.g}:${a.type}`);this.h.dispatchEvent(a)}scoped(a){return new da(this.h,`${this.g}:${a}`)}}window.ScopedEventTarget=da;class h{constructor(a){this.h=a;this.g=new Map}subscribe(a,b){let c=this.g.get(a);c||(c=new Map,this.g.set(a,c));if(!c.has(b)){var d=e=>{b(e.detail)};c.set(b,d);this.h.addEventListener(a,d)}}unsubscribe(a,b){const c=this.g.get(a);if(c){var d=c.get(b);d&&(this.h.removeEventListener(a,d),c.delete(b));0===c.size&&this.g.delete(a)}}publish(a,b){this.h.dispatchEvent(new ba(a,b))}};class fa{enter(){throw Error("enter() must be implemented");}exit(){throw Error("exit() must be implemented");}}class ha{constructor(){this.g={};this.currentSceneName=null;this.isTransitioning=!1}register(a,b){this.g[a]=b}transitionTo(a,b){if(!this.isTransitioning){var c=this.g[a];if(!c)throw Error(`Scene not found: ${a}`);this.isTransitioning=!0;try{this.currentSceneName&&this.g[this.currentSceneName].exit(),c.enter(b),this.currentSceneName=a}finally{this.isTransitioning=!1}}}};class ia{constructor(a="welcome"){this.h=a;this.g=[];this.currentHash=null}register(a,b){this.g.push({pattern:new RegExp("^\\/?"+a.replace(/^\//,"").replace(/\//g,"\\/")+"(?:\\?(.*))?$"),B:b})}resolve(a){if(null!==this.currentHash&&a===this.currentHash)return!1;var b=a;b.startsWith("#")&&(b=b.slice(1));b.startsWith("/")&&(b=b.slice(1));b||(b=this.h);for(var c=0;c<this.g.length;c++){const e=this.g[c];var d=b.match(e.pattern);if(d){c=d[1]||"";b={};if(c)for(c=c.split("&"),d=0;d<c.length;d++){const f=
c[d].split("=");f[0]&&(b[decodeURIComponent(f[0])]=decodeURIComponent(f[1]||""))}this.currentHash=a;e.B(b);return!0}}return!1}listen(){window.addEventListener("hashchange",()=>{this.resolve(window.location.hash)});const a=window.location.hash;a&&"#"!==a&&"#/"!==a?this.resolve(a):this.navigate("#/"+this.h)}navigate(a){window.location.hash=a}};const m=new aa;window.locator=m;class ja extends fa{enter(){const a=q.locator.resolve(r);a.welcomeScreen&&a.welcomeScreen.classList.add("hidden");a.readerScreen&&a.readerScreen.classList.add("hidden")}exit(){}}class ka extends fa{enter(){const a=q.locator.resolve(r);a.welcomeScreen&&a.welcomeScreen.classList.remove("hidden");la()}exit(){const a=q.locator.resolve(r);a.welcomeScreen&&a.welcomeScreen.classList.add("hidden");ma()}}
class na extends fa{enter(){const a=q.locator.resolve(r);a.readerScreen&&a.readerScreen.classList.remove("hidden");oa()}exit(){const a=q.locator.resolve(r);a.readerScreen&&a.readerScreen.classList.add("hidden");pa()}};class qa{get(){return Promise.reject(Error("get() must be implemented"))}save(){return Promise.reject(Error("save() must be implemented"))}delete(){return Promise.reject(Error("delete() must be implemented"))}keys(){return Promise.reject(Error("keys() must be implemented"))}clear(){return Promise.reject(Error("clear() must be implemented"))}}
class ra extends qa{get(a){try{return Promise.resolve(localStorage.getItem(a))}catch(b){return console.warn("LocalStorageRepository.get() failed:",b),Promise.resolve(null)}}save(a,b){try{localStorage.setItem(a,b)}catch(c){console.warn("LocalStorageRepository.save() failed:",c)}return Promise.resolve()}delete(a){try{localStorage.removeItem(a)}catch(b){console.warn("LocalStorageRepository.delete() failed:",b)}return Promise.resolve()}keys(){const a=[];try{for(let b=0;b<localStorage.length;b++){const c=
localStorage.key(b);null!==c&&a.push(c)}}catch(b){console.warn("LocalStorageRepository.keys() failed:",b)}return Promise.resolve(a)}clear(){try{localStorage.clear()}catch(a){console.warn("LocalStorageRepository.clear() failed:",a)}return Promise.resolve()}}
class x{constructor(a){this.storage=a;this._KEY="yuzora_config"}async load(){try{const a=await this.storage.get(this._KEY);if(a){const b=JSON.parse(a);if(b&&"object"===typeof b)return b}}catch(a){console.warn("SettingsRepository.load() failed to parse JSON:",a)}return{}}async save(a){try{await this.storage.save(this._KEY,JSON.stringify(a))}catch(b){console.warn("SettingsRepository.save() failed to serialize JSON:",b)}}async clear(){await this.storage.delete(this._KEY)}}
class y{constructor(a){this.storage=a;this._PREFIX="bookmark_"}async load(a){if(!a)return 0;try{const b=await this.storage.get(this._PREFIX+a);if(b){const c=parseFloat(b);return isNaN(c)?0:c}}catch(b){console.warn("BookmarkRepository.load() failed:",b)}return 0}async save(a,b){a&&await this.storage.save(this._PREFIX+a,b.toString())}async clearAll(){const a=(await this.storage.keys()).filter(b=>b.startsWith(this._PREFIX));await Promise.all(a.map(b=>this.storage.delete(b)))}}
class z{constructor(a){this.storage=a;this._KEY_NAME="last_read_file_name";this._KEY_CONTENT="last_read_file_content";this._KEY_TYPE="last_read_file_type"}async load(){const [a,b,c]=await Promise.all([this.storage.get(this._KEY_NAME),this.storage.get(this._KEY_CONTENT),this.storage.get(this._KEY_TYPE)]);return{name:a,content:b,type:c}}async save(a,b,c){await Promise.all([this.storage.save(this._KEY_NAME,a),this.storage.save(this._KEY_CONTENT,b),this.storage.save(this._KEY_TYPE,c)])}async clear(){await Promise.all([this.storage.delete(this._KEY_NAME),
this.storage.delete(this._KEY_CONTENT),this.storage.delete(this._KEY_TYPE)])}}const sa=new ra,ta=new x(sa),ua=new y(sa),va=new z(sa);m.register(ra,sa);m.register(x,ta);m.register(y,ua);m.register(z,va);m.register(ca,new ca);window.YuzoraEvent=ba;window.YuzoraEventTarget=ca;
window.YuzoraEventType={N:"document:load-start",L:"document:loaded",O:"document:rendered",M:"document:load-failed",X:"ui:navigate-page",Y:"ui:page-changed",P:"ui:config-changed",$:"ui:toc-generated",Z:"ui:toc-active-changed",ba:"ui:toggle-debug-modal",aa:"ui:toggle-controls",ca:"ui:toggle-drawer",T:"system:history-updated",S:"system:diagnose-run",R:"system:diagnose-completed",V:"system:layout-repaired",U:"system:layout-check-requested",W:"system:layout-repair-requested"};m.register(h,new h(m.resolve(ca)));window.Publisher=h;class r{constructor(){this.headerTimeout=this.tabContentDiagnose=this.tabContentMonitor=this.tabBtnDiagnose=this.tabBtnMonitor=this.btnImportHistory=this.btnExportHistory=this.debugHistoryJSON=this.diagnoseReportOutput=this.btnCopyDebugReport=this.btnDiagnoseLayout=this.btnClearAll=this.btnClearConfig=this.btnClearBookmarks=this.debugMonitor=this.debugModalOverlay=this.btnCloseDebug=this.debugModal=this.btnOpenDebug=this.readerBooksGrid=this.developerBooksGrid=this.readingIndex=this.readingPercentage=
this.progressBar=this.progressBarContainer=this.readerFooter=this.readerHeader=this.pageNavRight=this.pageNavLeft=this.drawerOverlay=this.tocList=this.tocDrawer=this.settingsDrawer=this.btnCloseTOC=this.btnCloseSettings=this.btnFirstPage=this.btnTOC=this.btnSettings=this.btnBack=this.bookTitle=this.readerContent=this.readerViewport=this.fileInput=this.dropZone=this.readerScreen=this.welcomeScreen=this.app=null;this.isReflowing=!1;this.progressAnimationFrameId=this.cachedClientWidth=this.cachedScrollWidth=
this.config=this.tocObserver=this.activeHeadingId=null;this.isSnapping=!1;this.scrollStartTimestamp=null;this.scrollEventCount=0;this.tocDrawerOpen=this.settingsDrawerOpen=!1}initializeDOMElements(){this.app=document.getElementById("app");this.welcomeScreen=document.getElementById("welcome-screen");this.readerScreen=document.getElementById("reader-screen");this.dropZone=document.getElementById("drop-zone");this.fileInput=document.getElementById("file-input");this.readerViewport=document.getElementById("reader-viewport");
this.readerContent=document.getElementById("reader-content");this.bookTitle=document.getElementById("book-title");this.btnBack=document.getElementById("btn-back");this.btnSettings=document.getElementById("btn-settings");this.btnTOC=document.getElementById("btn-toc");this.btnFirstPage=document.getElementById("btn-first-page");this.btnCloseSettings=document.getElementById("btn-close-settings");this.btnCloseTOC=document.getElementById("btn-close-toc");this.settingsDrawer=document.getElementById("settings-drawer");
this.tocDrawer=document.getElementById("toc-drawer");this.tocList=document.getElementById("toc-list");this.drawerOverlay=document.getElementById("drawer-overlay");this.pageNavLeft=document.getElementById("page-nav-left");this.pageNavRight=document.getElementById("page-nav-right");this.readerHeader=document.querySelector(".reader-header");this.readerFooter=document.querySelector(".reader-footer");this.progressBarContainer=document.querySelector(".progress-bar-container");this.progressBar=document.getElementById("progress-bar");
this.readingPercentage=document.getElementById("reading-percentage");this.readingIndex=document.getElementById("reading-index");this.developerBooksGrid=document.getElementById("developer-books-grid");this.readerBooksGrid=document.getElementById("reader-books-grid");this.btnOpenDebug=document.getElementById("btn-open-debug");this.debugModal=document.getElementById("debug-modal");this.btnCloseDebug=document.getElementById("btn-close-debug");this.debugModalOverlay=document.getElementById("debug-modal-overlay");
this.debugMonitor=document.getElementById("debug-monitor");this.btnClearBookmarks=document.getElementById("btn-clear-bookmarks");this.btnClearConfig=document.getElementById("btn-clear-config");this.btnClearAll=document.getElementById("btn-clear-all");this.btnDiagnoseLayout=document.getElementById("btn-diagnose-layout");this.btnCopyDebugReport=document.getElementById("btn-copy-debug-report");this.diagnoseReportOutput=document.getElementById("diagnose-report-output");this.debugHistoryJSON=document.getElementById("debug-history-json");
this.btnExportHistory=document.getElementById("btn-export-history");this.btnImportHistory=document.getElementById("btn-import-history");this.tabBtnMonitor=document.getElementById("tab-btn-monitor");this.tabBtnDiagnose=document.getElementById("tab-btn-diagnose");this.tabContentMonitor=document.getElementById("debug-tab-content-monitor");this.tabContentDiagnose=document.getElementById("debug-tab-content-diagnose")}}
class B{constructor(){this.type=this.content=this.author=this.title="";this.currentPage=this.totalPages=0;this.toc=[]}isEmpty(){return!this.title||!this.content}clear(){this.type=this.content=this.author=this.title="";this.currentPage=this.totalPages=0;this.toc=[]}}
class C{constructor(){this.theme="sepia";this.font="font-gothic";this.direction="rtl";this.size="size-md";this.lh="line-height-normal";this.spacing="spacing-normal"}async load(){const a=await q.locator.resolve(x).load();a&&"object"===typeof a&&0<Object.keys(a).length&&(a.theme&&(this.theme=a.theme),a.font&&(this.font=a.font),a.direction&&(this.direction=a.direction),a.size&&(this.size=a.size),a.lh&&(this.lh=a.lh),a.spacing&&(this.spacing=a.spacing))}async save(){await q.locator.resolve(x).save({theme:this.theme,
font:this.font,direction:this.direction,size:this.size,lh:this.lh,spacing:this.spacing})}apply(){document.body.setAttribute("data-theme",this.theme);var a=q.locator.resolve(r);a.readerContent&&a.readerViewport&&(a.readerViewport.style.direction=this.direction,a.readerContent.className="reader-content",a.readerContent.classList.add(this.font,`direction-${this.direction}`,this.size,this.lh,this.spacing),"rtl"===this.direction?(a.pageNavLeft.title="\u6b21\u306e\u30da\u30fc\u30b8\u3078",a.pageNavRight.title=
"\u524d\u306e\u30da\u30fc\u30b8\u3078"):(a.pageNavLeft.title="\u524d\u306e\u30da\u30fc\u30b8\u3078",a.pageNavRight.title="\u6b21\u306e\u30da\u30fc\u30b8\u3078"),(a=a.btnFirstPage?a.btnFirstPage.querySelector("path"):null)&&("rtl"===this.direction?a.setAttribute("d","M11.25 4.5l7.5 7.5-7.5 7.5m-6-15l7.5 7.5-7.5 7.5"):a.setAttribute("d","M18.75 19.5l-7.5-7.5 7.5-7.5m-6 15L5.25 12l7.5-7.5")),"function"===typeof E&&(E(".theme-selector button","theme",this.theme),E(".font-selector button","font",this.font),
E(".direction-selector button","direction",this.direction),E(".size-selector button","size",this.size),E(".lh-selector button","lh",this.lh),E(".spacing-selector button","spacing",this.spacing)))}}class F{constructor(){this.bookmarkProgress=0}async save(a,b){a&&(this.bookmarkProgress=b,await q.locator.resolve(y).save(a,b))}async load(a){return a?this.bookmarkProgress=await q.locator.resolve(y).load(a):this.bookmarkProgress=0}clear(){this.bookmarkProgress=0}}
var wa=[{id:"kokoro",title:"\u3053\u3053\u308d",j:"\u3053\u3053\u308d",l:773,path:"src/books/773_yoko.txt",i:"developer",author:"\u590f\u76ee\u6f31\u77f3",m:"\u590f\u76ee\u6f31\u77f3"},{id:"gokyo",title:"\u6545\u90f7",j:"\u6545\u90f7",l:42939,path:"src/books/42939_yoko.txt",i:"developer",author:"\u9b6f\u8fc5",m:"\u9b6f\u8fc5"},{id:"musashi_01",title:"\u5bae\u672c\u6b66\u8535 01 \u5e8f\u3001\u306f\u3057\u304c\u304d",j:"\u5e8f\u3001\u306f\u3057\u304c\u304d",l:52395,path:"src/books/52395_yoko.txt",i:"reader",
author:"\u5409\u5ddd\u82f1\u6cbb",m:"01"},{id:"musashi_02",title:"\u5bae\u672c\u6b66\u8535 02 \u5730\u306e\u5dfb",j:"\u5730\u306e\u5dfb",l:52396,path:"src/books/52396_yoko.txt",i:"reader",author:"\u5409\u5ddd\u82f1\u6cbb",m:"02"},{id:"musashi_03",title:"\u5bae\u672c\u6b66\u8535 03 \u6c34\u306e\u5dfb",j:"\u6c34\u306e\u5dfb",l:52397,path:"src/books/52397_yoko.txt",i:"reader",author:"\u5409\u5ddd\u82f1\u6cbb",m:"03"},{id:"musashi_04",title:"\u5bae\u672c\u6b66\u8535 04 \u706b\u306e\u5dfb",j:"\u706b\u306e\u5dfb",
l:52398,path:"src/books/52398_yoko.txt",i:"reader",author:"\u5409\u5ddd\u82f1\u6cbb",m:"04"},{id:"musashi_05",title:"\u5bae\u672c\u6b66\u8535 05 \u98a8 of the roll",j:"\u98a8\u306e\u5dfb",l:52399,path:"src/books/52399_yoko.txt",i:"reader",author:"\u5409\u5ddd\u82f1\u6cbb",m:"05"},{id:"musashi_06",title:"\u5bae\u672c\u6b66\u8535 06 \u7a7a\u306e\u5dfb",j:"\u7a7a\u306e\u5dfb",l:52400,path:"src/books/52400_yoko.txt",i:"reader",author:"\u5409\u5ddd\u82f1\u6cbb",m:"06"},{id:"musashi_07",title:"\u5bae\u672c\u6b66\u8535 07 \u4e8c\u5929\u306e\u5dfb",
j:"\u4e8c\u5929\u306e\u5dfb",l:52401,path:"src/books/52401_yoko.txt",i:"reader",author:"\u5409\u5ddd\u82f1\u6cbb",m:"07"},{id:"musashi_08",title:"\u5bae\u672c\u6b66\u8535 08 \u5186\u660e\u306e\u5dfb",j:"\u5186\u660e\u306e\u5dfb",l:52402,path:"src/books/52402_yoko.txt",i:"reader",author:"\u5409\u5ddd\u82f1\u6cbb",m:"08"}];m.register(r,new r);m.register(B,new B);m.register(C,new C);m.register(F,new F);class xa{constructor(a,b){this.id=a;this.type=b;this.status="loading";this.error=null}dispose(){this.type=this.id="";this.status="failed";this.error=null}}class ya extends xa{constructor(a,b){super(a,"book");this.title="";this.content=b||"";this.toc=[]}dispose(){super.dispose();this.content=this.title="";this.toc=[]}}window.Asset=xa;window.BookAsset=ya;class G{constructor(){this.assets=new Map}loadBook(a,b,c){if(b.startsWith("http://")||b.startsWith("https://")||b.startsWith("//"))try{var d=(new URL(b,window.location.href)).origin===window.location.origin}catch(f){d=!1}else d=!0;if(!d)return c=Error("Security Error: Fetching from external origin is blocked."),b=new ya(a,""),b.status="failed",b.error=c,this.assets.set(a,b),Promise.reject(c);if(this.assets.has(a)&&(b=this.assets.get(a),b instanceof ya)){if("ready"===b.status)return Promise.resolve(b);
if("loading"===b.status)return Promise.reject(Error("Asset is currently loading."))}var e=new ya(a,"");this.assets.set(a,e);return c().then(f=>{if(f&&2097152<f.length)throw f=Error("File size exceeds the 2MB safety limit."),e.status="failed",e.error=f,f;e.content=f;e.status="ready";return e}).catch(f=>{e.status="failed";e.error=f;throw f;})}unload(a){this.assets.has(a)&&(this.assets.get(a).dispose(),this.assets.delete(a))}clear(){this.assets.forEach(a=>{a.dispose()});this.assets.clear()}}
window.ResourceDirector=G;class I{constructor(a){this.type=a}execute(){throw Error("execute() must be implemented");}serialize(){return{type:this.type,params:{}}}}
class za extends I{constructor(a,b){super("LoadBook");this.fileName=a;this.fileContent=b}execute(){const a=q.locator.resolve(B),b=this;q.locator.resolve(G).loadBook(this.fileName,this.fileName,function(){return Promise.resolve(b.fileContent)}).then(function(c){a.title=c.id;a.type=c.id.endsWith(".html")||c.id.endsWith(".xhtml")?"html":"txt";a.content=c.content;yuzora.publisher.publish("document:loaded",{fileName:b.fileName,fileContent:b.fileContent})}).catch(function(c){console.error("LoadBookCommand execution failed:",
c)})}serialize(){return{type:this.type,params:{fileName:this.fileName,fileContent:this.fileContent}}}}class J extends I{constructor(a){super("NavigatePage");this.targetPage=a}execute(){q.locator.resolve(r).readerViewport&&yuzora.publisher.publish("ui:navigate-page",{targetPage:this.targetPage})}serialize(){return{type:this.type,params:{targetPage:this.targetPage}}}}
class K extends I{constructor(a,b){super("UpdateConfig");this.configKey=a;this.configValue=b}async execute(){const a=q.locator.resolve(r),b=q.locator.resolve(C),c=q.locator.resolve(F);b[this.configKey]=this.configValue;Aa(this.configKey,this.configValue);a.isReflowing=!0;Ba();setTimeout(()=>{const d=Math.abs(a.readerViewport.scrollWidth-a.readerViewport.clientWidth);a.readerViewport.scrollLeft="rtl"===b.direction?-(c.bookmarkProgress*d):c.bookmarkProgress*d;a.isReflowing=!1},150);await Ca()}serialize(){return{type:this.type,
params:{configKey:this.configKey,configValue:this.configValue}}}}class Ea extends I{constructor(a){super("SyncBookmark");this.progress=a}execute(){q.locator.resolve(F).bookmarkProgress=this.progress}serialize(){return{type:this.type,params:{progress:this.progress}}}}
class Fa extends I{constructor(a){super("ToggleControls");this.visible=a}execute(){if(this.visible)Ga();else{const a=q.locator.resolve(r);a.headerTimeout&&clearTimeout(a.headerTimeout);Ha()}}serialize(){return{type:this.type,params:{visible:this.visible}}}}
class M extends I{constructor(a,b){super("ToggleDrawer");this.drawerId=a;this.open=b}execute(){const a=q.locator.resolve(r);var b="settings"===this.drawerId?a.settingsDrawer:a.tocDrawer;b&&(this.open?(b.classList.add("open"),a.drawerOverlay&&a.drawerOverlay.classList.add("active"),"toc"===this.drawerId&&Ia()):(b.classList.remove("open"),(b="settings"===this.drawerId?a.tocDrawer:a.settingsDrawer)&&!b.classList.contains("open")&&a.drawerOverlay&&a.drawerOverlay.classList.remove("active")))}serialize(){return{type:this.type,
params:{drawerId:this.drawerId,open:this.open}}}}class Ja extends I{constructor(){super("ExitReader")}execute(){const a=q.locator.resolve(B),b=q.locator.resolve(z);q.locator.resolve(ia).navigate("/welcome");b.clear();a.clear()}serialize(){return{type:this.type,params:{}}}}
class Ka extends I{constructor(a){super("ClearStorage");this.clearType=a}async execute(){const a=q.locator.resolve(F),b=q.locator.resolve(y),c=q.locator.resolve(x),d=q.locator.resolve(z);"bookmarks"===this.clearType?(await b.clearAll(),a.bookmarkProgress=0,La()):"config"===this.clearType?(await c.clear(),N.isReplaying||window.location.reload()):"all"===this.clearType&&(await Promise.all([b.clearAll(),c.clear(),d.clear()]),N.isReplaying||window.location.reload())}serialize(){return{type:this.type,
params:{clearType:this.clearType}}}}class O extends I{constructor(a){super("ToggleDebugModal");this.open=a}execute(){yuzora.publisher.publish("ui:toggle-debug-modal",{open:this.open})}serialize(){return{type:this.type,params:{open:this.open}}}}function Ma(a){yuzora.publisher.publish("system:history-updated",{history:a.commandHistory.map(b=>b.serialize()),ea:!1,da:!1})}
function Na(a){switch(a.type){case "LoadBook":return new za(a.params.fileName,a.params.fileContent);case "NavigatePage":return new J(a.params.targetPage);case "UpdateConfig":return new K(a.params.configKey,a.params.configValue);case "SyncBookmark":return new Ea(a.params.progress);case "ToggleControls":return new Fa(a.params.visible);case "ToggleDrawer":return new M(a.params.drawerId,a.params.open);case "ExitReader":return new Ja;case "ClearStorage":return new Ka(a.params.clearType);case "ToggleDebugModal":return new O(a.params.open);
default:throw Error(`Unknown command type: ${a.type}`);}}function Oa(a,b,c){return(b={LoadBook:a.s,NavigatePage:a.G,UpdateConfig:a.h,SyncBookmark:a.H,ToggleControls:a.I,ToggleDrawer:a.K,ExitReader:()=>!0,ClearStorage:a.g,ToggleDebugModal:a.J}[b])?b.call(a,c):!1}
class Pa{constructor(){this.commandHistory=[];this.isReplaying=!1}undo(){console.warn("Undo operation is not implemented.")}redo(){console.warn("Redo operation is not implemented.")}async execute(a,b=!1){if(!this.isReplaying||b){await a.execute();if(b=!b)0===this.commandHistory.length?b=!1:(b=this.commandHistory[this.commandHistory.length-1],b="NavigatePage"===a.type&&"NavigatePage"===b.type?b.targetPage===a.targetPage:"SyncBookmark"===a.type&&"SyncBookmark"===b.type?.001>Math.abs(b.progress-a.progress):
!1),b=!b;b&&(this.commandHistory.push(a),100>=this.commandHistory.length||("LoadBook"===this.commandHistory[0].type?this.commandHistory.splice(1,1):this.commandHistory.shift()),Ma(this))}}exportJSON(){return JSON.stringify(this.commandHistory.map(a=>a.serialize()),null,2)}h(a){if(!a||"string"!==typeof a.configKey||"string"!==typeof a.configValue)return!1;var b={theme:["sepia","light","dark","black"],font:["font-mincho","font-gothic"],direction:["rtl","ltr"],size:["size-sm","size-md","size-lg"],lh:["line-height-sm",
"line-height-normal","line-height-lg"],spacing:["spacing-sm","spacing-normal","spacing-lg"]};if(!Object.prototype.hasOwnProperty.call(b,a.configKey))return!1;b=b[a.configKey];return!!b&&b.includes(a.configValue)}s(a){return!!a&&"string"===typeof a.fileName&&"string"===typeof a.fileContent}G(a){return!!a&&"number"===typeof a.targetPage&&!isNaN(a.targetPage)&&1<=a.targetPage}H(a){return!!a&&"number"===typeof a.progress&&!isNaN(a.progress)&&0<=a.progress&&1>=a.progress}I(a){return!!a&&"boolean"===typeof a.visible}K(a){return!!a&&
("settings"===a.drawerId||"toc"===a.drawerId)&&"boolean"===typeof a.open}g(a){return!!a&&["bookmarks","config","all"].includes(a.clearType)}J(a){return!!a&&"boolean"===typeof a.open}importJSON(a){try{const c=JSON.parse(a);if(!Array.isArray(c))throw Error("Input operations history must be a JSON array");a=[];for(const d of c){a:{if(!d||"object"!==typeof d||"string"!==typeof d.type||!d.params||"object"!==typeof d.params){var b=!1;break a}const e=d.params;for(const f of Object.keys(e))if("__proto__"===
f||"constructor"===f||"prototype"===f){b=!1;break a}b=Oa(this,d.type,e)}if(b){const e=Na(d);e&&a.push(e)}else console.warn("Skipping invalid/unsafe command item:",d)}return a}catch(c){return console.error("Failed to parse operations history JSON:",c),alert(`\u5c65\u6b74\u30c7\u30fc\u30bf\u306e\u30a4\u30f3\u30dd\u30fc\u30c8\u306b\u5931\u6557\u3057\u307e\u3057\u305f:\n${c instanceof Error?c.message:String(c)}`),null}}updateDebugMonitor(){const a=q.locator.resolve(r);if(a.debugMonitor){var b=document.querySelector('meta[name="build-id"]'),
c=document.querySelector('meta[name="build-date"]');b=b&&b.content?b.content:"";c=c&&c.content?c.content:"";a.debugMonitor.textContent=`Build: ${b&&"BUILD_ID_PLACEHOLDER"!==b?b:"dev"}  ${c&&"BUILD_DATE_PLACEHOLDER"!==c?c:"---"}\nHistory: ${this.commandHistory.length} operations.`}}}const Qa=new Pa;m.register(Pa,Qa);m.register(Pa,Qa);var N=m.resolve(Pa);class P{constructor(a,b,c,d){this.type=a;this.value=b;this.rt=c;this.children=d}}class Ra extends P{constructor(a){super("Root",void 0,void 0,a)}}class Sa extends P{constructor(a){super("Text",a,void 0,void 0)}}class Ta extends P{constructor(a,b){super("Ruby",a,b,void 0)}}class Ua extends P{constructor(a){super("Bold",void 0,void 0,a)}}class Va extends P{constructor(a){super("Italic",void 0,void 0,a)}}class Wa extends P{constructor(a){super("Bouten",void 0,void 0,a)}}window.ASTNode=P;
window.RootNode=Ra;window.TextNode=Sa;window.RubyNode=Ta;window.BoldNode=Ua;window.ItalicNode=Va;window.BoutenNode=Wa;class Xa extends P{constructor(a){super("Document",void 0,void 0,a)}}class Ya extends P{constructor(a,b){super("CoverPage");this.title=a;this.author=b}}class Za extends P{constructor(){super("PageBreak")}}class $a extends P{constructor(){super("EmptyLine")}}
class ab extends P{constructor(a,b,c,d,e){super("Heading",void 0,void 0,c);this.level=a;this.headingId=b;this.jisageClass=d;this.alignmentClass=e}}class bb extends P{constructor(a,b,c){super("Paragraph",void 0,void 0,c);this.jisageClass=a;this.alignmentClass=b}}window.DocumentNode=Xa;window.CoverPageNode=Ya;window.PageBreakNode=Za;window.EmptyLineNode=$a;window.HeadingNode=ab;window.ParagraphNode=bb;class cb{tokenizeInline(a){const b=[];let c=0;for(;c<a.length;){if("\uff5c"===a[c]||"|"===a[c]){var d=a.indexOf("\u300a",c);if(-1!==d){var e=a.indexOf("\u300b",d);if(-1!==e){b.push({type:"RUBY",value:a.substring(c+1,d),rt:a.substring(d+1,e),children:void 0});c=e+1;continue}}}if(d=a.substring(c).match(/^((?:[\u4e00-\u9fa0\u3005\u4edd\u3006\u3007\u30f6]|\u203b\uff3b\uff03\u4e8c\u306e\u5b57\u70b9\u3001\u9762\u533a\u70b9\u756a\u53f71-2-22\uff3d)+|[A-Za-z]+)\u300a([^\u300b]+)\u300b/))b.push({type:"RUBY",
value:d[1],rt:d[2],children:void 0}),c+=d[0].length;else if(a.startsWith("\uff3b\uff03\u3053\u3053\u304b\u3089\u592a\u5b57\uff3d",c))b.push({type:"BOLD_START",value:void 0,rt:void 0,children:void 0}),c+=9;else if(a.startsWith("\uff3b\uff03\u3053\u3053\u3067\u592a\u5b57\u7d42\u308f\u308a\uff3d",c))b.push({type:"BOLD_END",value:void 0,rt:void 0,children:void 0}),c+=11;else if(a.startsWith("\uff3b\uff03\u3053\u3053\u304b\u3089\u659c\u4f53\uff3d",c))b.push({type:"ITALIC_START",value:void 0,rt:void 0,
children:void 0}),c+=9;else if(a.startsWith("\uff3b\uff03\u3053\u3053\u3067\u659c\u4f53\u7d42\u308f\u308a\uff3d",c))b.push({type:"ITALIC_END",value:void 0,rt:void 0,children:void 0}),c+=11;else if(a.startsWith("\uff3b\uff03\u508d\u70b9\uff3d",c))b.push({type:"BOUTEN_START",value:void 0,rt:void 0,children:void 0}),c+=5;else if(a.startsWith("\uff3b\uff03\u508d\u70b9\u7d42\u308f\u308a\uff3d",c))b.push({type:"BOUTEN_END",value:void 0,rt:void 0,children:void 0}),c+=8;else{if(a.startsWith("\uff3b\uff03",
c)&&(d=a.indexOf("\uff3d",c),-1!==d)){c=d+1;continue}d=a.length;e=["\uff5c","|","\uff3b\uff03","\u300a"];for(let f=0;f<e.length;f++){const g=a.indexOf(e[f],c);-1!==g&&g<d&&(d=g)}e=a.substring(c,d);"\u300a"===a[d]&&(e=e.match(/([\u4e00-\u9fa0\u3005\u4edd\u3006\u3007\u30f6]+|[A-Za-z]+)$/))&&(d=c+e.index);d===c?(b.push({type:"TEXT",value:a[c],rt:void 0,children:void 0}),c++):(b.push({type:"TEXT",value:a.substring(c,d),rt:void 0,children:void 0}),c=d)}}return b}}window.AozoraTokenizer=cb;function db(a,b,c){if(b.children)for(let d=0;d<b.children.length;d++){const e=b.children[d];"Ruby"===e.type?c?(console.warn(`Semantic Warning: Nested ruby tag detected for "${e.value}". Flatting it to plain text.`),b.children[d]=new Sa(e.value||"")):db(a,e,!0):db(a,e,c)}}class eb{analyze(a){db(this,a,!1);return a}}window.AozoraSemanticAnalyzer=eb;function Q(a,b){if("Document"===b.type)return(b.children||[]).map(e=>Q(a,e)).join("\n");if("CoverPage"===b.type){var c=a.escapeHTML(b.title||"");b=a.escapeHTML(b.author||"");return`<div class="book-cover-page">\n    <h1 class="book-cover-title">${c}</h1>\n    <p class="book-cover-author">${b}</p>\n</div>`}if("PageBreak"===b.type)return'<div class="page-break"></div>';if("EmptyLine"===b.type)return'<p class="empty-line">&nbsp;</p>';if("Heading"===b.type){c=b.level||2;const e=b.headingId||"";var d=
[];b.jisageClass&&d.push(b.jisageClass);b.alignmentClass&&d.push(b.alignmentClass);d=0<d.length?` class="${d.join(" ")}"`:"";b=(b.children||[]).map(f=>Q(a,f)).join("");return`<h${c} id="${e}"${d}>${b}</h${c}>`}return"Paragraph"===b.type?(c=[],b.jisageClass&&c.push(b.jisageClass),b.alignmentClass&&c.push(b.alignmentClass),c=0<c.length?` class="${c.join(" ")}"`:"",b=(b.children||[]).map(e=>Q(a,e)).join(""),`<p${c}>${b}</p>`):"Root"===b.type?(b.children||[]).map(e=>Q(a,e)).join(""):"Text"===b.type?a.escapeHTML(b.value||
""):"Ruby"===b.type?`<ruby>${a.escapeHTML(b.value||"")}<rt>${a.escapeHTML(b.rt||"")}</rt></ruby>`:"Bold"===b.type?`<strong class="aozora-bold">${(b.children||[]).map(e=>Q(a,e)).join("")}</strong>`:"Italic"===b.type?`<em class="aozora-italic">${(b.children||[]).map(e=>Q(a,e)).join("")}</em>`:"Bouten"===b.type?`<span class="em-sesame">${(b.children||[]).map(e=>Q(a,e)).join("")}</span>`:""}
class fb{evaluate(a){return Q(this,a)}escapeHTML(a){return a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}sanitizeDOM(a){function b(f){var g=Array.from(f.attributes);for(const k of g)if(g=k.name.toLowerCase(),g.startsWith("on")||!e.has(g))f.removeAttribute(k.name);else if("href"===g||"src"===g)g=k.value.trim().toLowerCase(),(g.startsWith("javascript:")||g.startsWith("data:")||g.startsWith("vbscript:"))&&f.removeAttribute(k.name)}function c(f){f=Array.from(f.childNodes);for(const g of f)if(1===
g.nodeType){f=g;const k=f.tagName.toLowerCase();if(d.has(k))b(f),c(f);else{if(!["script","style","iframe"].includes(k))for(;f.firstChild;)f.parentNode.insertBefore(f.firstChild,f);f.remove()}}}const d=new Set("div span p h1 h2 h3 h4 h5 h6 a ruby rt rp br img b i strong em".split(" ")),e=new Set(["class","id","src","alt","href"]);b(a);c(a)}}window.AozoraEvaluator=fb;function gb(a){return a?a.replace(/[\uff5c|]/g,"").replace(/\u300a[^\u300b]+\u300b/g,"").trim():""}function hb(a){var b="";const c=a.match(/\uff3b\uff03([\uff10-\uff190-9]+)\u5b57\u4e0b\u3052\uff3d/);c&&(b=c[1].replace(/[\uff10-\uff19]/g,d=>String.fromCharCode(d.charCodeAt(0)-65248)),b=`jisage${parseInt(b,10)}`,a=a.replace(/\uff3b\uff03[\uff10-\uff190-9]+\u5b57\u4e0b\u3052\uff3d/,""));return{jisageClass:b,line:a}}
function ib(a){var b="";if(a.includes("\uff3b\uff03\u5730\u4ed8\u304d\uff3d"))b="chitsuki",a=a.replace(/\uff3b\uff03\u5730\u4ed8\u304d\uff3d/g,"");else if(a.includes("\uff3b\uff03\u5730\u5bc4\u305b\uff3d"))b="chiyose",a=a.replace(/\uff3b\uff03\u5730\u5bc4\u305b\uff3d/g,"");else{const c=a.match(/\uff3b\uff03\u5730\u304b\u3089([\uff10-\uff190-9]+)\u5b57\u4e0a\u3052\uff3d/);c&&(b=c[1].replace(/[\uff10-\uff19]/g,d=>String.fromCharCode(d.charCodeAt(0)-65248)),b=`chitage-${parseInt(b,10)}`,a=a.replace(/\uff3b\uff03\u5730\u304b\u3089[\uff10-\uff190-9]+\u5b57\u4e0a\u3052\uff3d/g,
""))}return{alignmentClass:b,line:a}}function jb(a,b){b=a.s.tokenizeInline(b);b=a.parseTokensToAST(b);return b=a.h.analyze(b)}
class R{constructor(){this.s=q.locator.resolve(cb);this.h=q.locator.resolve(eb);this.g=q.locator.resolve(fb)}parseTokensToAST(a){const b=new Ra([]),c=[b];for(let e=0;e<a.length;e++){var d=a[e];const f=c[c.length-1];"TEXT"===d.type?f.children.push(new Sa(d.value||"")):"RUBY"===d.type?f.children.push(new Ta(d.value||"",d.rt||"")):"BOLD_START"===d.type?(d=new Ua([]),f.children.push(d),c.push(d)):"BOLD_END"===d.type?1<c.length&&"Bold"===c[c.length-1].type&&c.pop():"ITALIC_START"===d.type?(d=new Va([]),
f.children.push(d),c.push(d)):"ITALIC_END"===d.type?1<c.length&&"Italic"===c[c.length-1].type&&c.pop():"BOUTEN_START"===d.type?(d=new Wa([]),f.children.push(d),c.push(d)):"BOUTEN_END"===d.type&&1<c.length&&"Bouten"===c[c.length-1].type&&c.pop()}return b}parseAozoraText(a){var b=q.locator.resolve(B);b.toc=[];let c=0,d=a.split(/\r?\n/),e=a="";0<d.length&&(a=gb(d[0]));1<d.length&&(e=gb(d[1]));b.title=a;b.author=e;const f=[];f.push(new Ya(a,e));f.push(new Za);let g=!0,k=!1;for(let u=0;u<d.length;u++){var l=
d[u];if(g){if(l.includes("-------------------------------------------------------")){g=!1;var n=d[u+2]?d[u+2].trim():"";if((d[u+1]?d[u+1].trim():"").includes("\u3010\u30c6\u30ad\u30b9\u30c8\u4e2d\u306b\u73fe\u308c\u308b\u8a18\u53f7\u306b\u3064\u3044\u3066\u3011")||n.includes("\u3010\u30c6\u30ad\u30b9\u30c8\u4e2d\u306b\u73fe\u308c\u308b\u8a18\u53f7\u306b\u3064\u3044\u3066\u3011"))k=!0;continue}n=l;var p=u;if(n.includes("-------------------------------------------------------")||n.includes("\uff3b\uff03")&&
(n.includes("\u59cb\u307e\u308a")||n.includes("\u76ee\u6b21"))||0<n.trim().length&&!n.startsWith("\uff3b\uff03")&&2<p)g=!1;else continue}if(k){l.includes("-------------------------------------------------------")&&(k=!1);continue}if(0===l.trim().length){f.push(new $a);continue}if("\uff3b\uff03\u6539\u30da\u30fc\u30b8\uff3d"===l.trim()){f.push(new Za);continue}const {jisageClass:v,line:H}=hb(l),{alignmentClass:w,line:D}=ib(H);n=D;p=!1;l=2;let A="";var t=n.match(/\uff3b\uff03\u300c([^\u300d]+)\u300d\u306f(\u5927|\u4e2d|\u5c0f)\u898b\u51fa\u3057\uff3d/);
t&&(p=!0,A=t[1],t=t[2],"\u5927"===t?l=2:"\u4e2d"===t?l=3:"\u5c0f"===t&&(l=4),n=n.replace(/\uff3b\uff03\u300c[^\u300d]+\u300d\u306f(?:\u5927|\u4e2d|\u5c0f)\u898b\u51fa\u3057\uff3d/,""));const {F:T,C:L,D:ea,line:Da}={F:p,C:l,D:A,line:n};n=jb(this,Da);if(T){if(2===L||3===L){p=null;for(l=f.length-1;0<=l;l--)if("EmptyLine"!==f[l].type){p=f[l];break}p&&"Heading"!==p.type&&"PageBreak"!==p.type&&"CoverPage"!==p.type&&f.push(new Za)}p=`toc-heading-${c}`;b.toc.push({id:p,text:ea.replace(/[\uff5c|]/g,"").replace(/\u300a[^\u300b]+\u300b/g,
"").trim(),level:L});c++;f.push(new ab(L,p,n.children||[],v,w))}else f.push(new bb(v,w,n.children||[]))}b=this.g.evaluate(new Xa(f));return{title:this.g.escapeHTML(a)+(e?` (${this.g.escapeHTML(e)})`:""),body:b}}parseAozoraHTML(a){var b=(new DOMParser).parseFromString(a,"text/html");a=(a=b.querySelector("title"))?a.textContent:"";let c=b.querySelector(".main_body");c||=b.querySelector("body");(b=c.querySelector(".bibliographical_information"))&&b.remove();(b=c.querySelector(".card_link"))&&b.remove();
this.g.sanitizeDOM(c);return{title:a||"",body:c.innerHTML}}formatAozoraMarkup(a){a=jb(this,a);return this.g.evaluate(a)}}window.AozoraParser=R;function kb(a){if(!a)return{currentPage:0,A:0};const b=Math.abs(a.scrollLeft),c=Math.round(a.scrollWidth/a.clientWidth)||0;return{currentPage:0<a.scrollWidth-a.clientWidth?Math.round(b/a.clientWidth)+1:0<c?1:0,A:c}}
function lb(a,b){const c=q.locator.resolve(B),d=q.locator.resolve(C),e=q.locator.resolve(F),f=q.locator.resolve(r);let g;g="### \ud83d\udcd6 \u3086\u3046\u305e\u3089 \u30ec\u30a4\u30a2\u30a6\u30c8\u8a3a\u65ad\u30ec\u30dd\u30fc\u30c8\n"+`- **\u65e5\u6642**: ${(new Date).toLocaleString()}\n`;g+=`- **\u30d5\u30a1\u30a4\u30eb\u540d**: ${c.title||"(\u672a\u30ed\u30fc\u30c9)"}\n`;g+=`- **\u30d5\u30a1\u30a4\u30eb\u7a2e\u5225**: ${c.type||"(\u306a\u3057)"}\n`;g=g+"- **\u8868\u793a\u8a2d\u5b9a**:\n"+`  - \u30c6\u30fc\u30de: ${d.theme}\n`;
g+=`  - \u66f8\u4f53: ${"font-mincho"===d.font?"\u660e\u671d\u4f53":"\u30b4\u30b7\u30c3\u30af\u4f53"}\n`;g+=`  - \u9001\u308a\u65b9\u5411: ${"rtl"===d.direction?"\u53f3\u304b\u3089\u5de6 (RTL)":"\u5de6\u304b\u3089\u53f3 (LTR)"}\n`;g+=`  - \u6587\u5b57\u30b5\u30a4\u30ba: ${d.size}\n`;g+=`  - \u884c\u9593: ${d.lh}\n`;g+=`  - \u6587\u5b57\u9593: ${d.spacing}\n`;g=g+"- **\u753b\u9762\u30b5\u30a4\u30ba**:\n"+`  - \u30d3\u30e5\u30fc\u30dd\u30fc\u30c8\u5e45(clientWidth): ${f.readerViewport.clientWidth}px\n`;
g+=`  - \u30d3\u30e5\u30fc\u30dd\u30fc\u30c8\u9ad8(clientHeight): ${f.readerViewport.clientHeight}px\n`;g+=`  - \u30b3\u30f3\u30c6\u30f3\u30c4\u5168\u4f53\u5e45(scrollWidth): ${f.readerViewport.scrollWidth}px\n`;g=g+"- **\u30b9\u30af\u30ed\u30fc\u30eb\u72b6\u614b**:\n"+`  - scrollLeft: ${f.readerViewport.scrollLeft}px\n`;g+=`  - \u9032\u6357\u5272\u5408(bookmarkProgress): ${(100*e.bookmarkProgress).toFixed(1)}%\n`;return g+`  - \u30da\u30fc\u30b8\u6570: \u73fe\u5728 ${a} / ${b} \u30da\u30fc\u30b8\n\n`}
function mb(a){const b=a.marginLeft||"0px",c=a.marginRight||"0px";a="### \ud83d\udcd0 \u30ab\u30e9\u30e0\uff06\u30d3\u30e5\u30fc\u30dd\u30fc\u30c8\u8a08\u7b97\u691c\u8a3c\n- **\u30b3\u30f3\u30c6\u30f3\u30c4\u914d\u7f6e\u30b9\u30bf\u30a4\u30eb**:\n"+`  - column-width: ${a.columnWidth||"auto"}\n`+`  - column-gap: ${a.columnGap||"normal"}\n`;a=a+`  - margin-left: ${b}\n`+`  - margin-right: ${c}\n`;return a+="\n"}
function nb(a){var b=q.locator.resolve(r).readerViewport.clientWidth;const c=parseFloat(a.columnWidth||"auto")||0;var d=parseFloat(a.marginLeft||"0px")||0;const e=parseFloat(a.marginRight||"0px")||0;d=(a=768>window.innerWidth)?b-d-e:b/2-d-e;b=Math.abs(c-d);a="- **\u30ab\u30e9\u30e0\u4ed5\u69d8\u30c1\u30a7\u30c3\u30af**:\n"+`  - \u30c7\u30d0\u30a4\u30b9\u74b0\u5883: ${a?"\u30e2\u30d0\u30a4\u30eb (1\u6bb5\u7d44\u307f)":"PC (\u898b\u958b\u304d2\u6bb5\u7d44\u307f)"}\n`+`  - \u7406\u8ad6\u4e0a\u306e\u7406\u60f3\u30ab\u30e9\u30e0\u5e45: ${d.toFixed(1)}px (\u8a08\u7b97\u5f0f: ${a?
"W - margins":"W/2 - margins"})\n`;a+=`  - \u5b9f\u969b\u306e\u30ab\u30e9\u30e0\u5e45: ${c.toFixed(1)}px\n`;a=2<b?a+`  - \u26a0\ufe0f **\u8b66\u544a**: \u5b9f\u969b\u306e\u30ab\u30e9\u30e0\u5e45\u304c\u7406\u60f3\u306e\u5e45\u3068 ${b.toFixed(1)}px \u30ba\u30ec\u3066\u3044\u307e\u3059\u3002\u6539\u6bb5\u305a\u308c\u306e\u539f\u56e0\u3068\u306a\u308a\u307e\u3059\u3002\n`:a+"  - \u2705 **\u6b63\u5e38**: \u30ab\u30e9\u30e0\u5e45\u306f\u30ec\u30a4\u30a2\u30a6\u30c8\u8a2d\u8a08\u901a\u308a\u3067\u3059\u3002\n";
return a+"\n"}
function ob(a,b){var c=q.locator.resolve(r);let d="### \ud83d\udcd0 \u7e26\u65b9\u5411\u30ec\u30a4\u30a2\u30a6\u30c8\u914d\u7f6e\n";var e=document.querySelector(".reader-header"),f=document.querySelector(".reader-footer");e&&f&&(e=e.getBoundingClientRect(),f=f.getBoundingClientRect(),c=c.readerContent.getBoundingClientRect(),d+=`- **\u30d8\u30c3\u30c0\u30fc Y\u5ea7\u6a19\u7bc4\u56f2**: ${e.top.toFixed(1)}px \u301c ${e.bottom.toFixed(1)}px (\u9ad8\u3055: ${e.height.toFixed(1)}px)\n`,d+=`- **\u30d5\u30c3\u30bf\u30fc Y\u5ea7\u6a19\u7bc4\u56f2**: ${f.top.toFixed(1)}px \u301c ${f.bottom.toFixed(1)}px (\u9ad8\u3055: ${f.height.toFixed(1)}px)\n`,
d+=`- **\u30d3\u30e5\u30fc\u30dd\u30fc\u30c8\u9ad8**: ${a.height.toFixed(1)}px\n`,d+=`- **\u30b3\u30f3\u30c6\u30f3\u30c4 Y\u5ea7\u6a19\u7bc4\u56f2**: ${c.top.toFixed(1)}px \u301c ${c.bottom.toFixed(1)}px (\u9ad8\u3055: ${c.height.toFixed(1)}px)\n`,d+=`  - margin-top: ${b.marginTop}\n`,d+=`  - margin-bottom: ${b.marginBottom}\n`,d+=`  - margin-left: ${b.marginLeft}\n`,d+=`  - margin-right: ${b.marginRight}\n`,a=c.bottom>f.top,d+=`  - \u30d8\u30c3\u30c0\u30fc\u3068\u306e\u91cd\u8907: ${c.top<e.bottom?
`\u26a0\ufe0f \u3042\u308a (\u91cd\u8907\u9ad8: ${(e.bottom-c.top).toFixed(1)}px)`:"\u2705 \u306a\u3057"}\n`,d+=`  - \u30d5\u30c3\u30bf\u30fc\u3068\u306e\u91cd\u8907: ${a?`\u26a0\ufe0f \u3042\u308a (\u91cd\u8907\u9ad8: ${(c.bottom-f.top).toFixed(1)}px)`:"\u2705 \u306a\u3057"}\n`,d+=`  - \u30d5\u30c3\u30bf\u30fc\u3068\u306e\u9593\u306e\u4f59\u767d: ${(f.top-c.bottom).toFixed(1)}px\n\n`);return d}
async function pb(a,b,c){for(let d=0;d<a.length;d+=20){const e=a.slice(d,d+20);e.forEach((f,g)=>{c(f,d+g)});b(Math.round((d+e.length)/a.length*100));await new Promise(f=>{"function"===typeof requestAnimationFrame?requestAnimationFrame(()=>{setTimeout(f,0)}):setTimeout(f,0)})}}
async function qb(a,b,c){let d=`### \ud83d\udccf \u53ef\u8996\u8981\u7d20\u306e\u5883\u754c\u5ea7\u6a19\u5206\u5e03 (Y: ${a.top.toFixed(1)}px)\n`,e=0;await pb(b,f=>{c(`\u30ec\u30a4\u30a2\u30a6\u30c8\u5ea7\u6a19\u8a3a\u65ad\u4e2d... ${f}%`)},(f,g)=>{if(!f.classList.contains("empty-line")&&!f.classList.contains("page-break")){var k=f.getBoundingClientRect(),l=k.left-a.left,n=k.right-a.left;if(k.right>=a.left-5&&k.left<=a.right+5){e++;const p=n>a.width+1;d+=`- **\u6bb5\u843d ${g+1} (${f.tagName.toLowerCase()})**: X\u7bc4\u56f2: ${l.toFixed(1)}px \u301c ${n.toFixed(1)}px (\u5e45: ${k.width.toFixed(1)}px) \u300c${f.textContent.trim().substring(0,
15)}...\u300d\n`;-1>l&&(d+=`  - \u26a0\ufe0f **\u306f\u307f\u51fa\u3057**: \u5de6\u5883\u754c\u3092 ${(-l).toFixed(1)}px \u8d85\u904e\u3057\u3066\u3044\u307e\u3059 (\u6b21\u306e\u30da\u30fc\u30b8\u306b\u56de\u308a\u8fbc\u3093\u3067\u3044\u308b\u304b\u3001\u898b\u5207\u308c\u3066\u3044\u307e\u3059)\n`);p&&(d+=`  - \u26a0\ufe0f **\u306f\u307f\u51fa\u3057**: \u53f3\u5883\u754c\u3092 ${(n-a.width).toFixed(1)}px \u8d85\u904e\u3057\u3066\u3044\u307e\u3059 (\u524d\u306e\u30da\u30fc\u30b8\u304b\u3089\u56de\u308a\u8fbc\u3093\u3067\u3044\u308b\u304b\u3001\u898b\u5207\u308c\u3066\u3044\u307e\u3059)\n`)}}});
0===e&&(d+="- (\u53ef\u8996\u6bb5\u843d\u306f\u691c\u51fa\u3055\u308c\u307e\u305b\u3093\u3067\u3057\u305f)\n");return d+="\n"}
async function rb(a,b,c,d){var e=q.locator.resolve(C);const f=q.locator.resolve(r);var g=c-1;g="rtl"===e.direction?-(g*f.readerViewport.clientWidth):g*f.readerViewport.clientWidth;e=Math.abs(f.readerViewport.scrollLeft-g);g="### \ud83d\udcd0 \u30a2\u30e9\u30a4\u30e1\u30f3\u30c8\u691c\u8a3c\n"+`- **\u73fe\u5728\u306e\u30da\u30fc\u30b8\u306e\u7406\u60f3\u30b9\u30af\u30ed\u30fc\u30eb\u4f4d\u7f6e**: ${g}px\n`+`- **\u5b9f\u969b\u306e\u30b9\u30af\u30ed\u30fc\u30eb\u4f4d\u7f6e\u3068\u306e\u30ba\u30ec**: ${e}px\n`;
g=(5<e?g+`  - \u26a0\ufe0f **\u8b66\u544a**: \u30b9\u30af\u30ed\u30fc\u30eb\u4f4d\u7f6e\u304c\u30da\u30fc\u30b8\u306e\u533a\u5207\u308a\u304b\u3089 ${e}px \u30ba\u30ec\u3066\u3044\u307e\u3059\u3002\u6587\u5b57\u304c\u898b\u5207\u308c\u308b\u539f\u56e0\u306b\u306a\u3063\u3066\u3044\u308b\u53ef\u80fd\u6027\u304c\u3042\u308a\u307e\u3059\u3002\n`:g+"  - \u2705 **\u6b63\u5e38**: \u30b9\u30af\u30ed\u30fc\u30eb\u4f4d\u7f6e\u306f\u6b63\u3057\u304f\u914d\u7f6e\u3055\u308c\u3066\u3044\u307e\u3059\u3002\n")+
"\n";g+="### \u26a0\ufe0f \u5883\u754c\u7dda\u4e0a\u3067\u306e\u30c6\u30ad\u30b9\u30c8\u898b\u5207\u308c\u691c\u51fa\n";const k=a.left,l=a.right;let n=0,p=0,t=0,u="";await pb(b,v=>{d(`\u5883\u754c\u898b\u5207\u308c\u8a3a\u65ad\u4e2d... ${v}%`)},(v,H)=>{if(!v.classList.contains("empty-line")&&!v.classList.contains("page-break")){var w=v.getBoundingClientRect();if(w.right>=a.left-50&&w.left<=a.right+50){var D=w.bottom>a.bottom+2;if(w.top<a.top-2||D)u+=`- **\u7e26\u65b9\u5411\u306f\u307f\u51fa\u3057**: \u6bb5\u843d ${H+
1} (${v.tagName.toLowerCase()}) \u304c\u30d3\u30e5\u30fc\u30dd\u30fc\u30c8\u306e\u4e0a\u4e0b\u5883\u754c\u304b\u3089\u306f\u307f\u51fa\u3057\u3066\u3044\u307e\u3059\u3002\n`,u+=`  - \u8981\u7d20 of Y\u5ea7\u6a19\u7bc4\u56f2: ${w.top.toFixed(1)}px \u301c ${w.bottom.toFixed(1)}px (\u30d3\u30e5\u30fc\u30dd\u30fc\u30c8: ${a.top.toFixed(1)}px \u301c ${a.bottom.toFixed(1)}px)\n`,u+=`  - \u30c6\u30ad\u30b9\u30c8\u629c\u7c8b: \u300c${v.textContent.substring(0,30)}...\u300d\n`,t++;D=window.getComputedStyle(v);
D=`[font-size: ${D.fontSize}, line-height: ${D.lineHeight}, font-family: ${D.fontFamily}]`;var A=1===c&&1>Math.abs(f.readerViewport.scrollLeft);if(w.left<k&&w.right>k&&!A&&(A=sb(v,k))){n++;var T=A.context,L=A.rect.left-a.left,ea=A.rect.right-a.left;const Da=a.left-A.rect.left;u+=`- **\u5de6\u5883\u754c\u7dda\u3068\u306e\u4ea4\u5dee**: \u6bb5\u843d ${H+1} (${v.tagName.toLowerCase()}) \u304c\u5de6\u30da\u30fc\u30b8\u5883\u754c (X: ${k.toFixed(1)}px) \u3092\u307e\u305f\u3044\u3067\u3044\u307e\u3059\u3002 ${D}\n`;
u+=`  - \u5883\u754c\u4e0a\u306e\u6587\u5b57: \u300c${T.before}**[${A.char}]**${T.after}\u300d\n`;u+=`  - \u6587\u5b57\u5ea7\u6a19 (viewport\u57fa\u6e96): left: ${L.toFixed(1)}px, right: ${ea.toFixed(1)}px (\u5e45: ${A.rect.width.toFixed(1)}px)\n`;u+=`  - \u5de6\u5883\u754c\u306f\u307f\u51fa\u3057\u91cf (overrun): **${Da.toFixed(1)}px**\n`}w.left<l&&w.right>l&&(w=sb(v,l))&&(p++,A=w.context,T=w.rect.left-a.left,L=w.rect.right-a.left,ea=w.rect.right-a.right,u+=`- **\u53f3\u5883\u754c\u7dda\u3068\u306e\u4ea4\u5dee**: \u6bb5\u843d ${H+
1} (${v.tagName.toLowerCase()}) \u304c\u53f3\u30da\u30fc\u30b8\u5883\u754c (X: ${l.toFixed(1)}px) \u3092\u307e\u305f\u3044\u3067\u3044\u307e\u3059\u3002 ${D}\n`,u+=`  - \u5883\u754c\u4e0a\u306e\u6587\u5b57: \u300c${A.before}**[${w.char}]**${A.after}\u300d\n`,u+=`  - \u6587\u5b57\u5ea7\u6a19 (viewport\u57fa\u6e96): left: ${T.toFixed(1)}px, right: ${L.toFixed(1)}px (\u5e45: ${w.rect.width.toFixed(1)}px)\n`,u+=`  - \u53f3\u5883\u754c\u306f\u307f\u51fa\u3057\u91cf (overrun): **${ea.toFixed(1)}px**\n`)}}});
0===n&&0===p&&0===t?g+="- \u2705 \u5883\u754c\u7dda\u4e0a\u306e\u898b\u5207\u308c\u3084\u306f\u307f\u51fa\u3057\u306f\u691c\u51fa\u3055\u308c\u307e\u305b\u3093\u3067\u3057\u305f\u3002\n":(g+=`- \u691c\u51fa\u30b5\u30de\u30ea\u30fc: \u5de6\u5883\u754c\u307e\u305f\u304e ${n}\u4ef6, \u53f3\u5883\u754c\u307e\u305f\u304e ${p}\u4ef6, \u4e0a\u4e0b\u306f\u307f\u51fa\u3057 ${t}\u4ef6\n\n`,g+=u);return g}
async function tb(){const a=q.locator.resolve(r);if(!a.readerViewport||!a.readerContent)return Promise.resolve("\u30a8\u30e9\u30fc: \u30d3\u30e5\u30fc\u30a2\u30fc\u304c\u521d\u671f\u5316\u3055\u308c\u3066\u3044\u307e\u305b\u3093\u3002");const b=l=>{a.diagnoseReportOutput&&(a.diagnoseReportOutput.textContent=l)};b("\u8a3a\u65ad\u4e2d... \u74b0\u5883\u60c5\u5831\u3092\u53d6\u5f97\u3057\u3066\u3044\u307e\u3059\u3002");const {currentPage:c,A:d}=kb(a.readerViewport);var e=window.getComputedStyle(a.readerContent);
const f=a.readerViewport.getBoundingClientRect(),g=Array.from(a.readerContent.children);let k;k=""+lb(c,d);k+=mb(e);k+=nb(e);k+=ob(f,e);k+=await qb(f,g,b);k+=await rb(f,g,c,b);(e=q.locator.resolve(S))&&e.lastRepairMetrics&&(e=e.lastRepairMetrics,k=k+"### \ud83d\udee0\ufe0f \u30ec\u30a4\u30a2\u30a6\u30c8\u81ea\u5df1\u4fee\u5fa9\u30b9\u30c6\u30fc\u30bf\u30b9\n"+`- **\u4fee\u5fa9\u72b6\u614b**: ${30<=e.passesCount?"\u26a0\ufe0f \u30eb\u30fc\u30d7\u4e0a\u9650\u5230\u9054 (\u672a\u53ce\u675f)":"\u2705 \u53ce\u675f\u5b8c\u4e86 (\u6b63\u5e38)"}\n`,
k+=`- **\u5b9f\u884c\u30d1\u30b9\u6570**: ${e.passesCount}\u56de\n`,k+=`- **\u633f\u5165\u3055\u308c\u305f\u6539\u30da\u30fc\u30b8\u6570**: ${e.insertedCount}\u500b\n`,k+=`- **\u51e6\u7406\u6240\u8981\u6642\u9593**: ${e.durationMs.toFixed(1)}ms\n\n`);b(k);return k}
function sb(a,b){var c=[];a=document.createTreeWalker(a,NodeFilter.SHOW_TEXT,null);for(var d;d=a.nextNode();)c.push(d);for(const e of c)for(c=e.textContent,a=0;a<c.length;a++){d=document.createRange();try{d.setStart(e,a),d.setEnd(e,a+1)}catch(f){continue}d=d.getBoundingClientRect();if(d.left<b-.5&&d.right>b+.5)return{char:c[a],rect:d,context:{before:c.substring(Math.max(0,a-10),a),after:c.substring(a+1,Math.min(c.length,a+11))}}}return null};function ub(a){const b=new Set("div span p h1 h2 h3 h4 h5 h6 a ruby rt rp br img b i strong em".split(" ")),c=new Set(["class","id","src","alt","href"]),d=f=>{var g=Array.from(f.attributes);for(const k of g)if(g=k.name.toLowerCase(),g.startsWith("on")||!c.has(g))f.removeAttribute(k.name);else if("href"===g||"src"===g)g=k.value.trim().toLowerCase(),(g.startsWith("javascript:")||g.startsWith("data:")||g.startsWith("vbscript:"))&&f.removeAttribute(k.name)};d(a);const e=f=>{f=Array.from(f.childNodes);
for(const g of f)if(1===g.nodeType){f=g;const k=f.tagName.toLowerCase();if(b.has(k))d(f),e(f);else{if(!["script","style","iframe"].includes(k))for(;f.firstChild;)f.parentNode.insertBefore(f.firstChild,f);f.remove()}}};e(a)}
function vb(a){const b=wb(a.g.readerContent,a.g.readerViewport);if(b){var c=Array.from(b.parent.children);for(var d=0;d<c.length;d++){var e=c[d];e.classList.contains("page-break")&&(e.style.width="",e.style.height="",e.style.removeProperty("margin-block-end"))}for(d=0;d<c.length;d++)if(e=c[d],e.classList.contains("page-break")){a:{var f=c;var g=d;for(--g;0<=g;g--){var k=f[g];if(!k.classList.contains("page-break")&&!k.classList.contains("empty-line")&&"none"!==window.getComputedStyle(k).display){f=
k;break a}}f=null}g=f;f=b.columnWidth;g&&(f="rtl"===a.h.direction,g=g.getBoundingClientRect(),k=b.parent.getBoundingClientRect(),f=f?k.right-g.left:g.right-k.left,g=Math.max(1,Math.round(a.g.readerViewport.clientWidth/b.step)),f=(Math.floor(Math.floor(f/b.step)/g)+1)*g*b.step-f-b.columnGap);0>=f&&(f=b.columnWidth);e.style.width=`${f}px`;e.style.height="100%";e.style.setProperty("margin-block-end",`${b.columnGap}px`)}}}function xb(a,b,c){const d=[];1<a&&d.push((a-1)*c);a<b&&d.push(a*c);return d}
function yb(a,b,c,d){var e=a.g.readerContent;if(!e)return!1;e=Array.from(e.children);for(const H of b){if(b=!(0>=H))a:{b=a;var f=H,g=e,k=c,l=d;b.paragraphBoundsCache&&0!==b.paragraphBoundsCache.length||b.cacheParagraphBounds();let w=!0;var n=0;for(const D of g)if(D.classList.contains("page-break"))w=!0;else if(!D.classList.contains("empty-line"))if(g=w,w=!1,g)n++;else{b:{g=D;var p=f,t=k,u=l,v=b.paragraphBoundsCache[n];n+=1;if(v&&v.element===g){if(t=v.docRight,v.docLeft<p&&t>p&&zb(g,p,u)){g={v:!0,
u:n};break b}}else{v=g.getBoundingClientRect();const A=v.right+t;if(v.left+t<p&&A>p&&zb(g,p,u)){g={v:!0,u:n};break b}}g={v:!1,u:n}}n=g.u;if(g.v){b=!0;break a}}b=!1}if(b)return!0}return!1}
class S{constructor(){this.g=q.locator.resolve(r);this.h=q.locator.resolve(C);this.lastRepairMetrics={passesCount:0,insertedCount:0,durationMs:0};this.isRepairing=!1;this.paragraphBoundsCache=[];const a=q.locator.resolve(h);a&&a.subscribe("system:layout-repair-requested",()=>{this.adjustPageBreaksForOverrun()})}render(a){if(this.g.readerContent&&(this.paragraphBoundsCache=[],a=(new DOMParser).parseFromString(a,"text/html").body))for(ub(a),this.g.readerContent.innerHTML="";a.firstChild;)this.g.readerContent.appendChild(a.firstChild)}restoreScrollPosition(a,
b=!1){if(this.g.readerViewport){var c=this.g.readerViewport.scrollWidth-this.g.readerViewport.clientWidth;a="rtl"===this.h.direction?-(a*c):a*c;b?this.g.readerViewport.scrollTo({left:a,behavior:"smooth"}):this.g.readerViewport.scrollLeft=a}}scrollToPage(a){if(!this.g.readerViewport)return Promise.resolve();a=(a-1)*this.g.readerViewport.clientWidth;this.g.readerViewport.scrollTo({left:"rtl"===this.h.direction?-a:a,behavior:"smooth"});return new Promise(b=>{setTimeout(b,400)})}handleResize(a){if(!this.g.readerContent||
!this.g.readerViewport)return Promise.resolve();this.paragraphBoundsCache=[];this.g.readerContent.style.width="auto";return new Promise(b=>{setTimeout(()=>{this.g.readerContent.style.width="max-content";var c=q.locator.resolve(h);c&&c.publish("system:layout-check-requested",{scope:"all"});c=Math.abs(this.g.readerViewport.scrollWidth-this.g.readerViewport.clientWidth);this.g.readerViewport.scrollLeft="rtl"===this.h.direction?-(a*c):a*c;b()},100)})}adjustPageBreaksForOverrun(){if(!this.isRepairing&&
this.g.readerContent&&this.g.readerViewport){this.isRepairing=!0;try{const a=this.g.readerContent,b=this.g.readerViewport;a.querySelectorAll(".dynamic-page-break").forEach(l=>l.remove());const c=performance.now(),d=Array.from(a.children).filter(l=>"none"!==window.getComputedStyle(l).display);let e=0;for(;e<d.length;)Ab(d[e],b)&&vb(this),e++;const f=a.querySelectorAll(".dynamic-page-break").length,g=performance.now()-c;this.lastRepairMetrics={passesCount:1,insertedCount:f,durationMs:parseFloat(g.toFixed(1))};
this.g.cachedScrollWidth=null;this.g.cachedClientWidth=null;window.__DEBUG_PERFORMANCE__&&console.log(`[Layout Repair] adjustPageBreaksForOverrun completed in ${g.toFixed(1)}ms. passesCount: 1, insertedCount: ${f}`);this.cacheParagraphBounds();try{const l=q.locator.resolve(F);l&&this.restoreScrollPosition(l.bookmarkProgress,!1)}catch(l){}const k=q.locator.resolve(h);k&&k.publish("system:layout-repaired",this.lastRepairMetrics)}finally{this.isRepairing=!1}}}cacheParagraphBounds(){vb(this);this.paragraphBoundsCache=
[];var a=this.g.readerContent,b=this.g.readerViewport;if(a&&b){a=Array.from(a.children);b=Math.abs(b.scrollLeft);for(const c of a)c.classList.contains("empty-line")||c.classList.contains("page-break")||(a=c.getBoundingClientRect(),this.paragraphBoundsCache.push({element:c,docLeft:a.left+b,docRight:a.right+b}))}}hasOverrunNearCurrentPage(){if(!this.g.readerContent||!this.g.readerViewport)return!1;var a=performance.now(),b=this.g.readerViewport,c=b.clientWidth;if(!c||0>=c)return!1;const d=Math.round(b.scrollWidth/
c)||0;if(1>=d)return!1;const e=Math.abs(b.scrollLeft);c=xb(Math.round(e/c)+1,d,c);if(0===c.length)return!1;Array.from(this.g.readerContent.children).filter(f=>f.classList.contains("empty-line")?!1:"none"!==window.getComputedStyle(f).display);b=yb(this,c,e,b.scrollLeft);a=performance.now()-a;window.__DEBUG_PERFORMANCE__&&console.log(`[Layout Check] hasOverrunNearCurrentPage completed in ${a.toFixed(1)}ms. Result: ${b}`);return b}}
function Ab(a,b){if(a.classList.contains("empty-line")||a.classList.contains("page-break"))return!1;var c=b.clientWidth;if(!c||0>=c)return!1;b=b.scrollLeft;var d=Math.abs(b),e=a.getBoundingClientRect();const f=e.left+d;d=e.right+d;e=[];if(isFinite(f)&&isFinite(d)&&f<d){let k=Math.ceil(f/c)*c,l=0;for(;k<d&&50>l;)0<k&&e.push(k),k+=c,l++}for(var g of e)if(!(g<=f||g>=d)){a:{c=a.previousElementSibling;for(e=0;c&&10>e;){if(c.classList.contains("page-break")){c=!0;break a}if(!c.classList.contains("empty-line"))break;
c=c.previousElementSibling;e++}c=!1}if(c)break;if(zb(a,g,b))return g=document.createElement("div"),g.className="page-break dynamic-page-break",a.parentNode.insertBefore(g,a),!0}return!1}function Bb(a,b){if(3===a.nodeType)a.textContent&&0<a.textContent.trim().length&&b.push(a);else{a=a.firstChild;for(var c=0;a&&1E3>c;)Bb(a,b),a=a.nextSibling,c++}}
function zb(a,b,c){var d=[];Bb(a,d);a=Math.abs(c);c="rtl"===q.locator.resolve(C).direction;for(const n of d){a:{d=n;var e=b;const p=d.textContent;var f;if(!(f=!p)){b:{var g=d;f=e;var k=document.createRange();try{k.selectNodeContents(g)}catch(t){f=!1;break b}g=k.getBoundingClientRect();k=g.right+a;f=g.left+a<f&&k>f}f=!f}if(f)d=null;else{f=0;k=p.length-1;for(g=0;f<=k&&100>g;){g++;const t=Math.floor((f+k)/2);var l=document.createRange();try{l.setStart(d,t),l.setEnd(d,t+1)}catch(H){break}l=l.getBoundingClientRect();
const u=l.left+a,v=l.right+a;if(u<e-.5&&v>e+.5){d={char:p[t],rect:l,context:{before:p.substring(Math.max(0,t-10),t),after:p.substring(t+1,Math.min(p.length,t+11))}};break a}k=c?u>=e-.5?{low:t+1,high:k}:{low:f,high:t-1}:u>=e-.5?{low:f,high:t-1}:{low:t+1,high:k};f=k.low;k=k.high}d=null}}if(d)return d}return null}
function wb(a,b){if(!a||!b)return null;b=b.clientWidth;if(!b||0>=b)return null;var c=window.getComputedStyle(a);b=parseFloat(c.columnWidth);if(!b||isNaN(b))return null;c=parseFloat(c.columnGap);c=isNaN(c)?0:c;return{parent:a,columnWidth:b,columnGap:c,step:b+c}};function Cb(a){a&&q.locator.resolve(G).loadBook(a.name,a.name,function(){return new Promise((b,c)=>{const d=new FileReader;d.onload=function(e){e=e.target.result;var f=new TextDecoder("utf-8",{fatal:!0});try{b(f.decode(e))}catch(g){f=new TextDecoder("shift-jis",{fatal:!1}),b(f.decode(e))}};d.onerror=function(){c(Error("File reading failed."))};d.readAsArrayBuffer(a)})}).then(b=>{N.execute(new za(b.id,b.content))}).catch(b=>{console.error("Failed to load dropped file:",b);alert("\u30d5\u30a1\u30a4\u30eb\u306e\u8aad\u307f\u8fbc\u307f\u306b\u5931\u6557\u3057\u307e\u3057\u305f: "+
b.message)})}
function Db(a){const b=wa.find(c=>c.id===a);b&&q.locator.resolve(G).loadBook(b.title,b.path,function(){return fetch(b.path).then(c=>c.arrayBuffer()).then(c=>{const d=new TextDecoder("utf-8",{fatal:!0});try{return d.decode(c)}catch(e){return console.warn("Shift_JIS decode failed (fatal=true), falling back to UTF-8 for predefined book",e),(new TextDecoder("shift-jis",{fatal:!1})).decode(c)}})}).then(c=>{N.execute(new za(c.id,c.content))}).catch(c=>{console.error("Failed to load predefined book:",c);
alert("\u63a8\u5968\u66f8\u7c4d\u306e\u8aad\u307f\u8fbc\u307f\u306b\u5931\u6557\u3057\u307e\u3057\u305f: "+c.message)})}
async function Eb(){const a=q.locator.resolve(B),b=q.locator.resolve(F),c=q.locator.resolve(r);var d=q.locator.resolve(S);c.cachedScrollWidth=null;c.cachedClientWidth=null;var e="";e=q.locator.resolve(R);if("txt"===a.type)e=e.parseAozoraText(a.content).body;else{var f=e.parseAozoraHTML(a.content);e=f.body;a.title=f.title||a.title.replace(/\.(x?html)/,"")}if(f=wa.find(g=>g.title===a.title||a.title.includes(g.l.toString())))a.title=f.title,a.author=f.author||"";c.bookTitle.textContent=a.title;document.title=
`${a.title} - \u3086\u3046\u305e\u3089`;d.render(e);c.activeHeadingId=a.toc&&0<a.toc.length?a.toc[0].id:null;q.locator.resolve(ha).transitionTo("reader");d=q.locator.resolve(ia);f?(e="#/reader?book="+f.id,d.currentHash=e,window.location.hash=e):(e="#/reader?local="+encodeURIComponent(a.title),d.currentHash=e,window.location.hash=e);d=q.locator.resolve(y);b.bookmarkProgress=await d.load(a.title);c.isReflowing=!0;setTimeout(()=>{try{yuzora.publisher.publish("system:layout-check-requested",{scope:"all"}),
Fb(),U(),yuzora.publisher.publish("document:rendered"),setTimeout(()=>{c.isReflowing=!1},50)}catch(g){document.title="FATAL_ERROR: "+(g instanceof Error?g.message:String(g)),console.error("FATAL_ERROR: ",g),c.isReflowing=!1}},100)}
function U(){const a=q.locator.resolve(r);var b=q.locator.resolve(F);if(a.readerViewport){var c=performance.now(),d=a.cachedScrollWidth,e=a.cachedClientWidth;if(null===d||null===e)d=a.readerViewport.scrollWidth,e=a.readerViewport.clientWidth,a.cachedScrollWidth=d,a.cachedClientWidth=e;var f=d,g=e,k=Math.abs(a.readerViewport.scrollLeft);d=f-g;b.bookmarkProgress=0>=d?0:k/d;var l=Math.min(100,Math.max(0,Math.round(100*b.bookmarkProgress)));null!==a.progressAnimationFrameId&&cancelAnimationFrame(a.progressAnimationFrameId);
a.progressAnimationFrameId=requestAnimationFrame(()=>{a.progressAnimationFrameId=null;a.progressBar&&(a.progressBar.style.width=`${l}%`);a.readingPercentage&&(a.readingPercentage.textContent=`${l}%`);const n=Math.round(f/g),p=Math.min(n,Math.max(1,Math.round(k/g)+1));a.readingIndex&&(a.readingIndex.textContent=`${p} / ${n} \u30da\u30fc\u30b8`)});b=performance.now()-c;window.__DEBUG_PERFORMANCE__&&1<b&&console.log(`[Progress Update] updateProgress logic took ${b.toFixed(2)}ms (DOM writes deferred via rAF)`)}}
function Fb(){const a=q.locator.resolve(F);q.locator.resolve(S).restoreScrollPosition(a.bookmarkProgress,!1)}async function Gb(){const a=q.locator.resolve(B),b=q.locator.resolve(F);a.title&&await b.save(a.title,b.bookmarkProgress)}
function V(){var a=q.locator.resolve(r);if(a.readerViewport){var b=a.cachedClientWidth,c=a.cachedScrollWidth;if(null===b||null===c)b=a.readerViewport.clientWidth,c=a.readerViewport.scrollWidth,a.cachedClientWidth=b,a.cachedScrollWidth=c;a=Math.round(Math.abs(a.readerViewport.scrollLeft)/b)+1;a<Math.round(c/b)&&N.execute(new J(a+1))}}
function W(){var a=q.locator.resolve(r);if(a.readerViewport){var b=a.cachedClientWidth;null===b&&(b=a.readerViewport.clientWidth,a.cachedClientWidth=b);a=Math.round(Math.abs(a.readerViewport.scrollLeft)/b)+1;1<a&&N.execute(new J(a-1))}}
function Hb(a){const b=q.locator.resolve(r),c=q.locator.resolve(F),d=q.locator.resolve(S);let e=b.cachedClientWidth,f=b.cachedScrollWidth;if(null===e||null===f)e=b.readerViewport.clientWidth,f=b.readerViewport.scrollWidth,b.cachedClientWidth=e,b.cachedScrollWidth=f;const g=f,k=e,l=(a-1)*k,n=performance.now();b.isReflowing=!0;d.scrollToPage(a).then(()=>{b.isReflowing=!1;var p=performance.now()-n;window.__DEBUG_PERFORMANCE__&&console.log(`[Page Navigation] Scroll to page ${a} completed in ${p.toFixed(1)}ms`);
yuzora.publisher.publish("ui:page-changed",{page:a});p=g-k;c.bookmarkProgress=0<p?l/p:0;U();Gb()})}function Ib(){const a=q.locator.resolve(r),b=q.locator.resolve(F),c=q.locator.resolve(S);if(!a.isReflowing){a.cachedScrollWidth=null;a.cachedClientWidth=null;a.isReflowing=!0;var d=b.bookmarkProgress;c.handleResize(d).then(()=>{b.bookmarkProgress=d;U();setTimeout(()=>{a.isReflowing=!1},50)})}}
async function La(){const a=q.locator.resolve(B),b=q.locator.resolve(F),c=q.locator.resolve(y);b.bookmarkProgress=await c.load(a.title);Fb();U()}document.addEventListener("DOMContentLoaded",()=>{yuzora.publisher.subscribe("document:loaded",()=>{Eb()});yuzora.publisher.subscribe("ui:navigate-page",a=>{Hb(a.targetPage)})});function Aa(a,b){const c=q.locator.resolve(r),d=q.locator.resolve(C);if("theme"===a)document.body.className=`theme-${b}`;else if("font"===a)c.readerContent.className="reader-content",c.readerContent.classList.add(b,`direction-${d.direction}`,d.size,d.lh,d.spacing),Ib();else if("direction"===a)Ba(),Ib();else if("size"===a||"lh"===a||"spacing"===a)c.readerContent.className="reader-content",c.readerContent.classList.add(d.font,`direction-${d.direction}`,d.size,d.lh,d.spacing),Ib()}
function Jb(){const a=q.locator.resolve(r);a.debugModal.classList.add("hidden");a.debugModalOverlay.classList.add("hidden");document.body.classList.remove("debug-active");Ga()}function Kb(a){var b=q.locator.resolve(r);const c=q.locator.resolve(F);b=b.progressBarContainer.getBoundingClientRect();const d=b.width;c.bookmarkProgress=Math.max(0,Math.min(d,a-b.left))/d;a=q.locator.resolve(F);q.locator.resolve(S).restoreScrollPosition(a.bookmarkProgress,!0);U()}let Lb=[],Mb=[],Nb=null,Ob=null;
function X(a,b,c){a&&(a.addEventListener(b,c,void 0),Lb.push({element:a,type:b,o:c,options:void 0}))}function Y(a,b,c,d){a&&(d=void 0===d?void 0:d||void 0,a.addEventListener(b,c,d),Mb.push({element:a,type:b,o:c,options:d}))}
function Pb(){const a=q.locator.resolve(r),b=q.locator.resolve(ha),c=d=>{if(d){d.innerHTML="";for(let e=0;3>e;e++){const f=document.createElement("div");f.className="book-card-skeleton";f.innerHTML='\n                <div class="skeleton-title-vertical"></div>\n                <div class="skeleton-meta-horizontal"></div>\n            ';d.appendChild(f)}}};("undefined"!==typeof window&&window.requestAnimationFrame?window.requestAnimationFrame:d=>setTimeout(d,16))(()=>{setTimeout(()=>{"welcome"===b.currentSceneName&&
(c(a.developerBooksGrid),c(a.readerBooksGrid),setTimeout(()=>{"welcome"===b.currentSceneName&&(a.developerBooksGrid&&(a.developerBooksGrid.innerHTML="",wa.filter(d=>"developer"===d.i).forEach(d=>{const e=document.createElement("div");e.className="book-card fade-in";e.setAttribute("data-book-id",d.id);e.innerHTML=`
                            <div class="book-card-title">${d.j}</div>
                            <div class="book-card-author">${d.author}</div>
                        `;X(e,"click",()=>{window.location.hash="#/reader?book="+d.id});a.developerBooksGrid.appendChild(e)})),a.readerBooksGrid&&(a.readerBooksGrid.innerHTML="",wa.filter(d=>"reader"===d.i).forEach(d=>{const e=document.createElement("div");e.className="book-card fade-in";e.setAttribute("data-book-id",d.id);e.innerHTML=`
                            <div class="book-card-title">${d.j}</div>
                            <div class="book-card-author">${d.author}</div>
                        `;X(e,"click",()=>{window.location.hash="#/reader?book="+d.id});a.readerBooksGrid.appendChild(e)})))},600))},0)})}
function la(){const a=q.locator.resolve(r);X(a.dropZone,"dragover",b=>{b.preventDefault();a.dropZone.classList.add("dragover")});X(a.dropZone,"dragleave",()=>{a.dropZone.classList.remove("dragover")});X(a.dropZone,"drop",b=>{b.preventDefault();a.dropZone.classList.remove("dragover");Cb(b.dataTransfer.files[0])});X(a.fileInput,"change",b=>{Cb(b.target.files[0])});Pb()}function ma(){Lb.forEach(({element:a,type:b,o:c,options:d})=>{a.removeEventListener(b,c,void 0===d?void 0:d||void 0)});Lb=[]}
function oa(){const a=q.locator.resolve(r),b=q.locator.resolve(C);Y(a.btnBack,"click",()=>{N.execute(new Ja)});let c;Y(a.readerViewport,"scroll",()=>{a.isReflowing||(window.__DEBUG_PERFORMANCE__&&(null===a.scrollStartTimestamp&&(a.scrollStartTimestamp=performance.now(),a.scrollEventCount=0),a.scrollEventCount++),q.locator.resolve(r).isReflowing||U(),clearTimeout(c),c=setTimeout(Qb,150))});Y(a.readerViewport,"click",Rb);Nb=Ib;window.addEventListener("resize",Nb);Ob=g=>{if(!a.readerScreen.classList.contains("hidden")){var k=
a.debugModal&&!a.debugModal.classList.contains("hidden");if(k){if("Tab"===g.key){var l=q.locator.resolve(r).debugModal.querySelectorAll('button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])');k=l[0];l=l[l.length-1];g.shiftKey?document.activeElement===k&&(l.focus(),g.preventDefault()):document.activeElement===l&&(k.focus(),g.preventDefault());return}if("Escape"===g.key){N.execute(new O(!1));return}}if("INPUT"!==g.target.tagName&&"TEXTAREA"!==g.target.tagName&&!g.target.isContentEditable){l=
q.locator.resolve(r);var n=!(!l.debugModal||l.debugModal.classList.contains("hidden"));if("d"===g.key||"D"===g.key)n?Jb():l.btnOpenDebug&&l.btnOpenDebug.click(),g.preventDefault();g.ctrlKey&&("z"===g.key?(g.preventDefault(),N.undo()):"y"===g.key&&(g.preventDefault(),N.redo()));n&&("1"===g.key?l.tabBtnMonitor&&l.tabBtnMonitor.click():"2"===g.key&&l.tabBtnDiagnose&&l.tabBtnDiagnose.click())}k||("rtl"===b.direction?("ArrowLeft"===g.key&&V(),"ArrowRight"===g.key&&W()):("ArrowLeft"===g.key&&W(),"ArrowRight"===
g.key&&V()),"ArrowUp"!==g.key&&"ArrowDown"!==g.key)||(Rb(g),g.preventDefault())}};document.addEventListener("keydown",Ob);let d=0,e=0;Y(a.readerViewport,"touchstart",g=>{1===g.touches.length&&(d=g.touches[0].clientX,e=g.touches[0].clientY)},{passive:!0});Y(a.readerViewport,"touchend",g=>{if(1===g.changedTouches.length){const k=g.changedTouches[0].clientX-d;g=g.changedTouches[0].clientY-e;50<Math.abs(k)&&Math.abs(k)>Math.abs(g)&&("rtl"===b.direction?0<k?V():W():0<k?W():V())}});let f=!1;Y(a.progressBarContainer,
"mousedown",g=>{f=!0;Kb(g.clientX)});Y(document,"mousemove",g=>{f&&Kb(g.clientX)});Y(document,"mouseup",()=>{f&&(f=!1,Gb())});Y(a.progressBarContainer,"touchstart",g=>{f=!0;Kb(g.touches[0].clientX)},{passive:!0});Y(a.progressBarContainer,"touchmove",g=>{f&&Kb(g.touches[0].clientX)},{passive:!0});Y(a.progressBarContainer,"touchend",()=>{f&&(f=!1,Gb())},{passive:!0});Sb();Tb();Ub();Vb();Wb();Xb();Yb()}
function pa(){Mb.forEach(({element:b,type:c,o:d,options:e})=>{b.removeEventListener(c,d,void 0===e?void 0:e||void 0)});Mb=[];Nb&&(window.removeEventListener("resize",Nb),Nb=null);Ob&&(document.removeEventListener("keydown",Ob),Ob=null);const a=q.locator.resolve(r);a.tocObserver&&(a.tocObserver.disconnect(),a.tocObserver=null)}
function Qb(){if(!q.locator.resolve(r).isReflowing){var a=q.locator.resolve(r);if(!a.isReflowing){var b=Math.abs(a.readerViewport.scrollLeft),c=a.cachedClientWidth;null===c&&(c=a.readerViewport.clientWidth,a.cachedClientWidth=c);var d=c;var e=Math.round(b/d);c=e*d;if(5<Math.abs(b-c))d=q.locator.resolve(C),a.isSnapping=!0,window.__DEBUG_PERFORMANCE__&&console.log(`[Scroll Snap] Starting snap to page ${e+1} (target scrollLeft: ${c})`),a.readerViewport.scrollTo({left:"rtl"===d.direction?-c:c,behavior:"smooth"});
else{e+=1;b=a.isSnapping||null!==a.scrollStartTimestamp;a.isSnapping&&(a.isSnapping=!1,window.__DEBUG_PERFORMANCE__&&console.log(`[Scroll Snap] Snap settled at page ${e}`));if(b){b=q.locator.resolve(F);let f=a.cachedScrollWidth;null===f&&(f=a.readerViewport.scrollWidth,a.cachedScrollWidth=f);d=f-d;b.bookmarkProgress=0<d?c/d:0;U();Gb();yuzora.publisher.publish("ui:page-changed",{page:e})}window.__DEBUG_PERFORMANCE__&&null!==a.scrollStartTimestamp&&(c=performance.now()-a.scrollStartTimestamp,d=a.scrollEventCount,
console.log(`[Scroll Performance] Scroll ended. Events: ${d}, Duration: ${c.toFixed(1)}ms, Freq: ${0<c?(d/(c/1E3)).toFixed(1):0} events/sec`),a.scrollStartTimestamp=null,a.scrollEventCount=0)}}}}
function Sb(){const a=q.locator.resolve(r);Y(a.drawerOverlay,"click",()=>{a.settingsDrawer.classList.contains("open")&&N.execute(new M("settings",!1));a.tocDrawer.classList.contains("open")&&N.execute(new M("toc",!1))});Y(a.btnTOC,"click",()=>{N.execute(new M("toc",!0))});Y(a.btnCloseTOC,"click",()=>{N.execute(new M("toc",!1))});Y(a.btnSettings,"click",()=>{N.execute(new M("settings",!0))});Y(a.btnCloseSettings,"click",()=>{N.execute(new M("settings",!1))})}
function Tb(){const a=q.locator.resolve(r),b=q.locator.resolve(C);Y(a.pageNavLeft,"click",c=>{c.stopPropagation();"rtl"===b.direction?V():W()});Y(a.pageNavRight,"click",c=>{c.stopPropagation();"rtl"===b.direction?W():V()});a.btnFirstPage&&Y(a.btnFirstPage,"click",()=>{N.execute(new J(1));N.execute(new M("settings",!1));N.execute(new M("toc",!1))})}
function Ub(){Z(".theme-selector button","theme",a=>{N.execute(new K("theme",a))});Z(".font-selector button","font",a=>{N.execute(new K("font",a))});Z(".direction-selector button","direction",a=>{N.execute(new K("direction",a))});Z(".size-selector button","size",a=>{N.execute(new K("size",a))});Z(".lh-selector button","lh",a=>{N.execute(new K("lh",a))});Z(".spacing-selector button","spacing",a=>{N.execute(new K("spacing",a))})}
function Vb(){const a=q.locator.resolve(r);a.btnClearBookmarks&&Y(a.btnClearBookmarks,"click",()=>{N.execute(new Ka("bookmarks"));alert("\u3059\u3079\u3066\u306e\u3057\u304a\u308a\u3092\u6d88\u53bb\u3057\u307e\u3057\u305f\u3002")});a.btnClearConfig&&Y(a.btnClearConfig,"click",()=>{N.execute(new Ka("config"));alert("\u8868\u793a\u8a2d\u5b9a\u3092\u521d\u671f\u5316\u3057\u307e\u3057\u305f\u3002")});a.btnClearAll&&Y(a.btnClearAll,"click",()=>{N.execute(new Ka("all"));alert("\u3059\u3079\u3066\u306e\u30ad\u30e3\u30c3\u30b7\u30e5\u30c7\u30fc\u30bf\u3092\u30ea\u30bb\u30c3\u30c8\u3057\u307e\u3057\u305f\u3002")})}
function Wb(){const a=q.locator.resolve(r);a.btnCloseDebug&&Y(a.btnCloseDebug,"click",()=>{N.execute(new O(!1))});a.debugModalOverlay&&Y(a.debugModalOverlay,"click",()=>{N.execute(new O(!1))});a.btnOpenDebug&&Y(a.btnOpenDebug,"click",()=>{N.execute(new O(!0))})}
function Xb(){const a=q.locator.resolve(r);a.btnDiagnoseLayout&&Y(a.btnDiagnoseLayout,"click",async()=>{await tb()});a.btnCopyDebugReport&&Y(a.btnCopyDebugReport,"click",()=>{a.diagnoseReportOutput&&(a.diagnoseReportOutput.select(),navigator.clipboard.writeText(a.diagnoseReportOutput.value).then(()=>alert("\u8a3a\u65ad\u30ec\u30dd\u30fc\u30c8\u3092\u30af\u30ea\u30c3\u30d7\u30dc\u30fc\u30c9\u306b\u30b3\u30d4\u30fc\u3057\u307e\u3057\u305f\u3002")).catch(()=>alert("\u30b3\u30d4\u30fc\u306b\u5931\u6557\u3057\u307e\u3057\u305f\u3002")))});
a.btnExportHistory&&Y(a.btnExportHistory,"click",()=>{if(a.debugHistoryJSON){const b=N.exportJSON();a.debugHistoryJSON.value=b;navigator.clipboard.writeText(b).then(()=>alert("\u64cd\u4f5c\u5c65\u6b74JSON\u3092\u30b3\u30d4\u30fc\u3057\u3001\u51fa\u529b\u30a8\u30ea\u30a2\u306b\u8868\u793a\u3057\u307e\u3057\u305f\u3002")).catch(()=>alert("\u30b3\u30d4\u30fc\u306b\u5931\u6557\u3057\u307e\u3057\u305f\u3002"))}});a.btnImportHistory&&Y(a.btnImportHistory,"click",()=>{if(a.debugHistoryJSON){const b=a.debugHistoryJSON.value.trim();
b?N.importJSON(b):alert("\u30a4\u30f3\u30dd\u30fc\u30c8\u7528\u306eJSON\u30c7\u30fc\u30bf\u3092\u30c6\u30ad\u30b9\u30c8\u30a8\u30ea\u30a2\u306b\u5165\u529b\u3057\u3066\u304f\u3060\u3055\u3044\u3002")}})}
function Yb(){const a=q.locator.resolve(r);a.tabBtnMonitor&&a.tabBtnDiagnose&&(Y(a.tabBtnMonitor,"click",()=>{a.tabBtnMonitor.classList.add("active");a.tabBtnDiagnose.classList.remove("active");a.tabContentMonitor.classList.remove("hidden");a.tabContentDiagnose.classList.add("hidden")}),Y(a.tabBtnDiagnose,"click",async()=>{a.tabBtnDiagnose.classList.add("active");a.tabBtnMonitor.classList.remove("active");a.tabContentDiagnose.classList.remove("hidden");a.tabContentMonitor.classList.add("hidden");
await tb()}))}function Z(a,b,c){const d=document.querySelectorAll(a);d.forEach(e=>{Y(e,"click",()=>{const f=e.getAttribute(`data-${b}`);d.forEach(g=>g.classList.remove("active"));e.classList.add("active");c(f)})})}async function Ca(){await q.locator.resolve(C).save()}async function Zb(){await q.locator.resolve(C).load()}function Ba(){q.locator.resolve(C).apply()}
function E(a,b,c){document.querySelectorAll(a).forEach(d=>{d.getAttribute(`data-${b}`)===c?d.classList.add("active"):d.classList.remove("active")})}var $b=null;
function Ia(){function a(){const e=document.createDocumentFragment(),f=Math.min(d+100,c.toc.length);for(;d<f;d++){const g=c.toc[d],k=document.createElement("div");k.className=`toc-item toc-item-level-${g.level}${g.id===b.activeHeadingId?" active":""}`;k.textContent=g.text;k.setAttribute("data-heading-id",g.id);Y(k,"click",()=>{ac(g.id);const l=q.locator.resolve(r);l.tocDrawer.classList.remove("open");l.drawerOverlay.classList.remove("open");Ga()});e.appendChild(k)}b.tocList.appendChild(e);d<c.toc.length?
$b=requestAnimationFrame(a):($b=null,bc())}const b=q.locator.resolve(r),c=q.locator.resolve(B);$b&&(cancelAnimationFrame($b),$b=null);b.tocList.innerHTML="";if(c.toc&&0!==c.toc.length){var d=0;a()}else{const e=document.createElement("div");e.className="toc-item";e.style.cursor="default";e.style.color="var(--text-muted)";e.textContent="\u76ee\u6b21\u60c5\u5831\u306f\u3042\u308a\u307e\u305b\u3093\u3002";b.tocList.appendChild(e)}}var cc=new Set,dc=0;
function ec(){const a=q.locator.resolve(r),b=q.locator.resolve(B);cc.clear();a.tocObserver&&a.tocObserver.disconnect();a.tocObserver=new IntersectionObserver(c=>{c.forEach(d=>{d.isIntersecting?cc.add(d.target.id):cc.delete(d.target.id)});0<cc.size&&Date.now()>=dc&&(c=b.toc.find(d=>cc.has(d.id)))&&(a.activeHeadingId=c.id);a.activeHeadingId&&a.tocDrawer.classList.contains("open")&&bc()},{root:a.readerViewport,threshold:.1});b.toc&&b.toc.forEach(c=>{(c=document.getElementById(c.id))&&a.tocObserver.observe(c)})}
function bc(){const a=q.locator.resolve(r);a.tocList.querySelectorAll(".toc-item").forEach(b=>{b.getAttribute("data-heading-id")===a.activeHeadingId?b.classList.add("active"):b.classList.remove("active")})}
function ac(a){const b=q.locator.resolve(r),c=q.locator.resolve(C),d=document.getElementById(a);if(d){b.activeHeadingId=a;dc=Date.now()+800;a=d.getBoundingClientRect();var e=b.readerViewport.getBoundingClientRect(),f=b.readerViewport.clientWidth,g=0;g="rtl"===c.direction?Math.floor((e.right-a.right+Math.abs(b.readerViewport.scrollLeft)+(e.right-a.left+Math.abs(b.readerViewport.scrollLeft)))/2/f):Math.floor((a.left-e.left+b.readerViewport.scrollLeft+(a.right-e.left+b.readerViewport.scrollLeft))/2/
f);N.execute(new J(g+1));setTimeout(()=>{d.setAttribute("tabindex","-1");d.focus({preventScroll:!0})},400)}}function Ha(){const a=q.locator.resolve(r);a.settingsDrawer.classList.contains("open")||a.tocDrawer.classList.contains("open")||(a.readerHeader.classList.add("hidden"),a.readerFooter&&a.readerFooter.classList.add("hidden"))}
function Ga(){const a=q.locator.resolve(r);a.readerHeader.classList.remove("hidden");a.readerFooter&&a.readerFooter.classList.remove("hidden");clearTimeout(a.headerTimeout);a.headerTimeout=setTimeout(()=>{Ha()},3E3)}function Rb(a){const b=q.locator.resolve(r);a&&"click"===a.type&&(a.target.closest("a")||a.target.closest("ruby")||a.target.closest("button"))||N.execute(new Fa(b.readerHeader.classList.contains("hidden")))};class q{constructor(){this.locator=q.locator;this.publisher=this.locator.resolve(h);this.config=null}async boot(){const a=new ha;a.register("initialize",new ja);a.register("welcome",new ka);a.register("reader",new na);this.locator.register(ha,a);const b=new ia("welcome");this.locator.register(ia,b);this.locator.register(G,new G);var c=new S;this.locator.register(S,c);this.config=this.locator.resolve(C);q.locator.resolve(r).initializeDOMElements();const d=this.locator.resolve(r);b.register("/welcome",
()=>{a.transitionTo("welcome")});b.register("/reader",async f=>{if(f.book)Db(f.book);else if(f.local){const g=await this.locator.resolve(z).load();g&&g.name===f.local?this.locator.resolve(G).loadBook(g.name||"",g.name||"",function(){return Promise.resolve(g.content||"")}).then(k=>{const l=this.locator.resolve(B);l.title=k.id;l.content=k.content;l.type=k.id.endsWith(".html")||k.id.endsWith(".xhtml")?"html":"txt";this.publisher.publish("document:loaded",{fileName:k.id,fileContent:k.content})}).catch(k=>
{console.error("Failed to restore session via ResourceDirector:",k);b.navigate("/welcome")}):(alert("\u30ed\u30fc\u30ab\u30eb\u30d5\u30a1\u30a4\u30eb\u306f\u518d\u30ed\u30fc\u30c9\u304c\u5fc5\u8981\u3067\u3059\u3002"),b.navigate("/welcome"))}else b.navigate("/welcome")});a.transitionTo("initialize");await Zb();Ba();c=await this.locator.resolve(z).load();const e=window.location.hash;c&&c.name&&c.content&&(!e||"#"===e||"#/welcome"===e)&&(window.location.hash="#/reader?local="+encodeURIComponent(c.name));
b.listen();this.publisher.subscribe("document:rendered",()=>{Ga();ec()});this.publisher.subscribe("ui:toggle-debug-modal",f=>{f&&f.open?(f=q.locator.resolve(r),f.debugModal&&f.debugModalOverlay&&(f.debugModal.classList.remove("hidden"),f.debugModalOverlay.classList.remove("hidden"),document.body.classList.add("debug-active"),N.updateDebugMonitor())):Jb()});this.publisher.subscribe("system:history-updated",f=>{d.debugHistoryJSON&&f&&f.history&&(d.debugHistoryJSON.value=JSON.stringify(f.history,null,
2))});this.publisher.subscribe("ui:page-changed",()=>{this.locator.resolve(S).isRepairing||setTimeout(()=>{this.publisher.publish("system:layout-check-requested",{scope:"current"})},0)});this.publisher.subscribe("system:layout-check-requested",f=>{const g=this.locator.resolve(S);g.isRepairing||(f&&"current"===f.scope?g.hasOverrunNearCurrentPage()&&setTimeout(()=>{this.publisher.publish("system:layout-repair-requested")},0):setTimeout(()=>{this.publisher.publish("system:layout-repair-requested")},
0))})}parseAozoraText(a){return this.locator.resolve(R).parseAozoraText(a)}parseAozoraHTML(a){return this.locator.resolve(R).parseAozoraHTML(a)}formatAozoraMarkup(a){return this.locator.resolve(R).formatAozoraMarkup(a)}async runLayoutDiagnosis(){return await tb()}getCurrentTOC(){return this.locator.resolve(B).toc}get CommandManager(){return this.locator.resolve(Pa)}get BookModel(){return B}get ConfigModel(){return C}get BookmarkModel(){return F}get LoadBookCommand(){return za}get NavigatePageCommand(){return J}get UpdateConfigCommand(){return K}get SyncBookmarkCommand(){return Ea}get VerticalRenderer(){return S}get ViewContext(){return r}get AozoraTokenizer(){return cb}get AozoraParser(){return R}get AozoraSemanticAnalyzer(){return eb}get AozoraEvaluator(){return fb}get ASTNode(){return P}}
q.locator=m;const fc=new q;q.locator.register(q,fc);q.locator.register(cb,new cb);q.locator.register(eb,new eb);q.locator.register(fb,new fb);q.locator.register(R,new R);window.yuzora=fc;window.Yuzora=fc;document.addEventListener("DOMContentLoaded",()=>{fc.boot()});
